-- Automatically generated file: Zones

return {
    [0] = {id=0,en="unknown",ja="unknown",search="unknown"},
    [1] = {id=1,en="Phanauet Channel",ja="ファノエ運河",can_invite_cross_zone=true,can_pet=true,search="PhanauetCh"},
    [2] = {id=2,en="Carpenters' Landing",ja="ギルド桟橋",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="CpntLanding"},
    [3] = {id=3,en="Manaclipper",ja="マナクリッパー",can_invite_cross_zone=true,can_pet=true,search="Manaclipper"},
    [4] = {id=4,en="Bibiki Bay",ja="ビビキー湾",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="BibikiBay"},
    [5] = {id=5,en="Uleguerand Range",ja="ウルガラン山脈",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Uleguerand"},
    [6] = {id=6,en="Bearclaw Pinnacle",ja="熊爪嶽",can_pet=true,search="BearclawPn"},
    [7] = {id=7,en="Attohwa Chasm",ja="アットワ地溝",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="AttohwaCsm"},
    [8] = {id=8,en="Boneyard Gully",ja="千骸谷",can_pet=true,search="BoneyardGl"},
    [9] = {id=9,en="Pso'Xja",ja="ソ・ジヤ",can_invite_cross_zone=true,can_pet=true,search="PsoXja"},
    [10] = {id=10,en="The Shrouded Maw",ja="異界の口",can_pet=true,search="ShroudMaw"},
    [11] = {id=11,en="Oldton Movalpolos",ja="ムバルポロス旧市街",can_invite_cross_zone=true,can_pet=true,search="OldMoval"},
    [12] = {id=12,en="Newton Movalpolos",ja="ムバルポロス新市街",can_invite_cross_zone=true,can_pet=true,search="NewMoval"},
    [13] = {id=13,en="Mine Shaft #2716",ja="2716号採石場",can_pet=true,search="Mine2716"},
    [14] = {id=14,en="Hall of Transference",ja="転移の間",can_invite_cross_zone=true,can_pet=true,search="HallOfTrns"},
    [15] = {id=15,en="Abyssea - Konschtat",ja="アビセア-コンシュタット",can_invite_cross_zone=true,can_pet=true,search="AbysKonscht"},
    [16] = {id=16,en="Promyvion - Holla",ja="プロミヴォン-ホラ",can_invite_cross_zone=true,can_pet=true,search="PromvHolla"},
    [17] = {id=17,en="Spire of Holla",ja="ホラの塔",can_pet=true,search="SpireHolla"},
    [18] = {id=18,en="Promyvion - Dem",ja="プロミヴォン-デム",can_invite_cross_zone=true,can_pet=true,search="PromvDem"},
    [19] = {id=19,en="Spire of Dem",ja="デムの塔",can_pet=true,search="SpireDem"},
    [20] = {id=20,en="Promyvion - Mea",ja="プロミヴォン-メア",can_invite_cross_zone=true,can_pet=true,search="PromvMea"},
    [21] = {id=21,en="Spire of Mea",ja="メアの塔",can_pet=true,search="SpireMea"},
    [22] = {id=22,en="Promyvion - Vahzl",ja="プロミヴォン-ヴァズ",can_invite_cross_zone=true,can_pet=true,search="PromvVahzl"},
    [23] = {id=23,en="Spire of Vahzl",ja="ヴァズの塔",can_pet=true,search="SpireVahzl"},
    [24] = {id=24,en="Lufaise Meadows",ja="ルフェーゼ野",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="LufaiseMds"},
    [25] = {id=25,en="Misareaux Coast",ja="ミザレオ海岸",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Misareaux"},
    [26] = {id=26,en="Tavnazian Safehold",ja="タブナジア地下壕",can_invite_cross_zone=true,can_nexus=true,search="TavSafehld"},
    [27] = {id=27,en="Phomiuna Aqueducts",ja="フォミュナ水道",can_invite_cross_zone=true,can_pet=true,search="PhomiunaAq"},
    [28] = {id=28,en="Sacrarium",ja="礼拝堂",can_invite_cross_zone=true,can_pet=true,search="Sacrarium"},
    [29] = {id=29,en="Riverne - Site #B01",ja="リヴェーヌ岩塊群サイトB01",can_invite_cross_zone=true,can_pet=true,search="RiverneB01"},
    [30] = {id=30,en="Riverne - Site #A01",ja="リヴェーヌ岩塊群サイトA01",can_invite_cross_zone=true,can_pet=true,search="RiverneA01"},
    [31] = {id=31,en="Monarch Linn",ja="帝龍の飛泉",can_pet=true,search="MonarchLinn"},
    [32] = {id=32,en="Sealion's Den",ja="海獅子の巣窟",can_pet=true,search="SealionDen"},
    [33] = {id=33,en="Al'Taieu",ja="アル・タユ",can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="AlTaieu"},
    [34] = {id=34,en="Grand Palace of Hu'Xzoi",ja="フ・ゾイの王宮",can_invite_cross_zone=true,can_pet=true,search="HuXzoi"},
    [35] = {id=35,en="The Garden of Ru'Hmet",ja="ル・メトの園",can_invite_cross_zone=true,can_pet=true,search="RuHmet"},
    [36] = {id=36,en="Empyreal Paradox",ja="天象の鎖",can_pet=true,search="EmParadox"},
    [37] = {id=37,en="Temenos",ja="テメナス",can_invite_cross_zone=true,can_pet=true,search="Temenos"},
    [38] = {id=38,en="Apollyon",ja="アポリオン",can_invite_cross_zone=true,can_pet=true,search="Apollyon"},
    [39] = {id=39,en="Dynamis - Valkurm",ja="デュナミス-バルクルム",can_invite_cross_zone=true,can_pet=true,search="DynamisVal"},
    [40] = {id=40,en="Dynamis - Buburimu",ja="デュナミス-ブブリム",can_invite_cross_zone=true,can_pet=true,search="DynamisBub"},
    [41] = {id=41,en="Dynamis - Qufim",ja="デュナミス-クフィム",can_invite_cross_zone=true,can_pet=true,search="DynamisQuf"},
    [42] = {id=42,en="Dynamis - Tavnazia",ja="デュナミス-タブナジア",can_invite_cross_zone=true,can_pet=true,search="DynamisTav"},
    [43] = {id=43,en="Diorama Abdhaljs-Ghelsba",ja="アブダルスの箱庭-ゲルスバ",can_invite_cross_zone=true,can_pet=true,search="DioramaGhel"},
    [44] = {id=44,en="Abdhaljs Isle-Purgonorgo",ja="アブダルスの島-プルゴノルゴ",can_invite_cross_zone=true,can_pet=true,search="AbdhalPurgo"},
    [45] = {id=45,en="Abyssea - Tahrongi",ja="アビセア-タロンギ",can_invite_cross_zone=true,can_pet=true,search="AbysTahrongi"},
    [46] = {id=46,en="Open sea route to Al Zahbi",ja="外洋航路：アルザビ行き",can_invite_cross_zone=true,can_pet=true,search="OpenseaZah"},
    [47] = {id=47,en="Open sea route to Mhaura",ja="外洋航路：マウラ行き",can_invite_cross_zone=true,can_pet=true,search="OpenseaMha"},
    [48] = {id=48,en="Al Zahbi",ja="アルザビ",can_auction=true,can_deliver=true,can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="AlZahbi"},
    [50] = {id=50,en="Aht Urhgan Whitegate",ja="アトルガン白門",can_invite_cross_zone=true,can_nexus=true,search="Whitegate"},
    [51] = {id=51,en="Wajaom Woodlands",ja="ワジャーム樹林",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Wajaom"},
    [52] = {id=52,en="Bhaflau Thickets",ja="バフラウ段丘",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="BhafThicket"},
    [53] = {id=53,en="Nashmau",ja="ナシュモ",can_invite_cross_zone=true,can_nexus=true,search="Nashmau"},
    [54] = {id=54,en="Arrapago Reef",ja="アラパゴ暗礁域",can_invite_cross_zone=true,can_pet=true,search="ArrpgoReef"},
    [55] = {id=55,en="Ilrusi Atoll",ja="イルルシ環礁",can_pet=true,is_layered=true,search="Ilrusi"},
    [56] = {id=56,en="Periqia",ja="ペリキア",can_pet=true,is_layered=true,search="Periqia"},
    [57] = {id=57,en="Talacca Cove",ja="タラッカ入江",can_pet=true,search="Talacca"},
    [58] = {id=58,en="Silver Sea route to Nashmau",ja="銀海航路：ナシュモ行き",can_invite_cross_zone=true,can_pet=true,search="SilvSeaNas"},
    [59] = {id=59,en="Silver Sea route to Al Zahbi",ja="銀海航路：アルザビ行き",can_invite_cross_zone=true,can_pet=true,search="SilvSeaZah"},
    [60] = {id=60,en="The Ashu Talif",ja="アシュタリフ号",can_pet=true,search="AshuTalif"},
    [61] = {id=61,en="Mount Zhayolm",ja="ゼオルム火山",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="MtZhayolm"},
    [62] = {id=62,en="Halvung",ja="ハルブーン",can_invite_cross_zone=true,can_pet=true,search="Halvung"},
    [63] = {id=63,en="Lebros Cavern",ja="レベロス風穴",can_pet=true,is_layered=true,search="Lebros"},
    [64] = {id=64,en="Navukgo Execution Chamber",ja="ナバゴ処刑場",can_pet=true,search="Navukgo"},
    [65] = {id=65,en="Mamook",ja="マムーク",can_invite_cross_zone=true,can_pet=true,search="Mamook"},
    [66] = {id=66,en="Mamool Ja Training Grounds",ja="マムージャ兵訓練所",can_pet=true,is_layered=true,search="MamoolTrGr"},
    [67] = {id=67,en="Jade Sepulcher",ja="翡翠廟",can_pet=true,search="JadeSepul"},
    [68] = {id=68,en="Aydeewa Subterrane",ja="エジワ蘿洞",can_invite_cross_zone=true,can_pet=true,search="Aydeewa"},
    [69] = {id=69,en="Leujaoam Sanctum",ja="ルジャワン霊窟",can_pet=true,is_layered=true,search="Leujaoam"},
    [70] = {id=70,en="Chocobo Circuit",ja="チョコボサーキット",can_invite_cross_zone=true,search="ChocoCirc"},
    [71] = {id=71,en="The Colosseum",ja="コロセウム",can_invite_cross_zone=true,search="Colosseum"},
    [72] = {id=72,en="Alzadaal Undersea Ruins",ja="アルザダール海底遺跡群",can_invite_cross_zone=true,can_pet=true,search="AlzaUndrsea"},
    [73] = {id=73,en="Zhayolm Remnants",ja="ゼオルム遺構",can_pet=true,is_layered=true,search="ZhaylmRem"},
    [74] = {id=74,en="Arrapago Remnants",ja="アラパゴ遺構",can_pet=true,is_layered=true,search="ArrpgoRem"},
    [75] = {id=75,en="Bhaflau Remnants",ja="バフラウ遺構",can_pet=true,is_layered=true,search="BhaflauRem"},
    [76] = {id=76,en="Silver Sea Remnants",ja="銀海遺構",can_pet=true,is_layered=true,search="SilvSeaRem"},
    [77] = {id=77,en="Nyzul Isle",ja="ナイズル島",can_pet=true,is_layered=true,search="Nyzul"},
    [78] = {id=78,en="Hazhalm Testing Grounds",ja="ハザルム試験場",can_pet=true,search="Hazhalm"},
    [79] = {id=79,en="Caedarva Mire",ja="カダーバの浮沼",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Caedarva"},
    [80] = {id=80,en="Southern San d'Oria [S]",ja="南サンドリア〔Ｓ〕",can_deliver=true,can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="SSandOria_S"},
    [81] = {id=81,en="East Ronfaure [S]",ja="東ロンフォール〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="ERonfaure_S"},
    [82] = {id=82,en="Jugner Forest [S]",ja="ジャグナー森林〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Jugner_S"},
    [83] = {id=83,en="Vunkerl Inlet [S]",ja="ブンカール浦〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Vunkerl_S"},
    [84] = {id=84,en="Batallia Downs [S]",ja="バタリア丘陵〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Batallia_S"},
    [85] = {id=85,en="La Vaule [S]",ja="ラヴォール村〔Ｓ〕",can_invite_cross_zone=true,can_pet=true,search="LaVaule_S"},
    [86] = {id=86,en="Everbloom Hollow",ja="常花の石窟",can_pet=true,is_layered=true,search="Everbloom"},
    [87] = {id=87,en="Bastok Markets [S]",ja="バストゥーク商業区〔Ｓ〕",can_deliver=true,can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="BasMarket_S"},
    [88] = {id=88,en="North Gustaberg [S]",ja="北グスタベルグ〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="NGustabrg_S"},
    [89] = {id=89,en="Grauberg [S]",ja="グロウベルグ〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Grauberg_S"},
    [90] = {id=90,en="Pashhow Marshlands [S]",ja="パシュハウ沼〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Pashhow_S"},
    [91] = {id=91,en="Rolanberry Fields [S]",ja="ロランベリー耕地〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="RolFields_S"},
    [92] = {id=92,en="Beadeaux [S]",ja="ベドー〔Ｓ〕",can_invite_cross_zone=true,can_pet=true,search="Beadeaux_S"},
    [93] = {id=93,en="Ruhotz Silvermines",ja="ルホッツ銀山",can_pet=true,is_layered=true,search="Ruhotz"},
    [94] = {id=94,en="Windurst Waters [S]",ja="ウィンダス水の区〔Ｓ〕",can_deliver=true,can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="WinWaters_S"},
    [95] = {id=95,en="West Sarutabaruta [S]",ja="西サルタバルタ〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="WSaruta_S"},
    [96] = {id=96,en="Fort Karugo-Narugo [S]",ja="カルゴナルゴ城砦〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="FortK-N_S"},
    [97] = {id=97,en="Meriphataud Mountains [S]",ja="メリファト山地〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="MeriMount_S"},
    [98] = {id=98,en="Sauromugue Champaign [S]",ja="ソロムグ原野〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="SaurChamp_S"},
    [99] = {id=99,en="Castle Oztroja [S]",ja="オズトロヤ城〔Ｓ〕",can_invite_cross_zone=true,can_pet=true,search="Oztroja_S"},
    [100] = {id=100,en="West Ronfaure",ja="西ロンフォール",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="WRonfaure"},
    [101] = {id=101,en="East Ronfaure",ja="東ロンフォール",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="ERonfaure"},
    [102] = {id=102,en="La Theine Plateau",ja="ラテーヌ高原",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="LaTheine"},
    [103] = {id=103,en="Valkurm Dunes",ja="バルクルム砂丘",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Valkurm"},
    [104] = {id=104,en="Jugner Forest",ja="ジャグナー森林",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Jugner"},
    [105] = {id=105,en="Batallia Downs",ja="バタリア丘陵",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Batallia"},
    [106] = {id=106,en="North Gustaberg",ja="北グスタベルグ",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="NGustaberg"},
    [107] = {id=107,en="South Gustaberg",ja="南グスタベルグ",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="SGustaberg"},
    [108] = {id=108,en="Konschtat Highlands",ja="コンシュタット高地",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Konschtat"},
    [109] = {id=109,en="Pashhow Marshlands",ja="パシュハウ沼",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Pashhow"},
    [110] = {id=110,en="Rolanberry Fields",ja="ロランベリー耕地",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Rolanberry"},
    [111] = {id=111,en="Beaucedine Glacier",ja="ボスディン氷河",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Beaucedine"},
    [112] = {id=112,en="Xarcabard",ja="ザルカバード",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Xarcabard"},
    [113] = {id=113,en="Cape Teriggan",ja="テリガン岬",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Teriggan"},
    [114] = {id=114,en="Eastern Altepa Desert",ja="東アルテパ砂漠",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="EastAltepa"},
    [115] = {id=115,en="West Sarutabaruta",ja="西サルタバルタ",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="WSartabarta"},
    [116] = {id=116,en="East Sarutabaruta",ja="東サルタバルタ",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="ESartabarta"},
    [117] = {id=117,en="Tahrongi Canyon",ja="タロンギ大峡谷",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Tahrongi"},
    [118] = {id=118,en="Buburimu Peninsula",ja="ブブリム半島",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Buburimu"},
    [119] = {id=119,en="Meriphataud Mountains",ja="メリファト山地",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Meriphataud"},
    [120] = {id=120,en="Sauromugue Champaign",ja="ソロムグ原野",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Sauromugue"},
    [121] = {id=121,en="The Sanctuary of Zi'Tah",ja="聖地ジ・タ",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="ZiTah"},
    [122] = {id=122,en="Ro'Maeve",ja="ロ・メーヴ",can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="RoMaeve"},
    [123] = {id=123,en="Yuhtunga Jungle",ja="ユタンガ大森林",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="YuhtunJng"},
    [124] = {id=124,en="Yhoator Jungle",ja="ヨアトル大森林",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="YhoatorJng"},
    [125] = {id=125,en="Western Altepa Desert",ja="西アルテパ砂漠",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="WestAltepa"},
    [126] = {id=126,en="Qufim Island",ja="クフィム島",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Qufim"},
    [127] = {id=127,en="Behemoth's Dominion",ja="ベヒーモスの縄張り",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="BehemotDom"},
    [128] = {id=128,en="Valley of Sorrows",ja="慟哭の谷",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="SorrowVall"},
    [129] = {id=129,en="Ghoyu's Reverie",ja="ゴユの空洞",can_pet=true,is_layered=true,search="GhoyusRev"},
    [130] = {id=130,en="Ru'Aun Gardens",ja="ル・オンの庭",can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="RuAunGard"},
    [131] = {id=131,en="Mordion Gaol",ja="モルディオン監獄",can_invite_cross_zone=true,search="Mordion"},
    [132] = {id=132,en="Abyssea - La Theine",ja="アビセア-ラテーヌ",can_invite_cross_zone=true,can_pet=true,search="AbysLaThein"},
    [133] = {id=133,en="Outer Ra'Kaznar [U2]",ja="ラ・カザナル宮外郭〔Ｕ２〕",can_pet=true,is_layered=true,search="OutRaKaz_U2"},
    [134] = {id=134,en="Dynamis - Beaucedine",ja="デュナミス-ボスディン",can_invite_cross_zone=true,can_pet=true,search="DynamisBcd"},
    [135] = {id=135,en="Dynamis - Xarcabard",ja="デュナミス-ザルカバード",can_invite_cross_zone=true,can_pet=true,search="DynamisXar"},
    [136] = {id=136,en="Beaucedine Glacier [S]",ja="ボスディン氷河〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="BeaGlacier_S"},
    [137] = {id=137,en="Xarcabard [S]",ja="ザルカバード〔Ｓ〕",can_invite_cross_zone=true,can_mount=true,can_nexus=true,can_pet=true,search="Xarcabard_S"},
    [138] = {id=138,en="Castle Zvahl Baileys [S]",ja="ズヴァール城外郭〔Ｓ〕",can_invite_cross_zone=true,can_pet=true,search="ZvBaileys_S"},
    [139] = {id=139,en="Horlais Peak",ja="ホルレーの岩峰",can_pet=true,search="HorlaisPk"},
    [140] = {id=140,en="Ghelsba Outpost",ja="ゲルスバ野営陣",can_invite_cross_zone=true,can_pet=true,search="GhelsbaOp"},
    [141] = {id=141,en="Fort Ghelsba",ja="ゲルスバ砦",can_invite_cross_zone=true,can_pet=true,search="FtGhelsba"},
    [142] = {id=142,en="Yughott Grotto",ja="ユグホトの岩屋",can_invite_cross_zone=true,can_pet=true,search="Yughott"},
    [143] = {id=143,en="Palborough Mines",ja="パルブロ鉱山",can_invite_cross_zone=true,can_pet=true,search="Palborough"},
    [144] = {id=144,en="Waughroon Shrine",ja="ワールンの祠",can_pet=true,search="Waughroon"},
    [145] = {id=145,en="Giddeus",ja="ギデアス",can_invite_cross_zone=true,can_pet=true,search="Giddeus"},
    [146] = {id=146,en="Balga's Dais",ja="バルガの舞台",can_pet=true,search="BalgasDais"},
    [147] = {id=147,en="Beadeaux",ja="ベドー",can_invite_cross_zone=true,can_pet=true,search="Beadeaux"},
    [148] = {id=148,en="Qulun Dome",ja="クゥルンの大伽藍",can_invite_cross_zone=true,can_pet=true,search="QulunDome"},
    [149] = {id=149,en="Davoi",ja="ダボイ",can_invite_cross_zone=true,can_pet=true,search="Davoi"},
    [150] = {id=150,en="Monastic Cavern",ja="修道窟",can_invite_cross_zone=true,can_pet=true,search="MonastiCav"},
    [151] = {id=151,en="Castle Oztroja",ja="オズトロヤ城",can_invite_cross_zone=true,can_pet=true,search="Oztroja"},
    [152] = {id=152,en="Altar Room",ja="祭壇の間",can_invite_cross_zone=true,can_pet=true,search="AltarRoom"},
    [153] = {id=153,en="The Boyahda Tree",ja="ボヤーダ樹",can_invite_cross_zone=true,can_pet=true,search="Boyahda"},
    [154] = {id=154,en="Dragon's Aery",ja="龍のねぐら",can_invite_cross_zone=true,can_pet=true,search="DragonAery"},
    [155] = {id=155,en="Castle Zvahl Keep [S]",ja="ズヴァール城内郭〔Ｓ〕",can_invite_cross_zone=true,can_pet=true,search="ZvKeep_S"},
    [156] = {id=156,en="Throne Room [S]",ja="王の間〔Ｓ〕",can_pet=true,search="ThroneRm_S"},
    [157] = {id=157,en="Middle Delkfutt's Tower",ja="デルクフの塔中層",can_invite_cross_zone=true,can_pet=true,search="MidDelkfut"},
    [158] = {id=158,en="Upper Delkfutt's Tower",ja="デルクフの塔上層",can_invite_cross_zone=true,can_pet=true,search="UpDelkfut"},
    [159] = {id=159,en="Temple of Uggalepih",ja="ウガレピ寺院",can_invite_cross_zone=true,can_pet=true,search="Uggalepih"},
    [160] = {id=160,en="Den of Rancor",ja="怨念洞",can_invite_cross_zone=true,can_pet=true,search="RancorDen"},
    [161] = {id=161,en="Castle Zvahl Baileys",ja="ズヴァール城外郭",can_invite_cross_zone=true,can_pet=true,search="ZvahlBails"},
    [162] = {id=162,en="Castle Zvahl Keep",ja="ズヴァール城内郭",can_invite_cross_zone=true,can_pet=true,search="ZvahlKeep"},
    [163] = {id=163,en="Sacrificial Chamber",ja="生贄の間",can_pet=true,search="SacriChamb"},
    [164] = {id=164,en="Garlaige Citadel [S]",ja="ガルレージュ要塞〔Ｓ〕",can_invite_cross_zone=true,can_pet=true,search="Garlaige_S"},
    [165] = {id=165,en="Throne Room",ja="王の間",can_pet=true,search="ThroneRoom"},
    [166] = {id=166,en="Ranguemont Pass",ja="ラングモント峠",can_invite_cross_zone=true,can_pet=true,search="Ranguemont"},
    [167] = {id=167,en="Bostaunieux Oubliette",ja="ボストーニュ監獄",can_invite_cross_zone=true,can_pet=true,search="Bostaunieu"},
    [168] = {id=168,en="Chamber of Oracles",ja="宣託の間",can_pet=true,search="OracleChmb"},
    [169] = {id=169,en="Toraimarai Canal",ja="トライマライ水路",can_invite_cross_zone=true,can_pet=true,search="Toraimarai"},
    [170] = {id=170,en="Full Moon Fountain",ja="満月の泉",can_pet=true,search="FullMoonFn"},
    [171] = {id=171,en="Crawlers' Nest [S]",ja="クロウラーの巣〔Ｓ〕",can_invite_cross_zone=true,can_pet=true,search="CrawlNest_S"},
    [172] = {id=172,en="Zeruhn Mines",ja="ツェールン鉱山",can_invite_cross_zone=true,can_pet=true,search="Zeruhn"},
    [173] = {id=173,en="Korroloka Tunnel",ja="コロロカの洞門",can_invite_cross_zone=true,can_pet=true,search="Korroloka"},
    [174] = {id=174,en="Kuftal Tunnel",ja="クフタルの洞門",can_invite_cross_zone=true,can_pet=true,search="Kuftal"},
    [175] = {id=175,en="The Eldieme Necropolis [S]",ja="エルディーム古墳〔Ｓ〕",can_invite_cross_zone=true,can_pet=true,search="Eldieme_S"},
    [176] = {id=176,en="Sea Serpent Grotto",ja="海蛇の岩窟",can_invite_cross_zone=true,can_pet=true,search="SeaGrotto"},
    [177] = {id=177,en="Ve'Lugannon Palace",ja="ヴェ・ルガノン宮殿",can_invite_cross_zone=true,can_pet=true,search="VeLugannon"},
    [178] = {id=178,en="The Shrine of Ru'Avitau",ja="ル・アビタウ神殿",can_invite_cross_zone=true,can_pet=true,search="RuAvitau"},
    [179] = {id=179,en="Stellar Fulcrum",ja="天輪の場",can_pet=true,search="StlrFulcrm"},
    [180] = {id=180,en="La'Loff Amphitheater",ja="ラ・ロフの劇場",can_pet=true,search="LaLoff"},
    [181] = {id=181,en="The Celestial Nexus",ja="宿星の座",can_pet=true,search="CelesNexus"},
    [182] = {id=182,en="Walk of Echoes",ja="ウォークオブエコーズ",can_invite_cross_zone=true,can_pet=true,search="WalkEchoes"},
    [183] = {id=183,en="Maquette Abdhaljs-LegionA",ja="アブダルスの模型-レギオンA",can_pet=true,is_layered=true,search="LegionA"},
    [184] = {id=184,en="Lower Delkfutt's Tower",ja="デルクフの塔下層",can_invite_cross_zone=true,can_pet=true,search="LowDelkfut"},
    [185] = {id=185,en="Dynamis - San d'Oria",ja="デュナミス-サンドリア",can_invite_cross_zone=true,can_pet=true,search="DynamisSan"},
    [186] = {id=186,en="Dynamis - Bastok",ja="デュナミス-バストゥーク",can_invite_cross_zone=true,can_pet=true,search="DynamisBas"},
    [187] = {id=187,en="Dynamis - Windurst",ja="デュナミス-ウィンダス",can_invite_cross_zone=true,can_pet=true,search="DynamisWin"},
    [188] = {id=188,en="Dynamis - Jeuno",ja="デュナミス-ジュノ",can_invite_cross_zone=true,can_pet=true,search="DynamisJeu"},
    [189] = {id=189,en="Outer Ra'Kaznar [U3]",ja="ラ・カザナル宮外郭〔Ｕ３〕",can_pet=true,is_layered=true,search="OutRaKaz_U3"},
    [190] = {id=190,en="King Ranperre's Tomb",ja="龍王ランペールの墓",can_invite_cross_zone=true,can_pet=true,search="RanpsTomb"},
    [191] = {id=191,en="Dangruf Wadi",ja="ダングルフの涸れ谷",can_invite_cross_zone=true,can_pet=true,search="Dangruf"},
    [192] = {id=192,en="Inner Horutoto Ruins",ja="内ホルトト遺跡",can_invite_cross_zone=true,can_pet=true,search="InHorutoto"},
    [193] = {id=193,en="Ordelle's Caves",ja="オルデール鍾乳洞",can_invite_cross_zone=true,can_pet=true,search="Ordelles"},
    [194] = {id=194,en="Outer Horutoto Ruins",ja="外ホルトト遺跡",can_invite_cross_zone=true,can_pet=true,search="OutHorutot"},
    [195] = {id=195,en="The Eldieme Necropolis",ja="エルディーム古墳",can_invite_cross_zone=true,can_pet=true,search="Eldieme"},
    [196] = {id=196,en="Gusgen Mines",ja="グスゲン鉱山",can_invite_cross_zone=true,can_pet=true,search="Gusgen"},
    [197] = {id=197,en="Crawlers' Nest",ja="クロウラーの巣",can_invite_cross_zone=true,can_pet=true,search="CrawlNest"},
    [198] = {id=198,en="Maze of Shakhrami",ja="シャクラミの地下迷宮",can_invite_cross_zone=true,can_pet=true,search="Shakhrami"},
    [200] = {id=200,en="Garlaige Citadel",ja="ガルレージュ要塞",can_invite_cross_zone=true,can_pet=true,search="Garlaige"},
    [201] = {id=201,en="Cloister of Gales",ja="突風の回廊",can_pet=true,search="ClstGales"},
    [202] = {id=202,en="Cloister of Storms",ja="雷鳴の回廊",can_pet=true,search="ClstStorms"},
    [203] = {id=203,en="Cloister of Frost",ja="凍結の回廊",can_pet=true,search="ClstFrost"},
    [204] = {id=204,en="Fei'Yin",ja="フェ・イン",can_invite_cross_zone=true,can_pet=true,search="FeiYin"},
    [205] = {id=205,en="Ifrit's Cauldron",ja="イフリートの釜",can_invite_cross_zone=true,can_pet=true,search="IfritCldrn"},
    [206] = {id=206,en="Qu'Bia Arena",ja="ク・ビアの闘技場",can_pet=true,search="QuBiaArena"},
    [207] = {id=207,en="Cloister of Flames",ja="灼熱の回廊",can_pet=true,search="ClstFlames"},
    [208] = {id=208,en="Quicksand Caves",ja="流砂洞",can_invite_cross_zone=true,can_pet=true,search="Quicksands"},
    [209] = {id=209,en="Cloister of Tremors",ja="震動の回廊",can_pet=true,search="ClstTremor"},
    [211] = {id=211,en="Cloister of Tides",ja="海流の回廊",can_pet=true,search="ClstTides"},
    [212] = {id=212,en="Gustav Tunnel",ja="グスタフの洞門",can_invite_cross_zone=true,can_pet=true,search="Gustav"},
    [213] = {id=213,en="Labyrinth of Onzozo",ja="オンゾゾの迷路",can_invite_cross_zone=true,can_pet=true,search="Onzozo"},
    [215] = {id=215,en="Abyssea - Attohwa",ja="アビセア-アットワ",can_invite_cross_zone=true,can_pet=true,search="AbysAttohwa"},
    [216] = {id=216,en="Abyssea - Misareaux",ja="アビセア-ミザレオ",can_invite_cross_zone=true,can_pet=true,search="AbysMisar"},
    [217] = {id=217,en="Abyssea - Vunkerl",ja="アビセア-ブンカール",can_invite_cross_zone=true,can_pet=true,search="AbysVunkerl"},
    [218] = {id=218,en="Abyssea - Altepa",ja="アビセア-アルテパ",can_invite_cross_zone=true,can_pet=true,search="AbysAltepa"},
    [220] = {id=220,en="Ship bound for Selbina",ja="航路：セルビナ行き",can_invite_cross_zone=true,can_pet=true,search="ShipToSelb"},
    [221] = {id=221,en="Ship bound for Mhaura",ja="航路：マウラ行き",can_invite_cross_zone=true,can_pet=true,search="ShipToMhau"},
    [222] = {id=222,en="Provenance",ja="真界",can_pet=true,search="Provenance"},
    [223] = {id=223,en="San d'Oria-Jeuno Airship",ja="飛空艇航路",can_invite_cross_zone=true,search="Airship"},
    [224] = {id=224,en="Bastok-Jeuno Airship",ja="飛空艇航路",can_invite_cross_zone=true,search="Airship"},
    [225] = {id=225,en="Windurst-Jeuno Airship",ja="飛空艇航路",can_invite_cross_zone=true,search="Airship"},
    [226] = {id=226,en="Kazham-Jeuno Airship",ja="飛空艇航路",can_invite_cross_zone=true,search="Airship"},
    [227] = {id=227,en="Ship bound for Selbina",ja="航路：セルビナ行き",can_invite_cross_zone=true,can_pet=true,search="ShipToSelb"},
    [228] = {id=228,en="Ship bound for Mhaura",ja="航路：マウラ行き",can_invite_cross_zone=true,can_pet=true,search="ShipToMhau"},
    [229] = {id=229,en="Throne Room [V]",ja="王の間〔Ｖ〕",can_pet=true,is_layered=true,search="ThroneRm_V"},
    [230] = {id=230,en="Southern San d'Oria",ja="南サンドリア",can_invite_cross_zone=true,can_nexus=true,search="SSandOria"},
    [231] = {id=231,en="Northern San d'Oria",ja="北サンドリア",can_invite_cross_zone=true,can_nexus=true,search="NSandOria"},
    [232] = {id=232,en="Port San d'Oria",ja="サンドリア港",can_invite_cross_zone=true,can_nexus=true,search="PSandOria"},
    [233] = {id=233,en="Chateau d'Oraguille",ja="ドラギーユ城",can_invite_cross_zone=true,search="ChatdOrag"},
    [234] = {id=234,en="Bastok Mines",ja="バストゥーク鉱山区",can_invite_cross_zone=true,can_nexus=true,search="BastokMine"},
    [235] = {id=235,en="Bastok Markets",ja="バストゥーク商業区",can_invite_cross_zone=true,can_nexus=true,search="BastokMark"},
    [236] = {id=236,en="Port Bastok",ja="バストゥーク港",can_invite_cross_zone=true,can_nexus=true,search="PortBastok"},
    [237] = {id=237,en="Metalworks",ja="大工房",can_invite_cross_zone=true,can_nexus=true,search="Metalworks"},
    [238] = {id=238,en="Windurst Waters",ja="ウィンダス水の区",can_invite_cross_zone=true,can_nexus=true,search="WindWaters"},
    [239] = {id=239,en="Windurst Walls",ja="ウィンダス石の区",can_invite_cross_zone=true,can_nexus=true,search="WindWalls"},
    [240] = {id=240,en="Port Windurst",ja="ウィンダス港",can_invite_cross_zone=true,can_nexus=true,search="PortWind"},
    [241] = {id=241,en="Windurst Woods",ja="ウィンダス森の区",can_invite_cross_zone=true,can_nexus=true,search="WindWoods"},
    [242] = {id=242,en="Heavens Tower",ja="天の塔",can_invite_cross_zone=true,can_nexus=true,search="HeavenTowr"},
    [243] = {id=243,en="Ru'Lude Gardens",ja="ル・ルデの庭",can_invite_cross_zone=true,can_nexus=true,search="RuLudeGard"},
    [244] = {id=244,en="Upper Jeuno",ja="ジュノ上層",can_invite_cross_zone=true,can_nexus=true,search="UpJeuno"},
    [245] = {id=245,en="Lower Jeuno",ja="ジュノ下層",can_invite_cross_zone=true,can_nexus=true,search="LowJeuno"},
    [246] = {id=246,en="Port Jeuno",ja="ジュノ港",can_invite_cross_zone=true,can_nexus=true,search="PortJeuno"},
    [247] = {id=247,en="Rabao",ja="ラバオ",can_invite_cross_zone=true,can_nexus=true,search="Rabao"},
    [248] = {id=248,en="Selbina",ja="セルビナ",can_invite_cross_zone=true,can_nexus=true,search="Selbina"},
    [249] = {id=249,en="Mhaura",ja="マウラ",can_invite_cross_zone=true,can_nexus=true,search="Mhaura"},
    [250] = {id=250,en="Kazham",ja="カザム",can_invite_cross_zone=true,can_nexus=true,search="Kazham"},
    [251] = {id=251,en="Hall of the Gods",ja="神々の間",can_invite_cross_zone=true,search="HallOfGods"},
    [252] = {id=252,en="Norg",ja="ノーグ",can_invite_cross_zone=true,can_nexus=true,search="Norg"},
    [253] = {id=253,en="Abyssea - Uleguerand",ja="アビセア-ウルガラン",can_invite_cross_zone=true,can_pet=true,search="AbysUleg"},
    [254] = {id=254,en="Abyssea - Grauberg",ja="アビセア-グロウベルグ",can_invite_cross_zone=true,can_pet=true,search="AbysGraub"},
    [255] = {id=255,en="Abyssea - Empyreal Paradox",ja="アビセア-天象の鎖",can_pet=true,search="AbysParadox"},
    [256] = {id=256,en="Western Adoulin",ja="西アドゥリン",can_invite_cross_zone=true,can_nexus=true,search="WestAdoulin"},
    [257] = {id=257,en="Eastern Adoulin",ja="東アドゥリン",can_invite_cross_zone=true,can_nexus=true,search="EastAdoulin"},
    [258] = {id=258,en="Rala Waterways",ja="ララ水道",can_invite_cross_zone=true,can_pet=true,search="Rala"},
    [259] = {id=259,en="Rala Waterways [U]",ja="ララ水道〔Ｕ〕",can_pet=true,is_layered=true,search="Rala_U"},
    [260] = {id=260,en="Yahse Hunting Grounds",ja="ヤッセの狩り場",can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="Yahse"},
    [261] = {id=261,en="Ceizak Battlegrounds",ja="ケイザック古戦場",can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="Ceizak"},
    [262] = {id=262,en="Foret de Hennetiel",ja="エヌティエル水林",can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="Hennetiel"},
    [263] = {id=263,en="Yorcia Weald",ja="ヨルシア森林",can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="Yorcia"},
    [264] = {id=264,en="Yorcia Weald [U]",ja="ヨルシア森林〔Ｕ〕",can_pet=true,is_layered=true,search="Yorcia_U"},
    [265] = {id=265,en="Morimar Basalt Fields",ja="モリマー台地",can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="Morimar"},
    [266] = {id=266,en="Marjami Ravine",ja="マリアミ渓谷",can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="Marjami"},
    [267] = {id=267,en="Kamihr Drifts",ja="カミール山麓",can_invite_cross_zone=true,can_nexus=true,can_pet=true,search="Kamihr"},
    [268] = {id=268,en="Sih Gates",ja="シィの門",can_invite_cross_zone=true,can_pet=true,search="SihGates"},
    [269] = {id=269,en="Moh Gates",ja="モーの門",can_invite_cross_zone=true,can_pet=true,search="MohGates"},
    [270] = {id=270,en="Cirdas Caverns",ja="シルダス洞窟",can_invite_cross_zone=true,can_pet=true,search="Cirdas"},
    [271] = {id=271,en="Cirdas Caverns [U]",ja="シルダス洞窟〔Ｕ〕",can_pet=true,is_layered=true,search="Cirdas_U"},
    [272] = {id=272,en="Dho Gates",ja="ドーの門",can_invite_cross_zone=true,can_pet=true,search="DhoGates"},
    [273] = {id=273,en="Woh Gates",ja="ウォーの門",can_invite_cross_zone=true,can_pet=true,search="WohGates"},
    [274] = {id=274,en="Outer Ra'Kaznar",ja="ラ・カザナル宮外郭",can_invite_cross_zone=true,can_pet=true,search="OutRaKaz"},
    [275] = {id=275,en="Outer Ra'Kaznar [U1]",ja="ラ・カザナル宮外郭〔Ｕ１〕",can_pet=true,is_layered=true,search="OutRaKaz_U1"},
    [276] = {id=276,en="Ra'Kaznar Inner Court",ja="ラ・カザナル宮内郭",can_invite_cross_zone=true,can_pet=true,search="InRaKaz"},
    [277] = {id=277,en="Ra'Kaznar Turris",ja="ラ・カザナル宮天守",can_pet=true,search="RaKazTurris"},
    [278] = {id=278,en="Gwora - Corridor",ja="グォラ-歩廊",can_pet=true,is_layered=true,search="GworaCorr"},
    [279] = {id=279,en="Walk of Echoes [P2]",ja="ウォークオブエコーズ〔Ｐ２〕",can_pet=true,is_layered=true,search="WlkEchoes_P2"},
    [280] = {id=280,en="Mog Garden",ja="モグガーデン",can_deliver=true,can_invite_cross_zone=true,is_layered=true,search="MogGarden"},
    [281] = {id=281,en="Leafallia",ja="リファーリア",can_invite_cross_zone=true,can_nexus=true,search="Leafallia"},
    [282] = {id=282,en="Mount Kamihr",ja="カミール山",can_invite_cross_zone=true,search="MtKamihr"},
    [283] = {id=283,en="Silver Knife",ja="シルバー・ナイフ",can_invite_cross_zone=true,search="SilverKnife"},
    [284] = {id=284,en="Celennia Memorial Library",ja="セレニア図書館",can_invite_cross_zone=true,search="Celennia"},
    [285] = {id=285,en="Feretory",ja="魂の聖櫃",can_invite_cross_zone=true,search="Feretory"},
    [287] = {id=287,en="Maquette Abdhaljs-LegionB",ja="アブダルスの模型-レギオンB",can_pet=true,is_layered=true,search="LegionB"},
    [288] = {id=288,en="Escha - Zi'Tah",ja="エスカ-ジ・タ",can_invite_cross_zone=true,can_pet=true,search="EschaZiTah"},
    [289] = {id=289,en="Escha - Ru'Aun",ja="エスカ-ル・オン",can_invite_cross_zone=true,can_pet=true,search="EschaRuAun"},
    [290] = {id=290,en="Desuetia - Empyreal Paradox",ja="デスエチア-天象の鎖",can_pet=true,is_layered=true,search="DesParadox"},
    [291] = {id=291,en="Reisenjima",ja="醴泉島",can_invite_cross_zone=true,can_pet=true,search="Reisenjima"},
    [292] = {id=292,en="Reisenjima Henge",ja="醴泉島-秘境",can_pet=true,is_layered=true,search="ReisenHenge"},
    [293] = {id=293,en="Reisenjima Sanctorium",ja="醴泉島の祠",can_pet=true,search="ReisenSanc"},
    [294] = {id=294,en="Dynamis - San d'Oria [D]",ja="デュナミス-サンドリア〔Ｄ〕",can_pet=true,is_layered=true,search="DynamisSan_D"},
    [295] = {id=295,en="Dynamis - Bastok [D]",ja="デュナミス-バストゥーク〔Ｄ〕",can_pet=true,is_layered=true,search="DynamisBas_D"},
    [296] = {id=296,en="Dynamis - Windurst [D]",ja="デュナミス-ウィンダス〔Ｄ〕",can_pet=true,is_layered=true,search="DynamisWin_D"},
    [297] = {id=297,en="Dynamis - Jeuno [D]",ja="デュナミス-ジュノ〔Ｄ〕",can_pet=true,is_layered=true,search="DynamisJeu_D"},
    [298] = {id=298,en="Walk of Echoes [P1]",ja="ウォークオブエコーズ〔Ｐ１〕",can_pet=true,is_layered=true,search="WlkEchoes_P1"},
}, {"id", "en", "ja", "search", "can_invite_cross_zone", "can_pet", "can_mount", "can_nexus", "can_auction", "can_deliver", "is_layered"}

--[[
Copyright © 2013-2023, Windower
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Windower nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Windower BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
