-- Automatically generated file: Ability Recasts

return {
    [0] = {id=0,en="SP Ability",ja="SPアビリティ",de="SP Fähigkeit",fr="SP aptitude"},
    [1] = {id=1,en="Berserk",ja="バーサク",de="Berserker",fr="Berserk"},
    [2] = {id=2,en="Warcry",ja="ウォークライ",de="Kampfschrei",fr="Cri de guerre"},
    [3] = {id=3,en="Defender",ja="ディフェンダー",de="Defender",fr="Défenseur"},
    [4] = {id=4,en="Aggressor",ja="アグレッサー",de="Aggressor",fr="Agresseur"},
    [5] = {id=5,en="Provoke",ja="挑発",de="Provozieren",fr="Provocation"},
    [6] = {id=6,en="Warrior's Charge",ja="ウォリアーチャージ",de="Kriegerwut",fr="Charge guerrier"},
    [7] = {id=7,en="Tomahawk",ja="トマホーク",de="Tomahawk",fr="Tomahawk"},
    [8] = {id=8,en="Retaliation",ja="リタリエーション",de="Sühne",fr="Contre-attaque"},
    [9] = {id=9,en="Restraint",ja="リストレント",de="Beherrschung",fr="Retenue"},
    [10] = {id=10,en="Rune Enchantment",ja="エンチャントルーン",de="Verzauber.-Rune",fr="Runes enchant."},
    [11] = {id=11,en="Blood Rage",ja="ブラッドレイジ",de="Blutrausch",fr="Rage sanguinaire"},
    [13] = {id=13,en="Focus",ja="集中",de="Fokus",fr="Précision"},
    [14] = {id=14,en="Dodge",ja="回避",de="Trick",fr="Esquive +"},
    [15] = {id=15,en="Chakra",ja="チャクラ",de="Chakra",fr="Chakra"},
    [16] = {id=16,en="Boost",ja="ためる",de="Boost",fr="Accumulation"},
    [17] = {id=17,en="Counterstance",ja="かまえる",de="Gegenzug",fr="Qui-vive"},
    [18] = {id=18,en="Chi Blast",ja="気孔弾",de="Chi-Stoß",fr="Rafale de chi"},
    [19] = {id=19,en="Mantra",ja="マントラ",de="Mantra",fr="Mantra"},
    [20] = {id=20,en="Formless Strikes",ja="無想無念",de="Formlose Schläge",fr="Coups informes"},
    [21] = {id=21,en="Footwork",ja="猫足立ち",de="Beinarbeit",fr="Jeu de jambes"},
    [22] = {id=22,en="Perfect Counter",ja="絶対カウンター",de="Super-Konter",fr="Riposte absolue"},
    [23] = {id=23,en="Vallation",ja="ヴァレション",de="Wall",fr="Vallation"},
    [24] = {id=24,en="Swordplay",ja="ソードプレイ",de="Fechtkunst",fr="Jeu d'épée"},
    [25] = {id=25,en="Lunge",ja="ランジ",de="Sprunghieb",fr="Fente"},
    [26] = {id=26,en="Divine Seal",ja="女神の印",de="Göttersiegel",fr="Sceau divin"},
    [27] = {id=27,en="Martyr",ja="マーター",de="Märtyrer",fr="Martyr"},
    [28] = {id=28,en="Devotion",ja="デヴォーション",de="Hingabe",fr="Dévotion"},
    [29] = {id=29,en="Afflatus Solace",ja="ハートオブソラス",de="Afflatus solatii",fr="Consolation"},
    [30] = {id=30,en="Afflatus Misery",ja="ハートオブミゼリ",de="Afflatus misariae",fr="Adversité"},
    [31] = {id=31,en="Impetus",ja="インピタス",de="Impetus",fr="Impulsivité"},
    [32] = {id=32,en="Divine Caress",ja="女神の愛撫",de="Göttersalbung",fr="Caresse divine"},
    [33] = {id=33,en="Sacrosanctity",ja="女神の聖域",de="Sacrosanctitas",fr="Sacro-sainteté"},
    [34] = {id=34,en="Enmity Douse",ja="エンミティダウス",de="Schlichtung",fr="Pacification"},
    [35] = {id=35,en="Manawell",ja="魔力の雫",de="Mana-Quell",fr="Rosée de Mana"},
    [36] = {id=36,en="Saboteur",ja="サボトゥール",de="Debilitas ",fr="Persévérance"},
    [37] = {id=37,en="Spontaneity",ja="クイックマジック",de="Spontanität",fr="Spontanéité"},
    [38] = {id=38,en="Elemental Seal",ja="精霊の印",de="Elementar-Siegel",fr="Sceau élément."},
    [39] = {id=39,en="Mana Wall",ja="マナウォール",de="Mana-Wall",fr="Barrière de Mana"},
    [40] = {id=40,en="Conspirator",ja="コンスピレーター",de="Verschwörer",fr="Conspirateur"},
    [41] = {id=41,en="Sepulcher",ja="セプルカー",de="Sakr. Bannspruch",fr="Nexus sépulcral"},
    [42] = {id=42,en="Palisade",ja="パリセード",de="Palisade",fr="Palissade"},
    [43] = {id=43,en="Arcane Crest",ja="アルケインクレスト",de="Arcanabann",fr="Nexus arcanique"},
    [44] = {id=44,en="Scarlet Delirium",ja="レッドデリリアム",de="Leidensdelirium",fr="Frénésie écarlate"},
    [45] = {id=45,en="Spur",ja="きばれ",de="Anspornen",fr="En avant !"},
    [46] = {id=46,en="Run Wild",ja="ふりしぼれ",de="Freilauf",fr="Déchaîne-toi !"},
    [47] = {id=47,en="Tenuto",ja="テヌート",de="Tenuto",fr="Tenuto"},
    [48] = {id=48,en="Marcato",ja="マルカート",de="Marcato",fr="Marcato"},
    [49] = {id=49,en="Convert",ja="コンバート",de="Austauschen",fr="Conversion"},
    [50] = {id=50,en="Composure",ja="コンポージャー",de="Fassung",fr="Aplomb"},
    [51] = {id=51,en="Bounty Shot",ja="バウンティショット",de="Goldener Pfeil",fr="Tir détrousseur"},
    [52] = {id=52,en="Decoy Shot",ja="デコイショット",de="Täuschungsschuss",fr="Tir leurre"},
    [53] = {id=53,en="Hamanoha",ja="破魔の刃",de="Hamanoha",fr="Nex. démoniaque"},
    [54] = {id=54,en="Hagakure",ja="葉隠",de="Hagakure",fr="Hagakure"},
    [57] = {id=57,en="Issekigan",ja="一隻眼",de="Issekigan",fr="Issekigan"},
    [58] = {id=58,en="Dragon Breaker",ja="ドラゴンブレイカー",de="Drachenbrecher",fr="Nexus draconique"},
    [59] = {id=59,en="Pflug",ja="フルーグ",de="Pflug",fr="Pflug"},
    [61] = {id=61,en="Despoil",ja="ぶんどる",de="Fleddern",fr="Pillage"},
    [62] = {id=62,en="Flee",ja="とんずら",de="Reißaus",fr="Fuite"},
    [63] = {id=63,en="Hide",ja="かくれる",de="Verstecken",fr="Dissimulation"},
    [64] = {id=64,en="Sneak Attack",ja="不意打ち",de="Schleichattacke",fr="Attaque furtive"},
    [65] = {id=65,en="Mug",ja="かすめとる",de="Ausrauben",fr="Rapine"},
    [66] = {id=66,en="Trick Attack",ja="だまし討ち",de="Trickattacke",fr="Attq. sournoise"},
    [67] = {id=67,en="Assassin's Charge",ja="アサシンチャージ",de="Attentäterwut",fr="Charge assassine"},
    [68] = {id=68,en="Feint",ja="フェイント",de="Finte",fr="Feinte"},
    [69] = {id=69,en="Accomp./Collab.",ja="アカンプリス/コラボレーター",de="Accomplice/Kollaborateur",fr="Complice/Acolyte"},
    [70] = {id=70,en="Steady Wing",ja="ステディウィング",de="Ruhige Schwinge",fr="Aile ferme"},
    [71] = {id=71,en="Mana Cede",ja="マナシード",de="Astral-Symbiose",fr="Transfert de Mana"},
    [72] = {id=72,en="Embolden",ja="エンボルド",de="Ermutigung",fr="Affermissement"},
    [73] = {id=73,en="Shield Bash",ja="シールドバッシュ",de="Schildschlag",fr="Coup du bouclier"},
    [74] = {id=74,en="Holy Circle",ja="ホーリーサークル",de="Heiliger Kreis",fr="Cercle sacré"},
    [75] = {id=75,en="Sentinel",ja="センチネル",de="Sentinel",fr="Sentinelle"},
    [76] = {id=76,en="Cover",ja="かばう",de="Deckung",fr="Couverture"},
    [77] = {id=77,en="Rampart",ja="ランパート",de="Schutzwall",fr="Rempart"},
    [78] = {id=78,en="Fealty",ja="フィールティ",de="Lehnseid",fr="Fidélité"},
    [79] = {id=79,en="Chivalry",ja="シバルリー",de="Rittertugend",fr="Chevalerie"},
    [80] = {id=80,en="Divine Emblem",ja="神聖の印",de="Gottesemblem",fr="Emblème divin"},
    [81] = {id=81,en="Unbridled Learning",ja="ノートリアスナレッジ",de="Ungezähm. Wissen",fr="Savoir irréfréné"},
    [84] = {id=84,en="Triple Shot",ja="トリプルショット",de="Dreifachschuss",fr="Triple tir"},
    [85] = {id=85,en="Souleater",ja="暗黒",de="Seelenfresser",fr="Noirceur"},
    [86] = {id=86,en="Arcane Circle",ja="アルケインサークル",de="Arcana-Kreis",fr="Cercle ésoté."},
    [87] = {id=87,en="Last Resort",ja="ラストリゾート",de="Letzter Ausweg",fr="Dernier recours"},
    [88] = {id=88,en="Weapon Bash",ja="ウェポンバッシュ",de="Waffenschlag",fr="Frappe paralys."},
    [89] = {id=89,en="Dark Seal",ja="ダークシール",de="Dunkles Siegel",fr="Sceau ténébreux"},
    [90] = {id=90,en="Diabolic Eye",ja="ディアボリクアイ",de="Diabolisches Auge",fr="Œil diabolique"},
    [91] = {id=91,en="Nether Void",ja="ネザーヴォイド",de="Niederes Nichts",fr="Vacuité limbes"},
    [92] = {id=92,en="Rune Enchantment",ja="エンチャントルーン",de="Verzauber.-Rune",fr="Runes enchant."},
    [97] = {id=97,en="Charm",ja="あやつる",de="Zauberformel",fr="Charme"},
    [98] = {id=98,en="Gauge",ja="みやぶる",de="Abschätzen",fr="Evaluation"},
    [99] = {id=99,en="Tame",ja="なだめる",de="Zähmen",fr="Amadouer"},
    [100] = {id=100,en="Fight",ja="たたかえ",de="Kämpfen",fr="Attaque !"},
    [101] = {id=101,en="Stay/Heel/Leave",ja="まってろ/もどれ/かえれ",de="Verharren/Bei Fuß/Freilassen",fr="Assis !/Au pied !/Va-t'en !"},
    [102] = {id=102,en="Sic/Ready",ja="ほんきだせ/しじをさせろ",de="Spezial/Sturm und Drang",fr="Vas-y !/Obéis !"},
    [103] = {id=103,en="Reward",ja="いたわる",de="Belohnung",fr="Récompense"},
    [104] = {id=104,en="Call Beast",ja="よびだす",de="Bestie rufen",fr="Appel familier"},
    [105] = {id=105,en="Feral Howl",ja="フェラルハウル",de="Wildes Heulen",fr="Hurlement sauv."},
    [106] = {id=106,en="Killer Instinct",ja="K.インスティンクト",de="Killer-Instinkt",fr="Instinct de tueur"},
    [107] = {id=107,en="Snarl",ja="ひきつけろ",de="Fass!",fr="Grogne !"},
    [109] = {id=109,en="Nightingale",ja="ナイチンゲール",de="Nachtigall",fr="Rossignol"},
    [110] = {id=110,en="Troubadour",ja="トルバドゥール",de="Troubadour",fr="Troubadour"},
    [112] = {id=112,en="Pianissimo",ja="ピアニッシモ",de="Pianissimo",fr="Pianissimo"},
    [113] = {id=113,en="Valiance",ja="ヴァリエンス",de="Kühnheit",fr="Valeur"},
    [114] = {id=114,en="Cooldown",ja="クールダウン",de="Cooldown",fr="Soulagement"},
    [115] = {id=115,en="Deus Ex Automata",ja="応急処置",de="Deus Ex Automata",fr="Mesure d'urgence"},
    [116] = {id=116,en="Gambit",ja="ガンビット",de="Gambit",fr="Gambit"},
    [117] = {id=117,en="Liement",ja="リエモン",de="Liemont",fr="Liement"},
    [118] = {id=118,en="One for All",ja="ワンフォアオール",de="Einer für alle",fr="Un pour tous"},
    [119] = {id=119,en="Rayke",ja="レイク",de="Rayke",fr="Rayke"},
    [120] = {id=120,en="Battuta",ja="バットゥタ",de="Battuta",fr="Battuta"},
    [121] = {id=121,en="Scavenge",ja="スカベンジ",de="Plündern",fr="Fouille"},
    [122] = {id=122,en="Shadowbind",ja="影縫い",de="Schattenfessel",fr="Entrave d'ombre"},
    [123] = {id=123,en="Camouflage",ja="カモフラージュ",de="Tarnung",fr="Camouflage"},
    [124] = {id=124,en="Sharpshot",ja="狙い撃ち",de="Fangschuss",fr="Visée"},
    [125] = {id=125,en="Barrage",ja="乱れ撃ち",de="Trommelfeuer",fr="Tir en rafale"},
    [126] = {id=126,en="Unlimited/Double Shot",ja="エンドレスショット/ダブルショット",de="Dauerschuss/Doppelschuss",fr="Tirs illimités/Double tir"},
    [127] = {id=127,en="Stealth Shot",ja="ステルスショット",de="Tarnschuss",fr="Tir furtif"},
    [128] = {id=128,en="Flashy Shot",ja="フラッシーショット",de="Grellschuss",fr="Tir flagrant"},
    [129] = {id=129,en="Velocity Shot",ja="ベロシティショット",de="Schnell-Lader",fr="Tir véloce"},
    [130] = {id=130,en="Widened Compass",ja="ワイデンコンパス",de="Superkompass",fr="Compas élargi"},
    [131] = {id=131,en="Odyllic Subterfuge",ja="オディリックサブタ",de="Ode an Od",fr="Subterfuge odiq."},
    [132] = {id=132,en="Konzen-ittai",ja="渾然一体",de="Konzen Ittai",fr="Konzen-ittai"},
    [133] = {id=133,en="Third Eye",ja="心眼",de="3. Auge",fr="Troisième œil"},
    [134] = {id=134,en="Meditate",ja="黙想",de="Meditieren",fr="Méditation"},
    [135] = {id=135,en="Warding Circle",ja="護摩の守護円",de="Gewahrsamskreis",fr="Cercle protecteur"},
    [136] = {id=136,en="Shikikoyo",ja="士気昂揚",de="Shikikoyo",fr="Shikikoyo"},
    [137] = {id=137,en="Blade Bash",ja="峰打ち",de="Mineuchi",fr="Revers de lame"},
    [138] = {id=138,en="Hasso",ja="八双",de="Hasso",fr="Hasso"},
    [139] = {id=139,en="Seigan",ja="星眼",de="Seigan",fr="Seigan"},
    [140] = {id=140,en="Sekkanoki",ja="石火之機",de="Sekkanoki",fr="Sekkanoki"},
    [141] = {id=141,en="Sengikori",ja="先義後利",de="Sengikori",fr="Sengikori"},
    [142] = {id=142,en="Ward",ja="ワード",de="Wehr",fr="Gardes runiques"},
    [143] = {id=143,en="Effusion",ja="エフューズ",de="Effusion",fr="Assauts runiques"},
    [145] = {id=145,en="Sange",ja="散華",de="Sange",fr="Sange"},
    [146] = {id=146,en="Yonin",ja="陽忍",de="Sonnenkunst",fr="Yonin"},
    [147] = {id=147,en="Innin",ja="陰忍",de="Schattenkunst",fr="Innin"},
    [148] = {id=148,en="Futae",ja="二重",de="Futae",fr="Futae"},
    [157] = {id=157,en="Ancient Circle",ja="エンシェントサークル",de="Urkreis",fr="Cercle ancien"},
    [158] = {id=158,en="Jump/Spirit Jump",ja="ジャンプ/スピリットジャンプ",de="Sprung/Seelensprung",fr="Saut/Saut d'esprit"},
    [159] = {id=159,en="High/Soul Jump",ja="ハイジャンプ/ソウルジャンプ",de="Hochsprung/Psycho-Sprung",fr="Saut aérien/Saut de l'âme"},
    [160] = {id=160,en="Super Jump",ja="スーパージャンプ",de="Supersprung",fr="Super saut"},
    [161] = {id=161,en="Dismiss",ja="送還",de="Wegschicken",fr="Renvoi"},
    [162] = {id=162,en="Spirit Link",ja="スピリットリンク",de="Seelenlink",fr="Lien spirituel"},
    [163] = {id=163,en="Call Wyvern",ja="コールワイバーン",de="Wyvern rufen",fr="Appel wyvern"},
    [164] = {id=164,en="Deep Breathing",ja="ディープブリージング",de="Tiefer Atem",fr="Souffle profond"},
    [165] = {id=165,en="Angon",ja="アンゴン",de="Angon",fr="Angon"},
    [170] = {id=170,en="Assault",ja="神獣の攻撃",de="Angriff",fr="Charge"},
    [171] = {id=171,en="Retreat",ja="神獣の退避",de="Rückzug",fr="Rappel"},
    [172] = {id=172,en="Release",ja="神獣の帰還",de="Freigabe",fr="Libérer"},
    [173] = {id=173,en="Blood Pact: Rage",ja="契約の履行:幻術",de="Blutsbund: Zorn",fr="Pacte sang : rage"},
    [174] = {id=174,en="Blood Pact: Ward",ja="契約の履行:験術",de="Blutsbund: Hilfe",fr="Pacte sang : abri"},
    [175] = {id=175,en="Elemental Siphon",ja="エレメントサイフォン",de="Elemental-Syphon",fr="Siphon élémental"},
    [176] = {id=176,en="Avatar's Favor",ja="神獣の加護",de="Avatar-Empathie",fr="Egide"},
    [181] = {id=181,en="Chain Affinity",ja="ブルーチェーン",de="Blaue Kette",fr="Lien de chaînes"},
    [182] = {id=182,en="Burst Affinity",ja="ブルーバースト",de="Blauer Ausbruch",fr="Lien d'explosions"},
    [183] = {id=183,en="Convergence",ja="コンバージェンス",de="Konvergenz",fr="Convergence"},
    [184] = {id=184,en="Diffusion",ja="ディフュージョン",de="Diffusion",fr="Diffusion"},
    [185] = {id=185,en="Efflux",ja="エフラックス",de="Efflux",fr="Effusion"},
    [193] = {id=193,en="Phantom Roll",ja="ファントムロール",de="Phantom-Wurf",fr="Jet fantôme"},
    [194] = {id=194,en="Double-Up",ja="ダブルアップ",de="Doppelter Einsatz",fr="Surenchère"},
    [195] = {id=195,en="Quick Draw",ja="クイックドロー",de="Schnellschuss",fr="Tirage vif"},
    [197] = {id=197,en="Snake Eye",ja="スネークアイ",de="Schlangenauge",fr="As"},
    [198] = {id=198,en="Fold",ja="フォールド",de="Passen",fr="Défausse"},
    [199] = {id=199,en="Quick Draw",ja="クイックドロー",de="Schnellschuss",fr="Tirage vif"},
    [205] = {id=205,en="Activate",ja="アクティベート",de="Aktivieren",fr="Activation"},
    [206] = {id=206,en="Repair",ja="リペアー",de="Reparieren",fr="Réparation"},
    [207] = {id=207,en="Deploy",ja="ディプロイ",de="Ausfahren",fr="Déploiement"},
    [208] = {id=208,en="Deactivate",ja="ディアクティベート",de="Deaktivieren",fr="Désactivation"},
    [209] = {id=209,en="Retrieve",ja="リトリーブ",de="Zurückziehen",fr="Repli"},
    [210] = {id=210,en="Maneuvers",ja="マニューバ",de="Manöver",fr="Manœuvres"},
    [211] = {id=211,en="Role Reversal",ja="黒衣チェンジ",de="Rollentausch",fr="Mime"},
    [212] = {id=212,en="Ventriloquy",ja="腹話術",de="Bauchredner",fr="Ventriloquie"},
    [213] = {id=213,en="Tactical Switch",ja="タクティクスウィッチ",de="Taktischer Tausch",fr="Changement strat."},
    [214] = {id=214,en="Maintenance",ja="フラッシング",de="Ölwechsel",fr="Vidange"},
    [215] = {id=215,en="Healing Waltz",ja="ヒーリングワルツ",de="Kur-Walzer",fr="Valse curative"},
    [216] = {id=216,en="Sambas",ja="サンバモード",de="Samba-Rhythmen",fr="Sambas"},
    [217] = {id=217,en="Curing Waltz",ja="ケアルワルツ",de="Heilender Walzer",fr="Valse Soin"},
    [218] = {id=218,en="Jigs",ja="ジグモード",de="Tango-Rhythmen",fr="Gigues"},
    [219] = {id=219,en="Saber Dance",ja="剣の舞い",de="Klingentanz",fr="Danse du sabre"},
    [220] = {id=220,en="Steps",ja="ステップ",de="Tanzschritte",fr="Pas"},
    [221] = {id=221,en="Flourishes I",ja="フラリッシュI",de="Polka-Rhythmen",fr="Pirouettes I"},
    [222] = {id=222,en="Flourishes II",ja="フラリッシュII",de="Polka-R. II",fr="Pirouettes II"},
    [223] = {id=223,en="No Foot Rise",ja="ノーフットライズ",de="Aplomb",fr="Pas posé"},
    [224] = {id=224,en="Fan Dance",ja="扇の舞い",de="Fächertanz",fr="D. de l'éventail"},
    [225] = {id=225,en="Divine Waltz",ja="ディバインワルツ",de="Walzer der Göttin",fr="Valse divine"},
    [226] = {id=226,en="Flourishes III",ja="フラリッシュIII",de="Polka-Rhythm. III",fr="Pirouettes III"},
    [227] = {id=227,en="Waltzes",ja="ワルツモード",de="Walzer-Rhythmen",fr="Valses"},
    [228] = {id=228,en="Light Arts",ja="白のグリモア",de="Weißes Grimoire",fr="Grimoire blanc"},
    [230] = {id=230,en="Modus Veritas",ja="以逸待労の計",de="Vae victis",fr="Modus veritas"},
    [231] = {id=231,en="Stratagems",ja="戦術魔道書",de="Schultz' Kriegsl.",fr="Stratagèmes"},
    [232] = {id=232,en="Dark Arts",ja="黒のグリモア",de="Schwarz. Grimoire",fr="Grimoire noir"},
    [233] = {id=233,en="Stratagems",ja="戦術魔道書",de="Schultz' Kriegsl.",fr="Stratagèmes"},
    [234] = {id=234,en="Sublimation",ja="机上演習",de="Sublimierung",fr="Révisions"},
    [235] = {id=235,en="Enlightenment",ja="大悟徹底",de="Licentia poetica",fr="Apaisement"},
    [236] = {id=236,en="Presto",ja="プレスト",de="Degagé",fr="Presto"},
    [237] = {id=237,en="Libra",ja="ライブラ",de="Libra",fr="Acuité"},
    [238] = {id=238,en="Smiting Breath",ja="スマイトブレス",de="Rächer-Atem",fr="Souffle menaçant"},
    [239] = {id=239,en="Restoring Breath",ja="レストアブレス",de="Empathie-Atem",fr="Souffle apaisant"},
    [240] = {id=240,en="Bully",ja="まどわす",de="Drangsalieren",fr="Frousse"},
    [241] = {id=241,en="Swipe",ja="スワイプ",de="Hechthieb",fr="Volée runique"},
    [242] = {id=242,en="Vivacious Pulse",ja="ビベイシャス",de="Pulsschlag",fr="Pouls vif"},
    [243] = {id=243,en="Full Circle",ja="フルサークル",de="Ganzer Kreis",fr="Cercle complet"},
    [244] = {id=244,en="Ecliptic Attrition",ja="サークルエンリッチ",de="Vollkomm. Kreis",fr="Renforc. sphér."},
    [245] = {id=245,en="Collimated Fervor",ja="コリメイトファーバー",de="Kollimat. Rausch",fr="Ferveur collimat."},
    [246] = {id=246,en="Life Cycle",ja="ライフサイクル",de="Kreis des Lebens",fr="Cycle de vie"},
    [247] = {id=247,en="Blaze of Glory",ja="グローリーブレイズ",de="Glanz und Gloria",fr="Emport. géomant."},
    [248] = {id=248,en="Dematerialize",ja="デマテリアライズ",de="Dematerialisation",fr="Dématérialisation"},
    [249] = {id=249,en="Theurgic Focus",ja="タウマテルギフォカス",de="Thaumat. Fokus",fr="Focalis. thaum."},
    [250] = {id=250,en="Concentric Pulse",ja="コンセントリクパルス",de="Konzentr. Puls",fr="Exp. concentrique"},
    [251] = {id=251,en="Mending Halation",ja="メンドハレイション",de="Heilsamer Lichthof",fr="Halo salvateur"},
    [252] = {id=252,en="Radial Arcana",ja="レイディアルアルカナ",de="Radiales Arkanum",fr="Arcane radiante"},
    [253] = {id=253,en="Relinquish",ja="リリンク",de="Remorph",fr="Disjonction"},
    [254] = {id=254,en="SP Ability II",ja="SPアビリティII",de="SP Fähigkeit II",fr="SP aptitude II"},
    [255] = {id=255,en="Ready",ja="しじをさせろ",de="Sturm und Drang",fr="Obéis !"},
}, {"id", "en", "ja", "de", "fr"}

--[[
Copyright © 2013-2014, Windower
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Windower nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Windower BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
