-- Automatically generated file: Ability Recasts

return {
    [0] = {id=0,en="SP Ability",ja="SPアビリティ"},
    [1] = {id=1,en="Berserk",ja="バーサク"},
    [2] = {id=2,en="Warcry",ja="ウォークライ"},
    [3] = {id=3,en="Defender",ja="ディフェンダー"},
    [4] = {id=4,en="Aggressor",ja="アグレッサー"},
    [5] = {id=5,en="Provoke",ja="挑発"},
    [6] = {id=6,en="Warrior's Charge",ja="ウォリアーチャージ"},
    [7] = {id=7,en="Tomahawk",ja="トマホーク"},
    [8] = {id=8,en="Retaliation",ja="リタリエーション"},
    [9] = {id=9,en="Restraint",ja="リストレント"},
    [10] = {id=10,en="Rune Enchantment",ja="エンチャントルーン"},
    [11] = {id=11,en="Blood Rage",ja="ブラッドレイジ"},
    [13] = {id=13,en="Focus",ja="集中"},
    [14] = {id=14,en="Dodge",ja="回避"},
    [15] = {id=15,en="Chakra",ja="チャクラ"},
    [16] = {id=16,en="Boost",ja="ためる"},
    [17] = {id=17,en="Counterstance",ja="かまえる"},
    [18] = {id=18,en="Chi Blast",ja="気孔弾"},
    [19] = {id=19,en="Mantra",ja="マントラ"},
    [20] = {id=20,en="Formless Strikes",ja="無想無念"},
    [21] = {id=21,en="Footwork",ja="猫足立ち"},
    [22] = {id=22,en="Perfect Counter",ja="絶対カウンター"},
    [23] = {id=23,en="Vallation",ja="ヴァレション"},
    [24] = {id=24,en="Swordplay",ja="ソードプレイ"},
    [25] = {id=25,en="Lunge",ja="ランジ"},
    [26] = {id=26,en="Divine Seal",ja="女神の印"},
    [27] = {id=27,en="Martyr",ja="マーター"},
    [28] = {id=28,en="Devotion",ja="デヴォーション"},
    [29] = {id=29,en="Afflatus Solace",ja="ハートオブソラス"},
    [30] = {id=30,en="Afflatus Misery",ja="ハートオブミゼリ"},
    [31] = {id=31,en="Impetus",ja="インピタス"},
    [32] = {id=32,en="Divine Caress",ja="女神の愛撫"},
    [33] = {id=33,en="Sacrosanctity",ja="女神の聖域"},
    [34] = {id=34,en="Enmity Douse",ja="エンミティダウス"},
    [35] = {id=35,en="Manawell",ja="魔力の雫"},
    [36] = {id=36,en="Saboteur",ja="サボトゥール"},
    [37] = {id=37,en="Spontaneity",ja="クイックマジック"},
    [38] = {id=38,en="Elemental Seal",ja="精霊の印"},
    [39] = {id=39,en="Mana Wall",ja="マナウォール"},
    [40] = {id=40,en="Conspirator",ja="コンスピレーター"},
    [41] = {id=41,en="Sepulcher",ja="セプルカー"},
    [42] = {id=42,en="Palisade",ja="パリセード"},
    [43] = {id=43,en="Arcane Crest",ja="アルケインクレスト"},
    [44] = {id=44,en="Scarlet Delirium",ja="レッドデリリアム"},
    [45] = {id=45,en="Spur",ja="きばれ"},
    [46] = {id=46,en="Run Wild",ja="ふりしぼれ"},
    [47] = {id=47,en="Tenuto",ja="テヌート"},
    [48] = {id=48,en="Marcato",ja="マルカート"},
    [49] = {id=49,en="Convert",ja="コンバート"},
    [50] = {id=50,en="Composure",ja="コンポージャー"},
    [51] = {id=51,en="Bounty Shot",ja="バウンティショット"},
    [52] = {id=52,en="Decoy Shot",ja="デコイショット"},
    [53] = {id=53,en="Hamanoha",ja="破魔の刃"},
    [54] = {id=54,en="Hagakure",ja="葉隠"},
    [57] = {id=57,en="Issekigan",ja="一隻眼"},
    [58] = {id=58,en="Dragon Breaker",ja="ドラゴンブレイカー"},
    [59] = {id=59,en="Pflug",ja="フルーグ"},
    [61] = {id=61,en="Despoil",ja="ぶんどる"},
    [62] = {id=62,en="Flee",ja="とんずら"},
    [63] = {id=63,en="Hide",ja="かくれる"},
    [64] = {id=64,en="Sneak Attack",ja="不意打ち"},
    [65] = {id=65,en="Mug",ja="かすめとる"},
    [66] = {id=66,en="Trick Attack",ja="だまし討ち"},
    [67] = {id=67,en="Assassin's Charge",ja="アサシンチャージ"},
    [68] = {id=68,en="Feint",ja="フェイント"},
    [69] = {id=69,en="Accomp./Collab.",ja="アカンプリス/コラボレーター"},
    [70] = {id=70,en="Steady Wing",ja="ステディウィング"},
    [71] = {id=71,en="Mana Cede",ja="マナシード"},
    [72] = {id=72,en="Embolden",ja="エンボルド"},
    [73] = {id=73,en="Shield Bash",ja="シールドバッシュ"},
    [74] = {id=74,en="Holy Circle",ja="ホーリーサークル"},
    [75] = {id=75,en="Sentinel",ja="センチネル"},
    [76] = {id=76,en="Cover",ja="かばう"},
    [77] = {id=77,en="Rampart",ja="ランパート"},
    [78] = {id=78,en="Fealty",ja="フィールティ"},
    [79] = {id=79,en="Chivalry",ja="シバルリー"},
    [80] = {id=80,en="Divine Emblem",ja="神聖の印"},
    [81] = {id=81,en="Unbridled Learning",ja="ノートリアスナレッジ"},
    [84] = {id=84,en="Triple Shot",ja="トリプルショット"},
    [85] = {id=85,en="Souleater",ja="暗黒"},
    [86] = {id=86,en="Arcane Circle",ja="アルケインサークル"},
    [87] = {id=87,en="Last Resort",ja="ラストリゾート"},
    [88] = {id=88,en="Weapon Bash",ja="ウェポンバッシュ"},
    [89] = {id=89,en="Dark Seal",ja="ダークシール"},
    [90] = {id=90,en="Diabolic Eye",ja="ディアボリクアイ"},
    [91] = {id=91,en="Nether Void",ja="ネザーヴォイド"},
    [92] = {id=92,en="Rune Enchantment",ja="エンチャントルーン"},
    [97] = {id=97,en="Charm",ja="あやつる"},
    [98] = {id=98,en="Gauge",ja="みやぶる"},
    [99] = {id=99,en="Tame",ja="なだめる"},
    [100] = {id=100,en="Fight",ja="たたかえ"},
    [101] = {id=101,en="Stay/Heel/Leave",ja="まってろ/もどれ/かえれ"},
    [102] = {id=102,en="Sic/Ready",ja="ほんきだせ/しじをさせろ"},
    [103] = {id=103,en="Reward",ja="いたわる"},
    [104] = {id=104,en="Call Beast",ja="よびだす"},
    [105] = {id=105,en="Feral Howl",ja="フェラルハウル"},
    [106] = {id=106,en="Killer Instinct",ja="K.インスティンクト"},
    [107] = {id=107,en="Snarl",ja="ひきつけろ"},
    [109] = {id=109,en="Nightingale",ja="ナイチンゲール"},
    [110] = {id=110,en="Troubadour",ja="トルバドゥール"},
    [112] = {id=112,en="Pianissimo",ja="ピアニッシモ"},
    [113] = {id=113,en="Valiance",ja="ヴァリエンス"},
    [114] = {id=114,en="Cooldown",ja="クールダウン"},
    [115] = {id=115,en="Deus Ex Automata",ja="応急処置"},
    [116] = {id=116,en="Gambit",ja="ガンビット"},
    [117] = {id=117,en="Liement",ja="リエモン"},
    [118] = {id=118,en="One for All",ja="ワンフォアオール"},
    [119] = {id=119,en="Rayke",ja="レイク"},
    [120] = {id=120,en="Battuta",ja="バットゥタ"},
    [121] = {id=121,en="Scavenge",ja="スカベンジ"},
    [122] = {id=122,en="Shadowbind",ja="影縫い"},
    [123] = {id=123,en="Camouflage",ja="カモフラージュ"},
    [124] = {id=124,en="Sharpshot",ja="狙い撃ち"},
    [125] = {id=125,en="Barrage",ja="乱れ撃ち"},
    [126] = {id=126,en="Unlimited/Double Shot",ja="エンドレスショット/ダブルショット"},
    [127] = {id=127,en="Stealth Shot",ja="ステルスショット"},
    [128] = {id=128,en="Flashy Shot",ja="フラッシーショット"},
    [129] = {id=129,en="Velocity Shot",ja="ベロシティショット"},
    [130] = {id=130,en="Widened Compass",ja="ワイデンコンパス"},
    [131] = {id=131,en="Odyllic Subterfuge",ja="オディリックサブタ"},
    [132] = {id=132,en="Konzen-ittai",ja="渾然一体"},
    [133] = {id=133,en="Third Eye",ja="心眼"},
    [134] = {id=134,en="Meditate",ja="黙想"},
    [135] = {id=135,en="Warding Circle",ja="護摩の守護円"},
    [136] = {id=136,en="Shikikoyo",ja="士気昂揚"},
    [137] = {id=137,en="Blade Bash",ja="峰打ち"},
    [138] = {id=138,en="Hasso",ja="八双"},
    [139] = {id=139,en="Seigan",ja="星眼"},
    [140] = {id=140,en="Sekkanoki",ja="石火之機"},
    [141] = {id=141,en="Sengikori",ja="先義後利"},
    [142] = {id=142,en="Ward",ja="ワード"},
    [143] = {id=143,en="Effusion",ja="エフューズ"},
    [145] = {id=145,en="Sange",ja="散華"},
    [146] = {id=146,en="Yonin",ja="陽忍"},
    [147] = {id=147,en="Innin",ja="陰忍"},
    [148] = {id=148,en="Futae",ja="二重"},
    [157] = {id=157,en="Ancient Circle",ja="エンシェントサークル"},
    [158] = {id=158,en="Jump/Spirit Jump",ja="ジャンプ/スピリットジャンプ"},
    [159] = {id=159,en="High/Soul Jump",ja="ハイジャンプ/ソウルジャンプ"},
    [160] = {id=160,en="Super Jump",ja="スーパージャンプ"},
    [161] = {id=161,en="Dismiss",ja="送還"},
    [162] = {id=162,en="Spirit Link",ja="スピリットリンク"},
    [163] = {id=163,en="Call Wyvern",ja="コールワイバーン"},
    [164] = {id=164,en="Deep Breathing",ja="ディープブリージング"},
    [165] = {id=165,en="Angon",ja="アンゴン"},
    [170] = {id=170,en="Assault",ja="神獣の攻撃"},
    [171] = {id=171,en="Retreat",ja="神獣の退避"},
    [172] = {id=172,en="Release",ja="神獣の帰還"},
    [173] = {id=173,en="Blood Pact: Rage",ja="契約の履行:幻術"},
    [174] = {id=174,en="Blood Pact: Ward",ja="契約の履行:験術"},
    [175] = {id=175,en="Elemental Siphon",ja="エレメントサイフォン"},
    [176] = {id=176,en="Avatar's Favor",ja="神獣の加護"},
    [181] = {id=181,en="Chain Affinity",ja="ブルーチェーン"},
    [182] = {id=182,en="Burst Affinity",ja="ブルーバースト"},
    [183] = {id=183,en="Convergence",ja="コンバージェンス"},
    [184] = {id=184,en="Diffusion",ja="ディフュージョン"},
    [185] = {id=185,en="Efflux",ja="エフラックス"},
    [193] = {id=193,en="Phantom Roll",ja="ファントムロール"},
    [194] = {id=194,en="Double-Up",ja="ダブルアップ"},
    [195] = {id=195,en="Quick Draw",ja="クイックドロー"},
    [197] = {id=197,en="Snake Eye",ja="スネークアイ"},
    [198] = {id=198,en="Fold",ja="フォールド"},
    [199] = {id=199,en="Quick Draw",ja="クイックドロー"},
    [205] = {id=205,en="Activate",ja="アクティベート"},
    [206] = {id=206,en="Repair",ja="リペアー"},
    [207] = {id=207,en="Deploy",ja="ディプロイ"},
    [208] = {id=208,en="Deactivate",ja="ディアクティベート"},
    [209] = {id=209,en="Retrieve",ja="リトリーブ"},
    [210] = {id=210,en="Maneuvers",ja="マニューバ"},
    [211] = {id=211,en="Role Reversal",ja="黒衣チェンジ"},
    [212] = {id=212,en="Ventriloquy",ja="腹話術"},
    [213] = {id=213,en="Tactical Switch",ja="タクティクスウィッチ"},
    [214] = {id=214,en="Maintenance",ja="フラッシング"},
    [215] = {id=215,en="Healing Waltz",ja="ヒーリングワルツ"},
    [216] = {id=216,en="Sambas",ja="サンバモード"},
    [217] = {id=217,en="Curing Waltz",ja="ケアルワルツ"},
    [218] = {id=218,en="Jigs",ja="ジグモード"},
    [219] = {id=219,en="Saber Dance",ja="剣の舞い"},
    [220] = {id=220,en="Steps",ja="ステップ"},
    [221] = {id=221,en="Flourishes I",ja="フラリッシュI"},
    [222] = {id=222,en="Flourishes II",ja="フラリッシュII"},
    [223] = {id=223,en="No Foot Rise",ja="ノーフットライズ"},
    [224] = {id=224,en="Fan Dance",ja="扇の舞い"},
    [225] = {id=225,en="Divine Waltz",ja="ディバインワルツ"},
    [226] = {id=226,en="Flourishes III",ja="フラリッシュIII"},
    [227] = {id=227,en="Waltzes",ja="ワルツモード"},
    [228] = {id=228,en="Light Arts",ja="白のグリモア"},
    [230] = {id=230,en="Modus Veritas",ja="以逸待労の計"},
    [231] = {id=231,en="Stratagems",ja="戦術魔道書"},
    [232] = {id=232,en="Dark Arts",ja="黒のグリモア"},
    [233] = {id=233,en="Stratagems",ja="戦術魔道書"},
    [234] = {id=234,en="Sublimation",ja="机上演習"},
    [235] = {id=235,en="Enlightenment",ja="大悟徹底"},
    [236] = {id=236,en="Presto",ja="プレスト"},
    [237] = {id=237,en="Libra",ja="ライブラ"},
    [238] = {id=238,en="Smiting Breath",ja="スマイトブレス"},
    [239] = {id=239,en="Restoring Breath",ja="レストアブレス"},
    [240] = {id=240,en="Bully",ja="まどわす"},
    [241] = {id=241,en="Swipe",ja="スワイプ"},
    [242] = {id=242,en="Vivacious Pulse",ja="ビベイシャス"},
    [243] = {id=243,en="Full Circle",ja="フルサークル"},
    [244] = {id=244,en="Ecliptic Attrition",ja="サークルエンリッチ"},
    [245] = {id=245,en="Collimated Fervor",ja="コリメイトファーバー"},
    [246] = {id=246,en="Life Cycle",ja="ライフサイクル"},
    [247] = {id=247,en="Blaze of Glory",ja="グローリーブレイズ"},
    [248] = {id=248,en="Dematerialize",ja="デマテリアライズ"},
    [249] = {id=249,en="Theurgic Focus",ja="タウマテルギフォカス"},
    [250] = {id=250,en="Concentric Pulse",ja="コンセントリクパルス"},
    [251] = {id=251,en="Mending Halation",ja="メンドハレイション"},
    [252] = {id=252,en="Radial Arcana",ja="レイディアルアルカナ"},
    [253] = {id=253,en="Relinquish",ja="リリンク"},
    [254] = {id=254,en="SP Ability II",ja="SPアビリティII"},
    [255] = {id=255,en="Ready",ja="しじをさせろ"},
}, {"id", "en", "ja"}

--[[
Copyright © 2013-2014, Windower
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Windower nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Windower BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
