-- Automatically generated file: Job Traits

return {
    [1] = {id=1,en="Accuracy Bonus",ja="物理命中率アップ",de="Präzisions-Bonus",fr="Bonus précision",element=4,icon_id=44,range=0,targets=0},
    [2] = {id=2,en="Evasion Bonus",ja="物理回避率アップ",de="Ausweich-Bonus",fr="Bonus esquive",element=2,icon_id=42,range=0,targets=0},
    [3] = {id=3,en="Attack Bonus",ja="物理攻撃力アップ",de="Attacken-Bonus",fr="Bonus attaque",element=0,icon_id=40,range=0,targets=0},
    [4] = {id=4,en="Defense Bonus",ja="物理防御力アップ",de="Verteidig.-Bonus",fr="Bonus défense",element=3,icon_id=43,range=0,targets=0},
    [5] = {id=5,en="Magic Atk. Bonus",ja="魔法攻撃力アップ",de="Magieatt.-Bonus",fr="Bonus attq. mag.",element=6,icon_id=46,range=0,targets=0},
    [6] = {id=6,en="Magic Def. Bonus",ja="魔法防御力アップ",de="Magievert.-Bonus",fr="Bonus déf. mag.",element=6,icon_id=46,range=0,targets=0},
    [7] = {id=7,en="Max HP Boost",ja="HPmaxアップ",de="Max. HP-Boost",fr="HP max. augm.",element=6,icon_id=46,range=0,targets=0},
    [8] = {id=8,en="Max MP Boost",ja="MPmaxアップ",de="Max. MP-Boost",fr="MP max. augm.",element=6,icon_id=46,range=0,targets=0},
    [9] = {id=9,en="Auto Regen",ja="オートリジェネ",de="Auto-Regen.",fr="Auto-récup",element=6,icon_id=46,range=0,targets=0},
    [10] = {id=10,en="Auto Refresh",ja="オートリフレシュ",de="Auto-Erfrischen",fr="Auto-recharge",element=6,icon_id=46,range=0,targets=0},
    [11] = {id=11,en="Rapid Shot",ja="ラピッドショット",de="Rapidschuss",fr="Tir rapide",element=2,icon_id=42,range=0,targets=0},
    [12] = {id=12,en="Fast Cast",ja="ファストキャスト",de="Schnellzauber",fr="Rapido-magie",element=6,icon_id=46,range=0,targets=0},
    [13] = {id=13,en="Conserve MP",ja="コンサーブMP",de="MP einsparen",fr="Economie MP",element=6,icon_id=46,range=0,targets=0},
    [14] = {id=14,en="Store TP",ja="ストアTP",de="TP lagern",fr="Réserve TP",element=6,icon_id=46,range=0,targets=0},
    [15] = {id=15,en="Double Attack",ja="ダブルアタック",de="Doppelattacke",fr="Double attaque",element=6,icon_id=46,range=0,targets=0},
    [16] = {id=16,en="Triple Attack",ja="トリプルアタック",de="Dreifachattacke",fr="Triple attaque",element=6,icon_id=46,range=0,targets=0},
    [17] = {id=17,en="Counter",ja="カウンター",de="Konter",fr="Riposte",element=6,icon_id=46,range=0,targets=0},
    [18] = {id=18,en="Dual Wield",ja="二刀流",de="Doppelwaffe",fr="Deux armes",element=6,icon_id=46,range=0,targets=0},
    [19] = {id=19,en="Treasure Hunter",ja="トレジャーハンター",de="Schatzjäger",fr="Chass. de trésor",element=6,icon_id=46,range=0,targets=0},
    [20] = {id=20,en="Gilfinder",ja="ギルスティール",de="Gilfinder",fr="Gils plus",element=6,icon_id=46,range=0,targets=0},
    [21] = {id=21,en="Alertness",ja="警戒",de="Wachsamkeit",fr="Vigilance",element=6,icon_id=46,range=0,targets=0},
    [22] = {id=22,en="Stealth",ja="ステルス",de="Heimlichkeit",fr="Discrétion",element=6,icon_id=46,range=0,targets=0},
    [23] = {id=23,en="Martial Arts",ja="マーシャルアーツ",de="Kampfkünste",fr="Arts martiaux",element=2,icon_id=42,range=0,targets=0},
    [24] = {id=24,en="Clear Mind",ja="クリアマインド",de="Klarer Kopf",fr="Esprit clair",element=1,icon_id=41,range=0,targets=0},
    [25] = {id=25,en="Shield Mastery",ja="シールドマスタリー",de="Schildmeister",fr="Maîtrise bouclier",element=6,icon_id=46,range=0,targets=0},
    [32] = {id=32,en="Beast Killer",ja="ビーストキラー",de="Bestienkiller",fr="Tueur de bêtes",element=6,icon_id=46,range=0,targets=0},
    [33] = {id=33,en="Plantoid Killer",ja="プラントイドキラー",de="Plantoidenkiller",fr="Tueur de plant.",element=6,icon_id=46,range=0,targets=0},
    [34] = {id=34,en="Vermin Killer",ja="ヴァーミンキラー",de="Ungezieferkiller",fr="Tueur de verm.",element=6,icon_id=46,range=0,targets=0},
    [35] = {id=35,en="Lizard Killer",ja="リザードキラー",de="Echsenkiller",fr="Tueur de lézards",element=6,icon_id=46,range=0,targets=0},
    [36] = {id=36,en="Bird Killer",ja="バードキラー",de="Vogelkiller",fr="Tueur d'oiseaux",element=6,icon_id=46,range=0,targets=0},
    [37] = {id=37,en="Amorph Killer",ja="アモルフキラー",de="Amorphkiller",fr="Tueur d'amorphes",element=6,icon_id=46,range=0,targets=0},
    [38] = {id=38,en="Aquan Killer",ja="アクアンキラー",de="Aquankiller",fr="Tueur d'aquans",element=6,icon_id=46,range=0,targets=0},
    [39] = {id=39,en="Undead Killer",ja="アンデッドキラー",de="Untotenkiller",fr="Tueur mort-vivant",element=6,icon_id=46,range=0,targets=0},
    [41] = {id=41,en="Arcana Killer",ja="アルカナキラー",de="Arcanakiller",fr="Tueur d'arcanas",element=7,icon_id=47,range=0,targets=0},
    [42] = {id=42,en="Demon Killer",ja="デーモンキラー",de="Dämonenkiller",fr="Tueur de démons",element=6,icon_id=46,range=0,targets=0},
    [43] = {id=43,en="Dragon Killer",ja="ドラゴンキラー",de="Drachenkiller",fr="Tueur de dragons",element=7,icon_id=47,range=0,targets=0},
    [48] = {id=48,en="Resist Sleep",ja="レジストスリープ",de="Schlaf widerstehen",fr="Résiste Sommeil",element=6,icon_id=46,range=0,targets=0},
    [49] = {id=49,en="Resist Poison",ja="レジストポイズン",de="Gift widerstehen",fr="Résiste Poison",element=4,icon_id=44,range=0,targets=0},
    [50] = {id=50,en="Resist Paralyze",ja="レジストパライズ",de="Paralyse widerst.",fr="Résiste Paralysie",element=0,icon_id=40,range=0,targets=0},
    [51] = {id=51,en="Resist Blind",ja="レジストブライン",de="Blind widerstehen",fr="Résiste Cécité",element=6,icon_id=46,range=0,targets=0},
    [52] = {id=52,en="Resist Silence",ja="レジストサイレス",de="Schweigen widerst.",fr="Résiste Silence",element=1,icon_id=41,range=0,targets=0},
    [53] = {id=53,en="Resist Petrify",ja="レジストペトリ",de="Stein widerstehen",fr="Résiste Pétrif.",element=2,icon_id=42,range=0,targets=0},
    [54] = {id=54,en="Resist Virus",ja="レジストウィルス",de="Viren widerstehen",fr="Résiste Virus",element=5,icon_id=45,range=0,targets=0},
    [55] = {id=55,en="Resist Curse",ja="レジストカーズ",de="Fluch widerstehen",fr="Résiste Maléfice",element=6,icon_id=46,range=0,targets=0},
    [56] = {id=56,en="Resist Stun",ja="レジストスタン",de="Betäub. widerst.",fr="Résiste Etourdi.",element=0,icon_id=40,range=0,targets=0},
    [57] = {id=57,en="Resist Bind",ja="レジストバインド",de="Fessel widerstehen",fr="Résiste Entrave",element=0,icon_id=40,range=0,targets=0},
    [58] = {id=58,en="Resist Gravity",ja="レジストグラビティ",de="Schwerkr. widerst.",fr="Résiste Pesant.",element=1,icon_id=41,range=0,targets=0},
    [59] = {id=59,en="Resist Slow",ja="レジストスロウ",de="Gemach widerst.",fr="Résiste Lenteur",element=2,icon_id=42,range=0,targets=0},
    [60] = {id=60,en="Resist Charm",ja="レジストチャーム",de="Zauberf. widerst.",fr="Résiste Charme",element=6,icon_id=46,range=0,targets=0},
    [63] = {id=63,en="Resist Amnesia",ja="レジストアムネジア",de="Amnesie widerst.",fr="Résiste Amnésie",element=5,icon_id=45,range=0,targets=0},
    [64] = {id=64,en="Treasure Hunter II",ja="トレジャーハンターII",de="Schatzjäger II",fr="Chass. de trés. II",element=6,icon_id=46,range=0,targets=0},
    [65] = {id=65,en="Treas. Hunter III",ja="トレジャーハンターIII",de="Schatzjäger III",fr="Chass. de trés. III",element=6,icon_id=46,range=0,targets=0},
    [66] = {id=66,en="Kick Attacks",ja="蹴撃",de="Trittattacke",fr="Coups de pied",element=6,icon_id=46,range=0,targets=0},
    [67] = {id=67,en="Subtle Blow",ja="モクシャ",de="Subtilschlag",fr="Coup subtil",element=2,icon_id=42,range=0,targets=0},
    [68] = {id=68,en="Assassin",ja="アサシン",de="Mörder",fr="Assassin",element=2,icon_id=42,range=0,targets=0},
    [69] = {id=69,en="Divine Veil",ja="女神の慈悲",de="Gottesschleier",fr="Voile divin",element=6,icon_id=46,range=0,targets=0},
    [70] = {id=70,en="Zanshin",ja="残心",de="Zanshin",fr="Zanshin",element=6,icon_id=46,range=0,targets=0},
    [71] = {id=71,en="Savagery",ja="サベッジリ",de="Wildheit",fr="Sauvagerie",element=6,icon_id=46,range=0,targets=0},
    [72] = {id=72,en="Aggressive Aim",ja="アグレシブエイム",de="Aggressiv-Treffer",fr="Visée agressive",element=6,icon_id=46,range=0,targets=0},
    [73] = {id=73,en="Invigorate",ja="練気",de="Stärkung",fr="Tonifiant",element=6,icon_id=46,range=0,targets=0},
    [74] = {id=74,en="Penance",ja="発剄",de="Buße",fr="Pénitence",element=6,icon_id=46,range=0,targets=0},
    [75] = {id=75,en="Aura Steal",ja="オーラスティール",de="Aura-Diebstahl",fr="Vol d'aura",element=6,icon_id=46,range=0,targets=0},
    [76] = {id=76,en="Ambush",ja="アンブッシュ",de="Hinterhalt",fr="Embuscade",element=6,icon_id=46,range=0,targets=0},
    [77] = {id=77,en="Iron Will",ja="アイアンウィル",de="Eiserner Wille",fr="Volonté de fer",element=6,icon_id=46,range=0,targets=0},
    [78] = {id=78,en="Guardian",ja="ガーディアン",de="Hüter",fr="Gardien",element=6,icon_id=46,range=0,targets=0},
    [79] = {id=79,en="Muted Soul",ja="ミューテッドソウル",de="Unterdrückte Seele",fr="Ame silencieuse",element=6,icon_id=46,range=0,targets=0},
    [80] = {id=80,en="Desperate Blows",ja="デスペレートブロー",de="Verzweiflungshiebe",fr="Coups désespérés",element=6,icon_id=46,range=0,targets=0},
    [81] = {id=81,en="Beast Affinity",ja="ビーストアフニティ",de="Bestien-Affinität",fr="Ami des bêtes",element=6,icon_id=46,range=0,targets=0},
    [82] = {id=82,en="Beast Healer",ja="ビーストヒーラー",de="Bestienheiler",fr="Vétérinaire",element=6,icon_id=46,range=0,targets=0},
    [83] = {id=83,en="Snapshot",ja="スナップショット",de="Schnappschuss",fr="Tir instantané",element=6,icon_id=46,range=0,targets=0},
    [84] = {id=84,en="Recycle",ja="リサイクル",de="Recycle",fr="Recyclage",element=6,icon_id=46,range=0,targets=0},
    [85] = {id=85,en="Ikishoten",ja="意気衝天",de="Ikishoten",fr="Ikishoten",element=6,icon_id=46,range=0,targets=0},
    [86] = {id=86,en="Overwhelm",ja="正正堂堂",de="Überwältigen",fr="Face-à-face",element=6,icon_id=46,range=0,targets=0},
    [87] = {id=87,en="Ninja Tool Expert.",ja="忍具の知識",de="Ninja-Weisheit",fr="Exp. outils ninja",element=6,icon_id=46,range=0,targets=0},
    [88] = {id=88,en="Empathy",ja="エンパシー",de="Empathie",fr="Empathie",element=6,icon_id=46,range=0,targets=0},
    [89] = {id=89,en="Strafe",ja="ストレイフ",de="Beschuss",fr="Bombardement",element=6,icon_id=46,range=0,targets=0},
    [90] = {id=90,en="Enchainment",ja="エンチェーンメント",de="Verkettung",fr="Enchaînement",element=6,icon_id=46,range=0,targets=0},
    [91] = {id=91,en="Assimilation",ja="アシミレーション",de="Einverleibung",fr="Assimilation",element=6,icon_id=46,range=0,targets=0},
    [92] = {id=92,en="Winning Streak",ja="ウィニングストリーク",de="Glückssträhne",fr="Sans-faute",element=6,icon_id=46,range=0,targets=0},
    [93] = {id=93,en="Loaded Deck",ja="ローデッドデッキ",de="Kartentrick",fr="Dés pipés",element=6,icon_id=46,range=0,targets=0},
    [94] = {id=94,en="Fine-Tuning",ja="微調整",de="Feinabstimmung",fr="Syntonisation",element=6,icon_id=46,range=0,targets=0},
    [95] = {id=95,en="Optimization",ja="最適化",de="Optimierung",fr="Optimisation",element=6,icon_id=46,range=0,targets=0},
    [96] = {id=96,en="Closed Position",ja="Ｃ・ポジション",de="Arabesque",fr="Position fermée",element=6,icon_id=46,range=0,targets=0},
    [97] = {id=97,en="Stormsurge",ja="陣頭指揮",de="Theatrum mundi",fr="Injonction",element=6,icon_id=46,range=0,targets=0},
    [98] = {id=98,en="Crit. Atk. Bonus",ja="C.インクリース",de="Krit. Att.-Bonus",fr="Expertise critique",element=6,icon_id=46,range=0,targets=0},
    [99] = {id=99,en="Crit. Def. Bonus",ja="C.リデュース",de="Krit. Vert.-Bonus",fr="Défense critique",element=6,icon_id=46,range=0,targets=0},
    [100] = {id=100,en="Tactical Parry",ja="タクティカルパリー",de="Takt. Parieren",fr="Parade strat.",element=6,icon_id=46,range=0,targets=0},
    [101] = {id=101,en="Tactical Guard",ja="タクティカルガード",de="Takt. Beschützen",fr="Garde strat.",element=6,icon_id=46,range=0,targets=0},
    [102] = {id=102,en="Shield Def. Bonus",ja="エクストリームガード",de="Schild-Vert.-Bonus",fr="Blocage strat.",element=6,icon_id=46,range=0,targets=0},
    [103] = {id=103,en="Stout Servant",ja="スタウトサーヴァント",de="Standhaft. Knecht",fr="Serviteur loyal",element=6,icon_id=46,range=0,targets=0},
    [104] = {id=104,en="True Shot",ja="トゥルーショット",de="Wahrhaft. Schuss",fr="Tir franc",element=6,icon_id=46,range=0,targets=0},
    [105] = {id=105,en="Blood Boon",ja="ブラッドブーン",de="Blutseligkeit",fr="Grâce du pacte",element=6,icon_id=46,range=0,targets=0},
    [106] = {id=106,en="Skillchain Bonus",ja="連携ボーナス",de="Domino-Effekt",fr="Chaîne experte",element=6,icon_id=46,range=0,targets=0},
    [107] = {id=107,en="Fencer",ja="フェンサー",de="Fechter",fr="Escrimeur",element=6,icon_id=46,range=0,targets=0},
    [108] = {id=108,en="Conserve TP",ja="コンサーブTP",de="TP einsparen",fr="Economie TP",element=6,icon_id=46,range=0,targets=0},
    [109] = {id=109,en="Occult Acumen",ja="マジックアキュメン",de="Okkult. Scharfsinn",fr="Virtuosité occulte",element=6,icon_id=46,range=0,targets=0},
    [110] = {id=110,en="Mag. Burst Bonus",ja="MB.ボーナス",de="Mag.-Schub-Bon.",fr="Bonus expl. mag.",element=6,icon_id=46,range=0,targets=0},
    [111] = {id=111,en="Divine Benison",ja="ディバインベニゾン",de="Gottesgabe",fr="Faveur divine",element=6,icon_id=46,range=0,targets=0},
    [112] = {id=112,en="Elemental Celerity",ja="エレメントセレリティ",de="Elementar-R.",fr="Incant. accélérée",element=7,icon_id=47,range=0,targets=0},
    [113] = {id=113,en="Dead Aim",ja="デッドエイム",de="Herzschuss",fr="Visée d'élite",element=6,icon_id=46,range=0,targets=0},
    [114] = {id=114,en="Tranquil Heart",ja="トランキルハート",de="Friedvolles Herz",fr="Ame sereine",element=6,icon_id=46,range=0,targets=0},
    [115] = {id=115,en="Stalwart Soul",ja="ストルワートソウル",de="Standhafte Seele",fr="Noirc. insoumise",element=7,icon_id=47,range=0,targets=0},
    [116] = {id=116,en="Cardinal Chant",ja="カーディナルチャント",de="Kardinalsgesang",fr="Psalm. cardinale",element=6,icon_id=46,range=0,targets=0},
    [117] = {id=117,en="Tenacity",ja="テナシティ",de="Zähigkeit",fr="Fermeté",element=6,icon_id=46,range=0,targets=0},
    [118] = {id=118,en="Inquartata",ja="インクァルタタ",de="Inquartata",fr="Incartade",element=6,icon_id=46,range=0,targets=0},
    [119] = {id=119,en="C. Recantation",ja="キュアリカント",de="K. Widerrufung",fr="Repli curatif",element=6,icon_id=46,range=0,targets=0},
    [120] = {id=120,en="Primeval Zeal",ja="プライムジール",de="Urz. Eifer",fr="Zèle primitif",element=7,icon_id=47,range=0,targets=0},
    [121] = {id=121,en="Inspiration",ja="インスパイア",de="Inspiration",fr="Inspiration",element=6,icon_id=46,range=0,targets=0},
    [122] = {id=122,en="Sleight of Sword",ja="スライトソード",de="Flinke Klinge",fr="Lame agile",element=2,icon_id=42,range=0,targets=0},
}, {"id", "en", "ja", "de", "fr", "element", "icon_id", "range", "targets"}

--[[
Copyright © 2013-2014, Windower
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Windower nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Windower BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
