-- Automatically generated file: Spell Recasts

return {
    [1] = {id=1,en="Cure",ja="ケアル",de="Heilen",fr="Soin",recast=20},
    [2] = {id=2,en="Cure II",ja="ケアルII",de="Heilen II",fr="Soin II",recast=22},
    [3] = {id=3,en="Cure III",ja="ケアルIII",de="Heilen III",fr="Soin III",recast=24},
    [4] = {id=4,en="Cure IV",ja="ケアルIV",de="Heilen IV",fr="Soin IV",recast=32},
    [5] = {id=5,en="Cure V",ja="ケアルV",de="Heilen V",fr="Soin V",recast=40},
    [6] = {id=6,en="Cure VI",ja="ケアルVI",de="Heilen VI",fr="Soin VI",recast=60},
    [7] = {id=7,en="Curaga",ja="ケアルガ",de="Heilga",fr="OmniSoin",recast=40},
    [8] = {id=8,en="Curaga II",ja="ケアルガII",de="Heilga II",fr="OmniSoin II",recast=41},
    [9] = {id=9,en="Curaga III",ja="ケアルガIII",de="Heilga III",fr="OmniSoin III",recast=42},
    [10] = {id=10,en="Curaga IV",ja="ケアルガIV",de="Heilga IV",fr="OmniSoin IV",recast=43},
    [11] = {id=11,en="Curaga V",ja="ケアルガV",de="Heilga V",fr="OmniSoin V",recast=44},
    [12] = {id=12,en="Cura",ja="ケアルラ",de="Vitra",fr="MultiSoin",recast=120},
    [13] = {id=13,en="Cura II",ja="ケアルラII",de="Vitra II",fr="MultiSoin II",recast=160},
    [14] = {id=14,en="Cura III",ja="ケアルラIII",de="Vitra III",fr="MultiSoin III",recast=200},
    [15] = {id=15,en="Raise",ja="レイズ",de="Wiederbeleben",fr="Vie",recast=240},
    [16] = {id=16,en="Raise II",ja="レイズII",de="Wiederbeleben II",fr="Vie II",recast=240},
    [17] = {id=17,en="Raise III",ja="レイズIII",de="Wiederbeleben III",fr="Vie III",recast=240},
    [18] = {id=18,en="Arise",ja="アレイズ",de="Erzengel",fr="Résurrection",recast=224},
    [19] = {id=19,en="Reraise",ja="リレイズ",de="Wiederauferstehen",fr="Revie",recast=240},
    [20] = {id=20,en="Reraise II",ja="リレイズII",de="Wiederauferst. II",fr="Revie II",recast=240},
    [21] = {id=21,en="Reraise III",ja="リレイズIII",de="Wiederauferst. III",fr="Revie III",recast=240},
    [22] = {id=22,en="Poisona",ja="ポイゾナ",de="Giftna",fr="CuraPoison",recast=20},
    [23] = {id=23,en="Paralyna",ja="パラナ",de="Paralyna",fr="CuraParalysie",recast=20},
    [24] = {id=24,en="Blindna",ja="ブライナ",de="Blindna",fr="CuraCécité",recast=40},
    [25] = {id=25,en="Silena",ja="サイレナ",de="Schweigna",fr="CuraSilence",recast=20},
    [26] = {id=26,en="Stona",ja="ストナ",de="Steina",fr="CuraPétrification",recast=20},
    [27] = {id=27,en="Viruna",ja="ウィルナ",de="Viruna",fr="CuraVirus",recast=20},
    [28] = {id=28,en="Cursna",ja="カーズナ",de="Fluchna",fr="CuraMaléfice",recast=40},
    [29] = {id=29,en="Sacrifice",ja="サクリファイス",de="Aufopfern",fr="Sacrifice",recast=120},
    [30] = {id=30,en="Esuna",ja="エスナ",de="Medica",fr="Guérison",recast=120},
    [35] = {id=35,en="Holy",ja="ホーリー",de="Heilig",fr="Miracle",recast=240},
    [36] = {id=36,en="Holy II",ja="ホーリーII",de="Heilig II",fr="Miracle II",recast=240},
    [37] = {id=37,en="Banish",ja="バニシュ",de="Verbannen",fr="Bannissement",recast=60},
    [38] = {id=38,en="Banish II",ja="バニシュII",de="Verbannen II",fr="Bannissement II",recast=120},
    [39] = {id=39,en="Banish III",ja="バニシュIII",de="Verbannen III",fr="Bannissement III",recast=180},
    [40] = {id=40,en="Banish IV",ja="バニシュIV",de="Verbannen IV",fr="Bannissement IV",recast=180},
    [41] = {id=41,en="Banish V",ja="バニシュV",de="Verbannen V",fr="Bannissement V",recast=240},
    [42] = {id=42,en="Banishga",ja="バニシュガ",de="Verbannga",fr="OmniBannissement",recast=60},
    [43] = {id=43,en="Banishga II",ja="バニシュガII",de="Verbannga II",fr="OmniBanniss. II",recast=120},
    [44] = {id=44,en="Banishga III",ja="バニシュガIII",de="Verbannga III",fr="OmniBanniss. III",recast=180},
    [45] = {id=45,en="Banishga IV",ja="バニシュガIV",de="Verbannga IV",fr="OmniBanniss. IV",recast=240},
    [46] = {id=46,en="Banishga V",ja="バニシュガV",de="Verbannga V",fr="OmniBanniss. V",recast=240},
    [47] = {id=47,en="Repose",ja="リポーズ",de="Schlummer",fr="Sérénité",recast=120},
    [48] = {id=48,en="Flash",ja="フラッシュ",de="Blitzlicht",fr="Flash",recast=180},
    [49] = {id=49,en="Enlight",ja="エンライト",de="Licht +",fr="EndoLumière",recast=120},
    [50] = {id=50,en="Protect",ja="プロテス",de="Schutz",fr="Bouclier",recast=20},
    [51] = {id=51,en="Protect II",ja="プロテスII",de="Schutz II",fr="Bouclier II",recast=21},
    [52] = {id=52,en="Protect III",ja="プロテスIII",de="Schutz III",fr="Bouclier III",recast=22},
    [53] = {id=53,en="Protect IV",ja="プロテスIV",de="Schutz IV",fr="Bouclier IV",recast=23},
    [54] = {id=54,en="Protect V",ja="プロテスV",de="Schutz V",fr="Bouclier V",recast=24},
    [55] = {id=55,en="Shell",ja="シェル",de="Schutzschirm",fr="Barrière",recast=20},
    [56] = {id=56,en="Shell II",ja="シェルII",de="Schutzschirm II",fr="Barrière II",recast=21},
    [57] = {id=57,en="Shell III",ja="シェルIII",de="Schutzschirm III",fr="Barrière III",recast=22},
    [58] = {id=58,en="Shell IV",ja="シェルIV",de="Schutzschirm IV",fr="Barrière IV",recast=23},
    [59] = {id=59,en="Shell V",ja="シェルV",de="Schutzschirm V",fr="Barrière V",recast=24},
    [60] = {id=60,en="Protectra",ja="プロテア",de="Schutzra",fr="OmniBouclier",recast=60},
    [61] = {id=61,en="Protectra II",ja="プロテアII",de="Schutzra II",fr="OmniBouclier II",recast=64},
    [62] = {id=62,en="Protectra III",ja="プロテアIII",de="Schutzra III",fr="OmniBouclier III",recast=68},
    [63] = {id=63,en="Protectra IV",ja="プロテアIV",de="Schutzra IV",fr="OmniBouclier IV",recast=72},
    [64] = {id=64,en="Protectra V",ja="プロテアV",de="Schutzra V",fr="OmniBouclier V",recast=76},
    [65] = {id=65,en="Shellra",ja="シェルラ",de="Schutzschirmra",fr="OmniBarrière",recast=60},
    [66] = {id=66,en="Shellra II",ja="シェルラII",de="Schutzschirmra II",fr="OmniBarrière II",recast=64},
    [67] = {id=67,en="Shellra III",ja="シェルラIII",de="Schutzschirmra III",fr="OmniBarrière III",recast=68},
    [68] = {id=68,en="Shellra IV",ja="シェルラIV",de="Schutzschirmra IV",fr="OmniBarrière IV",recast=72},
    [69] = {id=69,en="Shellra V",ja="シェルラV",de="Schutzschirmra V",fr="OmniBarrière V",recast=76},
    [70] = {id=70,en="Blink",ja="ブリンク",de="Spiegelschimmer",fr="Faux-semblant",recast=40},
    [71] = {id=71,en="Stoneskin",ja="ストンスキン",de="Steinhaut",fr="Cuirasse",recast=120},
    [72] = {id=72,en="Aquaveil",ja="アクアベール",de="Wasserschleier",fr="Aquavoile",recast=40},
    [73] = {id=73,en="Phalanx",ja="ファランクス",de="Phalanx",fr="Phalange",recast=40},
    [74] = {id=74,en="Phalanx II",ja="ファランクスII",de="Phalanx II",fr="Phalange II",recast=40},
    [75] = {id=75,en="Reprisal",ja="リアクト",de="Reflexion",fr="Représailles",recast=208},
    [76] = {id=76,en="Foil",ja="フォイル",de="Traverse",fr="Désengagement",recast=180},
    [77] = {id=77,en="Haste",ja="ヘイスト",de="Hast",fr="Hâte",recast=80},
    [78] = {id=78,en="Barfire",ja="バファイ",de="Feuerriegel",fr="AntiFeu",recast=40},
    [79] = {id=79,en="Barblizzard",ja="バブリザ",de="Eisriegel",fr="AntiGlace",recast=40},
    [80] = {id=80,en="Baraero",ja="バエアロ",de="Windriegel",fr="AntiVent",recast=40},
    [81] = {id=81,en="Barstone",ja="バストン",de="Erdenriegel",fr="AntiPierre",recast=40},
    [82] = {id=82,en="Barthunder",ja="バサンダ",de="Donnerriegel",fr="AntiFoudre",recast=40},
    [83] = {id=83,en="Barwater",ja="バウォタ",de="Wasserriegel",fr="AntiEau",recast=40},
    [84] = {id=84,en="Barfira",ja="バファイラ",de="Feuerriegelra",fr="OmniAntiFeu",recast=40},
    [85] = {id=85,en="Barblizzara",ja="バブリザラ",de="Eisriegelra",fr="OmniAntiGlace",recast=40},
    [86] = {id=86,en="Baraera",ja="バエアロラ",de="Windriegelra",fr="OmniAntiVent",recast=40},
    [87] = {id=87,en="Barstonra",ja="バストンラ",de="Erdenriegelra",fr="OmniAntiPierre",recast=40},
    [88] = {id=88,en="Barthundra",ja="バサンダラ",de="Donnerriegelra",fr="OmniAntiFoudre",recast=40},
    [89] = {id=89,en="Barwatera",ja="バウォタラ",de="Wasserriegelra",fr="OmniAntiEau",recast=40},
    [90] = {id=90,en="Barsleep",ja="バスリプル",de="Schlafriegel",fr="AntiSommeil",recast=40},
    [91] = {id=91,en="Barpoison",ja="バポイズン",de="Giftriegel",fr="AntiPoison",recast=40},
    [92] = {id=92,en="Barparalyze",ja="バパライズ",de="Paralyseriegel",fr="AntiParalysie",recast=40},
    [93] = {id=93,en="Barblind",ja="バブライン",de="Blindriegel",fr="AntiCécité",recast=40},
    [94] = {id=94,en="Barsilence",ja="バサイレス",de="Schweigriegel",fr="AntiSilence",recast=40},
    [95] = {id=95,en="Barpetrify",ja="バブレイク",de="Steinriegel",fr="AntiPétrification",recast=40},
    [96] = {id=96,en="Barvirus",ja="バウィルス",de="Virenriegel",fr="AntiVirus",recast=40},
    [97] = {id=97,en="Baramnesia",ja="バアムネジア",de="Amnesieriegel",fr="AntiAmnésie",recast=40},
    [98] = {id=98,en="Barsleepra",ja="バスリプラ",de="Schlafriegelra",fr="OmniAntiSommeil",recast=40},
    [99] = {id=99,en="Barpoisonra",ja="バポイゾラ",de="Giftriegelra",fr="OmniAntiPoison",recast=40},
    [100] = {id=100,en="Barparalyzra",ja="バパライラ",de="Paralyseriegelra",fr="OmniAntiParalysie",recast=40},
    [101] = {id=101,en="Barblindra",ja="バブライラ",de="Blindriegelra",fr="OmniAntiCécité",recast=40},
    [102] = {id=102,en="Barsilencera",ja="バサイレラ",de="Schweigriegelra",fr="OmniAntiSilence",recast=40},
    [103] = {id=103,en="Barpetra",ja="バブレクラ",de="Steinriegelra",fr="OmniAntiPétrif.",recast=40},
    [104] = {id=104,en="Barvira",ja="バウィルラ",de="Virenriegelra",fr="OmniAntiVirus",recast=40},
    [105] = {id=105,en="Baramnesra",ja="バアムネジラ",de="Amnesieriegelra",fr="OmniAntiAmnésie",recast=40},
    [106] = {id=106,en="Enfire",ja="エンファイア",de="Feuer +",fr="EndoFeu",recast=40},
    [107] = {id=107,en="Enfire II",ja="エンファイアII",de="Feuer ++",fr="EndoFeu II",recast=120},
    [108] = {id=108,en="Enblizzard",ja="エンブリザド",de="Eis +",fr="EndoGlace",recast=40},
    [109] = {id=109,en="Enblizzard II",ja="エンブリザドII",de="Eis ++",fr="EndoGlace II",recast=120},
    [110] = {id=110,en="Enaero",ja="エンエアロ",de="Wind +",fr="EndoVent",recast=40},
    [111] = {id=111,en="Enaero II",ja="エンエアロII",de="Wind ++",fr="EndoVent II",recast=120},
    [112] = {id=112,en="Enstone",ja="エンストーン",de="Erde +",fr="EndoPierre",recast=40},
    [113] = {id=113,en="Enstone II",ja="エンストーンII",de="Erde ++",fr="EndoPierre II",recast=120},
    [114] = {id=114,en="Enthunder",ja="エンサンダー",de="Donner +",fr="EndoFoudre",recast=40},
    [115] = {id=115,en="Enthunder II",ja="エンサンダーII",de="Donner ++",fr="EndoFoudre II",recast=120},
    [116] = {id=116,en="Enwater",ja="エンウォータ",de="Wasser +",fr="EndoEau",recast=40},
    [117] = {id=117,en="Enwater II",ja="エンウォータII",de="Wasser ++",fr="EndoEau II",recast=120},
    [118] = {id=118,en="Auspice",ja="オースピス",de="Auspizium",fr="Auspice",recast=40},
    [119] = {id=119,en="Temper",ja="ストライ",de="Temperament",fr="Irritation",recast=120},
    [120] = {id=120,en="Regen",ja="リジェネ",de="Regenerieren",fr="Récup",recast=48},
    [121] = {id=121,en="Regen II",ja="リジェネII",de="Regenerieren II",fr="Récup II",recast=64},
    [122] = {id=122,en="Regen III",ja="リジェネIII",de="Regenerieren III",fr="Récup III",recast=80},
    [123] = {id=123,en="Regen IV",ja="リジェネIV",de="Regenerieren IV",fr="Récup IV",recast=96},
    [124] = {id=124,en="Regen V",ja="リジェネV",de="Regenerieren V",fr="Récup V",recast=112},
    [125] = {id=125,en="Refresh",ja="リフレシュ",de="Erfrischen",fr="Recharge",recast=72},
    [126] = {id=126,en="Refresh II",ja="リフレシュII",de="Erfrischen II",fr="Recharge II",recast=108},
    [127] = {id=127,en="Sandstorm",ja="砂塵の陣",de="Staubfront",fr="Loi de la sécher.",recast=72},
    [128] = {id=128,en="Rainstorm",ja="豪雨の陣",de="Regenfront",fr="Loi des averses",recast=72},
    [129] = {id=129,en="Windstorm",ja="烈風の陣",de="Sturmfront",fr="Loi des ouragans",recast=72},
    [130] = {id=130,en="Firestorm",ja="熱波の陣",de="Feuerfront",fr="Loi de la canicule",recast=72},
    [131] = {id=131,en="Hailstorm",ja="吹雪の陣",de="Hagelfront",fr="Loi du blizzard",recast=72},
    [132] = {id=132,en="Thunderstorm",ja="疾雷の陣",de="Gewitterfront",fr="Loi des orages",recast=72},
    [133] = {id=133,en="Voidstorm",ja="妖霧の陣",de="Nebelfront",fr="Loi du crépuscule",recast=72},
    [134] = {id=134,en="Aurorastorm",ja="極光の陣",de="Aurorafront",fr="Loi de l'aurore",recast=72},
    [135] = {id=135,en="Animus Augeo",ja="悪事千里の策",de="Hostilia",fr="Traité d'animosité",recast=40},
    [136] = {id=136,en="Animus Minuo",ja="暗中飛躍の策",de="Pacificatio",fr="Traité de cordialité",recast=40},
    [137] = {id=137,en="Adloquium",ja="鼓舞激励の策",de="Adloquium",fr="Traité d'exhortation",recast=72},
    [138] = {id=138,en="Erase",ja="イレース",de="Entfernen",fr="Gomme",recast=60},
    [140] = {id=140,en="Gain-STR",ja="ゲインスト",de="STR-Stimulus",fr="Gain-STR",recast=40},
    [141] = {id=141,en="Gain-DEX",ja="ゲインデック",de="DEX-Stimulus",fr="Gain-DEX",recast=40},
    [142] = {id=142,en="Gain-VIT",ja="ゲインバイト",de="VIT-Stimulus",fr="Gain-VIT",recast=40},
    [143] = {id=143,en="Gain-AGI",ja="ゲインアジル",de="AGI-Stimulus",fr="Gain-AGI",recast=40},
    [144] = {id=144,en="Gain-INT",ja="ゲインイン",de="INT-Stimulus",fr="Gain-INT",recast=40},
    [145] = {id=145,en="Gain-MND",ja="ゲインマイン",de="MND-Stimulus",fr="Gain-MND",recast=40},
    [146] = {id=146,en="Gain-CHR",ja="ゲインカリス",de="CHR-Stimulus",fr="Gain-CHR",recast=40},
    [147] = {id=147,en="Boost-STR",ja="アディスト",de="STR-Augmen",fr="Augment-STR",recast=40},
    [148] = {id=148,en="Boost-DEX",ja="アディデック",de="DEX-Augmen",fr="Augment-DEX",recast=40},
    [149] = {id=149,en="Boost-VIT",ja="アディバイト",de="VIT-Augmen",fr="Augment-VIT",recast=40},
    [150] = {id=150,en="Boost-AGI",ja="アディアジル",de="AGI-Augmen",fr="Augment-AGI",recast=40},
    [151] = {id=151,en="Boost-INT",ja="アディイン",de="INT-Augmen",fr="Augment-INT",recast=40},
    [152] = {id=152,en="Boost-MND",ja="アディマイン",de="MND-Augmen",fr="Augment-MND",recast=40},
    [153] = {id=153,en="Boost-CHR",ja="アディカリス",de="CHR-Augmen",fr="Augment-CHR",recast=40},
    [154] = {id=154,en="Teleport-Holla",ja="テレポホラ",de="Teleport-Holla",fr="Téléport-Holla",recast=40},
    [155] = {id=155,en="Teleport-Dem",ja="テレポデム",de="Teleport-Dem",fr="Téléport-Dem",recast=40},
    [156] = {id=156,en="Teleport-Mea",ja="テレポメア",de="Teleport-Mea",fr="Téléport-Mea",recast=40},
    [157] = {id=157,en="Teleport-Yhoat",ja="テレポヨト",de="Teleport-Yhoat",fr="Téléport-Yhoat",recast=40},
    [158] = {id=158,en="Teleport-Altep",ja="テレポルテ",de="Teleport-Altep",fr="Téléport-Altep",recast=40},
    [159] = {id=159,en="Teleport-Vahzl",ja="テレポヴァズ",de="Teleport-Vahzl",fr="Téléport-Vahzl",recast=40},
    [160] = {id=160,en="Recall-Jugner",ja="リコールジャグ",de="Retroport-Jug",fr="Rappel-Jugner",recast=40},
    [161] = {id=161,en="Recall-Pashh",ja="リコールパシュ",de="Retroport-Pash",fr="Rappel-Pashh",recast=40},
    [162] = {id=162,en="Recall-Meriph",ja="リコールメリファ",de="Retroport-Meri",fr="Rappel-Mériph",recast=40},
    [163] = {id=163,en="Invisible",ja="インビジ",de="Unsichtbarkeit",fr="Invisible",recast=40},
    [164] = {id=164,en="Sneak",ja="スニーク",de="Schleichen",fr="Furtivité",recast=40},
    [165] = {id=165,en="Deodorize",ja="デオード",de="Parfümieren",fr="Inodore",recast=32},
    [166] = {id=166,en="Embrava",ja="オーラ",de="Embrava",fr="Hardiesse",recast=24},
    [170] = {id=170,en="Dia",ja="ディア",de="Dia",fr="Lumen",recast=20},
    [171] = {id=171,en="Dia II",ja="ディアII",de="Dia II",fr="Lumen II",recast=24},
    [172] = {id=172,en="Dia III",ja="ディアIII",de="Dia III",fr="Lumen III",recast=28},
    [173] = {id=173,en="Dia IV",ja="ディアIV",de="Dia IV",fr="Lumen IV",recast=32},
    [174] = {id=174,en="Dia V",ja="ディアV",de="Dia V",fr="Lumen V",recast=36},
    [175] = {id=175,en="Diaga",ja="ディアガ",de="Diaga",fr="OmniLumen",recast=24},
    [176] = {id=176,en="Diaga II",ja="ディアガII",de="Diaga II",fr="OmniLumen II",recast=25},
    [177] = {id=177,en="Diaga III",ja="ディアガIII",de="Diaga III",fr="OmniLumen III",recast=26},
    [178] = {id=178,en="Diaga IV",ja="ディアガIV",de="Diaga IV",fr="OmniLumen IV",recast=27},
    [179] = {id=179,en="Diaga V",ja="ディアガV",de="Diaga V",fr="OmniLumen V",recast=28},
    [180] = {id=180,en="Slow",ja="スロウ",de="Gemach",fr="Lenteur",recast=80},
    [181] = {id=181,en="Slow II",ja="スロウII",de="Gemach II",fr="Lenteur II",recast=80},
    [182] = {id=182,en="Paralyze",ja="パライズ",de="Paralyse",fr="Paralysie",recast=40},
    [183] = {id=183,en="Paralyze II",ja="パライズII",de="Paralyse II",fr="Paralysie II",recast=80},
    [184] = {id=184,en="Silence",ja="サイレス",de="Schweigen",fr="Silence",recast=40},
    [185] = {id=185,en="Addle",ja="アドル",de="Geist-Vernebelung",fr="Egarement",recast=80},
    [190] = {id=190,en="Fire",ja="ファイア",de="Feuer",fr="Feu",recast=8},
    [191] = {id=191,en="Fire II",ja="ファイアII",de="Feuer II",fr="Feu II",recast=24},
    [192] = {id=192,en="Fire III",ja="ファイアIII",de="Feuer III",fr="Feu III",recast=60},
    [193] = {id=193,en="Fire IV",ja="ファイアIV",de="Feuer IV",fr="Feu IV",recast=120},
    [194] = {id=194,en="Fire V",ja="ファイアV",de="Feuer V",fr="Feu V",recast=180},
    [195] = {id=195,en="Blizzard",ja="ブリザド",de="Eis",fr="Glace",recast=8},
    [196] = {id=196,en="Blizzard II",ja="ブリザドII",de="Eis II",fr="Glace II",recast=24},
    [197] = {id=197,en="Blizzard III",ja="ブリザドIII",de="Eis III",fr="Glace III",recast=60},
    [198] = {id=198,en="Blizzard IV",ja="ブリザドIV",de="Eis IV",fr="Glace IV",recast=120},
    [199] = {id=199,en="Blizzard V",ja="ブリザドV",de="Eis V",fr="Glace V",recast=180},
    [200] = {id=200,en="Aero",ja="エアロ",de="Wind",fr="Vent",recast=8},
    [201] = {id=201,en="Aero II",ja="エアロII",de="Wind II",fr="Vent II",recast=24},
    [202] = {id=202,en="Aero III",ja="エアロIII",de="Wind III",fr="Vent III",recast=60},
    [203] = {id=203,en="Aero IV",ja="エアロIV",de="Wind IV",fr="Vent IV",recast=120},
    [204] = {id=204,en="Aero V",ja="エアロV",de="Wind V",fr="Vent V",recast=180},
    [205] = {id=205,en="Stone",ja="ストーン",de="Erde",fr="Pierre",recast=8},
    [206] = {id=206,en="Stone II",ja="ストーンII",de="Erde II",fr="Pierre II",recast=24},
    [207] = {id=207,en="Stone III",ja="ストーンIII",de="Erde III",fr="Pierre III",recast=60},
    [208] = {id=208,en="Stone IV",ja="ストーンIV",de="Erde IV",fr="Pierre IV",recast=120},
    [209] = {id=209,en="Stone V",ja="ストーンV",de="Erde V",fr="Pierre V",recast=180},
    [210] = {id=210,en="Thunder",ja="サンダー",de="Donner",fr="Foudre",recast=8},
    [211] = {id=211,en="Thunder II",ja="サンダーII",de="Donner II",fr="Foudre II",recast=24},
    [212] = {id=212,en="Thunder III",ja="サンダーIII",de="Donner III",fr="Foudre III",recast=60},
    [213] = {id=213,en="Thunder IV",ja="サンダーIV",de="Donner IV",fr="Foudre IV",recast=120},
    [214] = {id=214,en="Thunder V",ja="サンダーV",de="Donner V",fr="Foudre V",recast=180},
    [215] = {id=215,en="Water",ja="ウォータ",de="Wasser",fr="Eau",recast=8},
    [216] = {id=216,en="Water II",ja="ウォータII",de="Wasser II",fr="Eau II",recast=24},
    [217] = {id=217,en="Water III",ja="ウォータIII",de="Wasser III",fr="Eau III",recast=60},
    [218] = {id=218,en="Water IV",ja="ウォータIV",de="Wasser IV",fr="Eau IV",recast=120},
    [219] = {id=219,en="Water V",ja="ウォータV",de="Wasser V",fr="Eau V",recast=180},
    [220] = {id=220,en="Firaga",ja="ファイガ",de="Feuerga",fr="OmniFeu",recast=20},
    [221] = {id=221,en="Firaga II",ja="ファイガII",de="Feuerga II",fr="OmniFeu II",recast=40},
    [222] = {id=222,en="Firaga III",ja="ファイガIII",de="Feuerga III",fr="OmniFeu III",recast=100},
    [223] = {id=223,en="Firaga IV",ja="ファイガIV",de="Feuerga IV",fr="OmniFeu IV",recast=160},
    [224] = {id=224,en="Firaga V",ja="ファイガV",de="Feuerga V",fr="OmniFeu V",recast=240},
    [225] = {id=225,en="Blizzaga",ja="ブリザガ",de="Eisga",fr="OmniGlace",recast=20},
    [226] = {id=226,en="Blizzaga II",ja="ブリザガII",de="Eisga II",fr="OmniGlace II",recast=40},
    [227] = {id=227,en="Blizzaga III",ja="ブリザガIII",de="Eisga III",fr="OmniGlace III",recast=100},
    [228] = {id=228,en="Blizzaga IV",ja="ブリザガIV",de="Eisga IV",fr="OmniGlace IV",recast=160},
    [229] = {id=229,en="Blizzaga V",ja="ブリザガV",de="Eisga V",fr="OmniGlace V",recast=240},
    [230] = {id=230,en="Aeroga",ja="エアロガ",de="Windga",fr="OmniVent",recast=20},
    [231] = {id=231,en="Aeroga II",ja="エアロガII",de="Windga II",fr="OmniVent II",recast=40},
    [232] = {id=232,en="Aeroga III",ja="エアロガIII",de="Windga III",fr="OmniVent III",recast=100},
    [233] = {id=233,en="Aeroga IV",ja="エアロガIV",de="Windga IV",fr="OmniVent IV",recast=160},
    [234] = {id=234,en="Aeroga V",ja="エアロガV",de="Windga V",fr="OmniVent V",recast=240},
    [235] = {id=235,en="Stonega",ja="ストンガ",de="Erdenga",fr="OmniPierre",recast=20},
    [236] = {id=236,en="Stonega II",ja="ストンガII",de="Erdenga II",fr="OmniPierre II",recast=40},
    [237] = {id=237,en="Stonega III",ja="ストンガIII",de="Erdenga III",fr="OmniPierre III",recast=100},
    [238] = {id=238,en="Stonega IV",ja="ストンガIV",de="Erdenga IV",fr="OmniPierre IV",recast=160},
    [239] = {id=239,en="Stonega V",ja="ストンガV",de="Erdenga V",fr="OmniPierre V",recast=240},
    [240] = {id=240,en="Thundaga",ja="サンダガ",de="Donnerga",fr="OmniFoudre",recast=20},
    [241] = {id=241,en="Thundaga II",ja="サンダガII",de="Donnerga II",fr="OmniFoudre II",recast=40},
    [242] = {id=242,en="Thundaga III",ja="サンダガIII",de="Donnerga III",fr="OmniFoudre III",recast=100},
    [243] = {id=243,en="Thundaga IV",ja="サンダガIV",de="Donnerga IV",fr="OmniFoudre IV",recast=160},
    [244] = {id=244,en="Thundaga V",ja="サンダガV",de="Donnerga V",fr="OmniFoudre V",recast=240},
    [245] = {id=245,en="Waterga",ja="ウォタガ",de="Wasserga",fr="OmniEau",recast=20},
    [246] = {id=246,en="Waterga II",ja="ウォタガII",de="Wasserga II",fr="OmniEau II",recast=40},
    [247] = {id=247,en="Waterga III",ja="ウォタガIII",de="Wasserga III",fr="OmniEau III",recast=100},
    [248] = {id=248,en="Waterga IV",ja="ウォタガIV",de="Wasserga IV",fr="OmniEau IV",recast=160},
    [249] = {id=249,en="Waterga V",ja="ウォタガV",de="Wasserga V",fr="OmniEau V",recast=240},
    [250] = {id=250,en="Firaja",ja="ファイジャ",de="Feuerka",fr="MaxiFeu",recast=180},
    [251] = {id=251,en="Blizzaja",ja="ブリザジャ",de="Eiska",fr="MaxiGlace",recast=180},
    [252] = {id=252,en="Aeroja",ja="エアロジャ",de="Windka",fr="MaxiVent",recast=180},
    [253] = {id=253,en="Stoneja",ja="ストンジャ",de="Erdenka",fr="MaxiPierre",recast=180},
    [254] = {id=254,en="Thundaja",ja="サンダジャ",de="Donnerka",fr="MaxiFoudre",recast=180},
    [255] = {id=255,en="Waterja",ja="ウォタジャ",de="Wasserka",fr="MaxiEau",recast=180},
    [256] = {id=256,en="Fira",ja="ファイラ",de="Feura",fr="MultiFeu",recast=20},
    [257] = {id=257,en="Fira II",ja="ファイラII",de="Feura II",fr="MultiFeu II",recast=60},
    [258] = {id=258,en="Blizzara",ja="ブリザラ",de="Eisra",fr="MultiGlace",recast=20},
    [259] = {id=259,en="Blizzara II",ja="ブリザラII",de="Eisra II",fr="MultiGlace II",recast=60},
    [260] = {id=260,en="Aerora",ja="エアロラ",de="Windra",fr="MultiVent",recast=20},
    [261] = {id=261,en="Aerora II",ja="エアロラII",de="Windra II",fr="MultiVent II",recast=60},
    [262] = {id=262,en="Stonera",ja="ストンラ",de="Erdenra",fr="MultiPierre",recast=20},
    [263] = {id=263,en="Stonera II",ja="ストンラII",de="Erdenra II",fr="MultiPierre II",recast=60},
    [264] = {id=264,en="Thundara",ja="サンダラ",de="Donnerra",fr="MultiFoudre",recast=20},
    [265] = {id=265,en="Thundara II",ja="サンダラII",de="Donnerra II",fr="MultiFoudre II",recast=60},
    [266] = {id=266,en="Watera",ja="ウォタラ",de="Wasserra",fr="MultiEau",recast=20},
    [267] = {id=267,en="Watera II",ja="ウォタラII",de="Wasserra II",fr="MultiEau II",recast=60},
    [268] = {id=268,en="Flare",ja="フレア",de="Flimmern",fr="Brasier",recast=240},
    [269] = {id=269,en="Flare II",ja="フレアII",de="Flimmern II",fr="Brasier II",recast=240},
    [270] = {id=270,en="Freeze",ja="フリーズ",de="Einfrieren",fr="Gel",recast=240},
    [271] = {id=271,en="Freeze II",ja="フリーズII",de="Einfrieren II",fr="Gel II",recast=240},
    [272] = {id=272,en="Tornado",ja="トルネド",de="Tornado",fr="Tornade",recast=240},
    [273] = {id=273,en="Tornado II",ja="トルネドII",de="Tornado II",fr="Tornade II",recast=240},
    [274] = {id=274,en="Quake",ja="クエイク",de="Beben",fr="Séisme",recast=240},
    [275] = {id=275,en="Quake II",ja="クエイクII",de="Beben II",fr="Séisme II",recast=240},
    [276] = {id=276,en="Burst",ja="バースト",de="Einschlag",fr="Eclair",recast=240},
    [277] = {id=277,en="Burst II",ja="バーストII",de="Einschlag II",fr="Eclair II",recast=240},
    [278] = {id=278,en="Flood",ja="フラッド",de="Flut",fr="Déluge",recast=240},
    [279] = {id=279,en="Flood II",ja="フラッドII",de="Flut II",fr="Déluge II",recast=240},
    [280] = {id=280,en="Meteor",ja="メテオ",de="Meteor",fr="Météore",recast=208},
    [281] = {id=281,en="Comet",ja="コメット",de="Komet",fr="Comète",recast=180},
    [282] = {id=282,en="Burn",ja="バーン",de="Brennen",fr="Combustion",recast=40},
    [283] = {id=283,en="Frost",ja="フロスト",de="Frost",fr="Givre",recast=40},
    [284] = {id=284,en="Choke",ja="チョーク",de="Drossel",fr="Suffocation",recast=40},
    [285] = {id=285,en="Rasp",ja="ラスプ",de="Raspel",fr="Râpe",recast=40},
    [286] = {id=286,en="Shock",ja="ショック",de="Schock",fr="Choc",recast=40},
    [287] = {id=287,en="Drown",ja="ドラウン",de="Ertrinken",fr="Submersion",recast=40},
    [288] = {id=288,en="Geohelix",ja="土門の計",de="Terras Kern",fr="Thèse tellurique",recast=180},
    [289] = {id=289,en="Hydrohelix",ja="水門の計",de="Neptuns Kern",fr="Thèse aquifère",recast=180},
    [290] = {id=290,en="Anemohelix",ja="風門の計",de="Austers Kern",fr="Thèse cyclonique",recast=180},
    [291] = {id=291,en="Pyrohelix",ja="火門の計",de="Vulkans Kern",fr="Thèse pyrogène",recast=180},
    [292] = {id=292,en="Cryohelix",ja="氷門の計",de="Aquilos Kern",fr="Thèse cryogène",recast=180},
    [293] = {id=293,en="Ionohelix",ja="雷門の計",de="Jupiters Kern",fr="Thèse ionique",recast=180},
    [294] = {id=294,en="Noctohelix",ja="闇門の計",de="Plutos Kern",fr="Thèse crépuscul.",recast=180},
    [295] = {id=295,en="Luminohelix",ja="光門の計",de="Apollos Kern",fr="Thèse aurorale",recast=180},
    [296] = {id=296,en="Impact",ja="インパクト",de="Impakt",fr="Aérolithe",recast=224},
    [297] = {id=297,en="(magic 505)",ja="(予備)",de="a line help text",fr=".",recast=20},
    [310] = {id=310,en="Blaze Spikes",ja="ブレイズスパイク",de="Flammenspitzen",fr="Pointes de feu",recast=40},
    [311] = {id=311,en="Ice Spikes",ja="アイススパイク",de="Eisspitzen",fr="Pointes de glace",recast=40},
    [312] = {id=312,en="Shock Spikes",ja="ショックスパイク",de="Schockspitzen",fr="Pointes de foudre",recast=40},
    [313] = {id=313,en="Retrace",ja="リトレース",de="Retrowarp",fr="Réminiscence",recast=40},
    [314] = {id=314,en="Warp",ja="デジョン",de="Warp",fr="Rapatriement",recast=40},
    [315] = {id=315,en="Warp II",ja="デジョンII",de="Warp II",fr="Rapatriement II",recast=40},
    [316] = {id=316,en="Escape",ja="エスケプ",de="Flucht",fr="Echappatoire",recast=240},
    [320] = {id=320,en="Poison",ja="ポイズン",de="Gift",fr="Poison",recast=20},
    [321] = {id=321,en="Poison II",ja="ポイズンII",de="Gift II",fr="Poison II",recast=20},
    [322] = {id=322,en="Poison III",ja="ポイズンIII",de="Gift III",fr="Poison III",recast=20},
    [323] = {id=323,en="Poison IV",ja="ポイズンIV",de="Gift IV",fr="Poison IV",recast=20},
    [324] = {id=324,en="Poison V",ja="ポイズンV",de="Gift V",fr="Poison V",recast=20},
    [325] = {id=325,en="Poisonga",ja="ポイゾガ",de="Giftga",fr="OmniPoison",recast=40},
    [326] = {id=326,en="Poisonga II",ja="ポイゾガII",de="Giftga II",fr="OmniPoison II",recast=40},
    [327] = {id=327,en="Poisonga III",ja="ポイゾガIII",de="Giftga III",fr="OmniPoison III",recast=40},
    [328] = {id=328,en="Poisonga IV",ja="ポイゾガIV",de="Giftga IV",fr="OmniPoison IV",recast=40},
    [329] = {id=329,en="Poisonga V",ja="ポイゾガV",de="Giftga V",fr="OmniPoison V",recast=40},
    [330] = {id=330,en="Sleep",ja="スリプル",de="Schlaf",fr="Sommeil",recast=120},
    [331] = {id=331,en="Sleep II",ja="スリプルII",de="Schlaf II",fr="Sommeil II",recast=120},
    [332] = {id=332,en="Sleepga",ja="スリプガ",de="Schlafga",fr="OmniSommeil",recast=120},
    [333] = {id=333,en="Sleepga II",ja="スリプガII",de="Schlafga II",fr="OmniSommeil II",recast=180},
    [334] = {id=334,en="Blind",ja="ブライン",de="Blind",fr="Cécité",recast=40},
    [335] = {id=335,en="Blind II",ja="ブラインII",de="Blind II",fr="Cécité II",recast=80},
    [336] = {id=336,en="Break",ja="ブレイク",de="Stillstand",fr="Brèche",recast=120},
    [337] = {id=337,en="Breakga",ja="ブレクガ",de="Stillstandga",fr="OmniBrèche",recast=180},
    [338] = {id=338,en="Bind",ja="バインド",de="Fessel",fr="Entrave",recast=160},
    [339] = {id=339,en="Dispel",ja="ディスペル",de="Entzaubern",fr="Dissipation",recast=40},
    [340] = {id=340,en="Gravity",ja="グラビデ",de="Schwerkraft",fr="Pesanteur",recast=240},
    [341] = {id=341,en="Gravity II",ja="グラビデII",de="Schwerkraft II",fr="Pesanteur II",recast=44},
    [345] = {id=345,en="Bio",ja="バイオ",de="Bio",fr="Bactérie",recast=20},
    [346] = {id=346,en="Bio II",ja="バイオII",de="Bio II",fr="Bactérie II",recast=20},
    [347] = {id=347,en="Bio III",ja="バイオIII",de="Bio III",fr="Bactérie III",recast=60},
    [348] = {id=348,en="Bio IV",ja="バイオIV",de="Bio IV",fr="Bactérie IV",recast=20},
    [349] = {id=349,en="Bio V",ja="バイオV",de="Bio V",fr="Bactérie V",recast=20},
    [350] = {id=350,en="Drain",ja="ドレイン",de="Aussaugen",fr="Spoliation",recast=240},
    [351] = {id=351,en="Drain II",ja="ドレインII",de="Aussaugen II",fr="Spoliation II",recast=208},
    [352] = {id=352,en="Aspir",ja="アスピル",de="Osmose",fr="Aspiration",recast=240},
    [353] = {id=353,en="Aspir II",ja="アスピルII",de="Osmose II",fr="Aspiration II",recast=44},
    [354] = {id=354,en="Stun",ja="スタン",de="Betäubung",fr="Etourdissement",recast=180},
    [355] = {id=355,en="Tractor",ja="トラクタ",de="Schlepper",fr="Traction",recast=40},
    [356] = {id=356,en="Tractor II",ja="トラクタII",de="Schlepper II",fr="Traction II",recast=40},
    [357] = {id=357,en="Absorb-STR",ja="アブゾースト",de="Absorb-STR",fr="Absorb-STR",recast=240},
    [358] = {id=358,en="Absorb-DEX",ja="アブゾデック",de="Absorb-DEX",fr="Absorb-DEX",recast=240},
    [359] = {id=359,en="Absorb-VIT",ja="アブゾバイト",de="Absorb-VIT",fr="Absorb-VIT",recast=240},
    [360] = {id=360,en="Absorb-AGI",ja="アブゾアジル",de="Absorb-AGI",fr="Absorb-AGI",recast=240},
    [361] = {id=361,en="Absorb-INT",ja="アブゾイン",de="Absorb-INT",fr="Absorb-INT",recast=240},
    [362] = {id=362,en="Absorb-MND",ja="アブゾマイン",de="Absorb-MND",fr="Absorb-MND",recast=240},
    [363] = {id=363,en="Absorb-CHR",ja="アブゾカリス",de="Absorb-CHR",fr="Absorb-CHR",recast=240},
    [364] = {id=364,en="Absorb-TP",ja="アブゾタック",de="Absorb-TP",fr="Absorb-TP",recast=240},
    [365] = {id=365,en="Absorb-ACC",ja="アブゾアキュル",de="Absorb-ACC",fr="Absorb-Précision",recast=240},
    [366] = {id=366,en="Absorb-Attri",ja="アブゾアトリ",de="Absorb-Attri",fr="Absorb-Attribut",recast=240},
    [367] = {id=367,en="Dread Spikes",ja="ドレッドスパイク",de="Furchtspitzen",fr="Pointes d'effroi",recast=208},
    [368] = {id=368,en="Endark",ja="エンダーク",de="Dunkel +",fr="EndoTénèbres",recast=120},
    [369] = {id=369,en="Klimaform",ja="虚誘掩殺の策",de="Prognostica",fr="Traité de réflexion",recast=208},
    [370] = {id=370,en="Kaustra",ja="メルトン",de="Kaustra",fr="Kaustra",recast=120},
    [375] = {id=375,en="Fire Spirit",ja="火精霊召喚",de="Feuergeist",fr="Esprit du feu",recast=20},
    [376] = {id=376,en="Ice Spirit",ja="氷精霊召喚",de="Eisgeist",fr="Esprit de la glace",recast=20},
    [377] = {id=377,en="Air Spirit",ja="風精霊召喚",de="Luftgeist",fr="Esprit du vent",recast=20},
    [378] = {id=378,en="Earth Spirit",ja="土精霊召喚",de="Erdgeist",fr="Esprit de la terre",recast=20},
    [379] = {id=379,en="Thunder Spirit",ja="雷精霊召喚",de="Donnergeist",fr="Esprit de la foudre",recast=20},
    [380] = {id=380,en="Water Spirit",ja="水精霊召喚",de="Wassergeist",fr="Esprit de l'eau",recast=20},
    [381] = {id=381,en="Light Spirit",ja="光精霊召喚",de="Lichtgeist",fr="Esprit de la lumière",recast=20},
    [382] = {id=382,en="Dark Spirit",ja="闇精霊召喚",de="Dunkelgeist",fr="Esprit des ténèbres",recast=20},
    [383] = {id=383,en="Carbuncle",ja="カーバンクル召喚",de="Carbuncle",fr="Carbuncle",recast=20},
    [384] = {id=384,en="Fenrir",ja="フェンリル召喚",de="Fenrir",fr="Fenrir",recast=20},
    [385] = {id=385,en="Ifrit",ja="イフリート召喚",de="Ifrit",fr="Ifrit",recast=20},
    [386] = {id=386,en="Titan",ja="タイタン召喚",de="Titan",fr="Titan",recast=20},
    [387] = {id=387,en="Leviathan",ja="リヴァイアサン召喚",de="Leviathan",fr="Leviathan",recast=20},
    [388] = {id=388,en="Garuda",ja="ガルーダ召喚",de="Garuda",fr="Garuda",recast=20},
    [389] = {id=389,en="Shiva",ja="シヴァ召喚",de="Shiva",fr="Shiva",recast=20},
    [390] = {id=390,en="Ramuh",ja="ラムウ召喚",de="Ramuh",fr="Ramuh",recast=20},
    [391] = {id=391,en="Diabolos",ja="ディアボロス召喚",de="Diabolos",fr="Diabolos",recast=20},
    [392] = {id=392,en="Odin",ja="オーディン召喚",de="Odin",fr="Odin",recast=240},
    [393] = {id=393,en="Alexander",ja="アレキサンダー召喚",de="Alexander",fr="Alexander",recast=240},
    [394] = {id=394,en="Cait Sith",ja="ケット・シー召喚",de="Cait Sith",fr="Cait Sith",recast=20},
    [400] = {id=400,en="Katon: Ichi",ja="火遁の術:壱",de="Katon: Ichi",fr="Katon : Ichi",recast=120},
    [401] = {id=401,en="Katon: Ni",ja="火遁の術:弐",de="Katon: Ni",fr="Katon : Ni",recast=180},
    [402] = {id=402,en="Katon: San",ja="火遁の術:参",de="Katon: San",fr="Katon : San",recast=240},
    [403] = {id=403,en="Hyoton: Ichi",ja="氷遁の術:壱",de="Hyoton: Ichi",fr="Hyoton : Ichi",recast=120},
    [404] = {id=404,en="Hyoton: Ni",ja="氷遁の術:弐",de="Hyoton: Ni",fr="Hyoton : Ni",recast=180},
    [405] = {id=405,en="Hyoton: San",ja="氷遁の術:参",de="Hyoton: San",fr="Hyoton : San",recast=240},
    [406] = {id=406,en="Huton: Ichi",ja="風遁の術:壱",de="Huton: Ichi",fr="Huton : Ichi",recast=120},
    [407] = {id=407,en="Huton: Ni",ja="風遁の術:弐",de="Huton: Ni",fr="Huton : Ni",recast=180},
    [408] = {id=408,en="Huton: San",ja="風遁の術:参",de="Huton: San",fr="Huton : San",recast=240},
    [409] = {id=409,en="Doton: Ichi",ja="土遁の術:壱",de="Doton: Ichi",fr="Doton : Ichi",recast=120},
    [410] = {id=410,en="Doton: Ni",ja="土遁の術:弐",de="Doton: Ni",fr="Doton : Ni",recast=180},
    [411] = {id=411,en="Doton: San",ja="土遁の術:参",de="Doton: San",fr="Doton : San",recast=240},
    [412] = {id=412,en="Raiton: Ichi",ja="雷遁の術:壱",de="Raiton: Ichi",fr="Raiton : Ichi",recast=120},
    [413] = {id=413,en="Raiton: Ni",ja="雷遁の術:弐",de="Raiton: Ni",fr="Raiton : Ni",recast=180},
    [414] = {id=414,en="Raiton: San",ja="雷遁の術:参",de="Raiton: San",fr="Raiton : San",recast=240},
    [415] = {id=415,en="Suiton: Ichi",ja="水遁の術:壱",de="Suiton: Ichi",fr="Suiton : Ichi",recast=120},
    [416] = {id=416,en="Suiton: Ni",ja="水遁の術:弐",de="Suiton: Ni",fr="Suiton : Ni",recast=180},
    [417] = {id=417,en="Suiton: San",ja="水遁の術:参",de="Suiton: San",fr="Suiton : San",recast=240},
    [418] = {id=418,en="Utsusemi: Ichi",ja="空蝉の術:壱",de="Utsusemi: Ichi",fr="Utsusemi : Ichi",recast=120},
    [419] = {id=419,en="Utsusemi: Ni",ja="空蝉の術:弐",de="Utsusemi: Ni",fr="Utsusemi : Ni",recast=180},
    [420] = {id=420,en="Utsusemi: San",ja="空蝉の術:参",de="Utsusemi: San",fr="Utsusemi : San",recast=240},
    [421] = {id=421,en="Jubaku: Ichi",ja="呪縛の術:壱",de="Jubaku: Ichi",fr="Jubaku : Ichi",recast=120},
    [422] = {id=422,en="Jubaku: Ni",ja="呪縛の術:弐",de="Jubaku: Ni",fr="Jubaku : Ni",recast=180},
    [423] = {id=423,en="Jubaku: San",ja="呪縛の術:参",de="Jubaku: San",fr="Jubaku : San",recast=240},
    [424] = {id=424,en="Hojo: Ichi",ja="捕縄の術:壱",de="Hojo: Ichi",fr="Hojo : Ichi",recast=120},
    [425] = {id=425,en="Hojo: Ni",ja="捕縄の術:弐",de="Hojo: Ni",fr="Hojo : Ni",recast=180},
    [426] = {id=426,en="Hojo: San",ja="捕縄の術:参",de="Hojo: San",fr="Hojo : San",recast=240},
    [427] = {id=427,en="Kurayami: Ichi",ja="暗闇の術:壱",de="Kurayami: Ichi",fr="Kurayami : Ichi",recast=120},
    [428] = {id=428,en="Kurayami: Ni",ja="暗闇の術:弐",de="Kurayami: Ni",fr="Kurayami : Ni",recast=180},
    [429] = {id=429,en="Kurayami: San",ja="暗闇の術:参",de="Kurayami: San",fr="Kurayami : San",recast=240},
    [430] = {id=430,en="Dokumori: Ichi",ja="毒盛の術:壱",de="Dokumori: Ichi",fr="Dokumori : Ichi",recast=120},
    [431] = {id=431,en="Dokumori: Ni",ja="毒盛の術:弐",de="Dokumori: Ni",fr="Dokumori : Ni",recast=180},
    [432] = {id=432,en="Dokumori: San",ja="毒盛の術:参",de="Dokumori: San",fr="Dokumori : San",recast=240},
    [433] = {id=433,en="Tonko: Ichi",ja="遁甲の術:壱",de="Tonko: Ichi",fr="Tonko : Ichi",recast=120},
    [434] = {id=434,en="Tonko: Ni",ja="遁甲の術:弐",de="Tonko: Ni",fr="Tonko : Ni",recast=180},
    [435] = {id=435,en="Tonko: San",ja="遁甲の術:参",de="Tonko: San",fr="Tonko : San",recast=240},
    [436] = {id=436,en="Monomi: Ichi",ja="物見の術:壱",de="Monomi: Ichi",fr="Monomi : Ichi",recast=120},
    [437] = {id=437,en="Aisha: Ichi",ja="哀車の術:壱",de="Aisha: Ichi",fr="Aisha : Ichi",recast=120},
    [438] = {id=438,en="Myoshu: Ichi",ja="妙手の術:壱",de="Myoshu: Ichi",fr="Myoshu : Ichi",recast=120},
    [439] = {id=439,en="Yurin: Ichi",ja="幽林の術:壱",de="Yurin: Ichi",fr="Yurin : Ichi",recast=120},
    [440] = {id=440,en="Kakka: Ichi",ja="活火の術:壱",de="Kakka: Ichi",fr="Kakka : Ichi",recast=120},
    [441] = {id=441,en="Migawari: Ichi",ja="身替の術:壱",de="Migawari: Ichi",fr="Migawari : Ichi",recast=224},
    [445] = {id=445,en="Indi-Regen",ja="インデリジェネ",de="Indi-Regenerieren",fr="Indi-Récup",recast=48},
    [446] = {id=446,en="Indi-Poison",ja="インデポイズン",de="Indi-Gift",fr="Indi-Poison",recast=48},
    [447] = {id=447,en="Indi-Refresh",ja="インデリフレシュ",de="Indi-Erfrischen",fr="Indi-Recharge",recast=48},
    [448] = {id=448,en="magic(771)",ja=".",de=".",fr=".",recast=48},
    [449] = {id=449,en="Indi-STR",ja="インデスト",de="Indi-STR",fr="Indi-STR",recast=48},
    [450] = {id=450,en="Indi-DEX",ja="インデデック",de="Indi-DEX",fr="Indi-DEX",recast=48},
    [451] = {id=451,en="Indi-VIT",ja="インデバイト",de="Indi-VIT",fr="Indi-VIT",recast=48},
    [452] = {id=452,en="Indi-AGI",ja="インデアジル",de="Indi-AGI",fr="Indi-AGI",recast=48},
    [453] = {id=453,en="Indi-INT",ja="インデイン",de="Indi-INT",fr="Indi-INT",recast=48},
    [454] = {id=454,en="Indi-MND",ja="インデマイン",de="Indi-MND",fr="Indi-MND",recast=48},
    [455] = {id=455,en="Indi-CHR",ja="インデカリス",de="Indi-CHR",fr="Indi-CHR",recast=48},
    [456] = {id=456,en="Indi-Fury",ja="インデフューリー",de="Indi-Furor",fr="Indi-Fureur",recast=48},
    [457] = {id=457,en="Indi-Barrier",ja="インデバリア",de="Indi-Barriere",fr="Indi-Défense",recast=48},
    [458] = {id=458,en="Indi-Acumen",ja="インデアキュメン",de="Indi-Esprit",fr="Indi-Sagacité",recast=48},
    [459] = {id=459,en="Indi-Fend",ja="インデフェンド",de="Indi-Fürsorge",fr="Indi-Sagesse",recast=48},
    [460] = {id=460,en="Indi-Precision",ja="インデプレサイス",de="Indi-Akribie",fr="Indi-Habileté",recast=48},
    [461] = {id=461,en="Indi-Voidance",ja="インデヴォイダンス",de="Indi-Reflex",fr="Indi-Dérobade",recast=48},
    [462] = {id=462,en="Indi-Focus",ja="インデフォーカス",de="Indi-Fokus",fr="Indi-Focus",recast=48},
    [463] = {id=463,en="Indi-Attunement",ja="インデアトゥーン",de="Indi-Anpassung",fr="Indi-Harmonie",recast=48},
    [464] = {id=464,en="Indi-Wilt",ja="インデウィルト",de="Indi-Ermüdung",fr="Indi-Faiblesse",recast=48},
    [465] = {id=465,en="Indi-Frailty",ja="インデフレイル",de="Indi-Fragilität",fr="Indi-Fragilité",recast=48},
    [466] = {id=466,en="Indi-Fade",ja="インデフェイド",de="Indi-Schwund",fr="Indi-Déficience",recast=48},
    [467] = {id=467,en="Indi-Malaise",ja="インデマレーズ",de="Indi-Malaise",fr="Indi-Malaise",recast=48},
    [468] = {id=468,en="Indi-Slip",ja="インデスリップ",de="Indi-Sturz",fr="Indi-Maladresse",recast=48},
    [469] = {id=469,en="Indi-Torpor",ja="インデトーパー",de="Indi-Starre",fr="Indi-Torpeur",recast=48},
    [470] = {id=470,en="Indi-Vex",ja="インデヴェックス",de="Indi-Irritation",fr="Indi-Dispersion",recast=48},
    [471] = {id=471,en="Indi-Languor",ja="インデランゴール",de="Indi-Ermattung",fr="Indi-Langueur",recast=48},
    [472] = {id=472,en="Indi-Slow",ja="インデスロウ",de="Indi-Gemach",fr="Indi-Lenteur",recast=48},
    [473] = {id=473,en="Indi-Paralysis",ja="インデパライズ",de="Indi-Paralyse",fr="Indi-Paralysie",recast=48},
    [474] = {id=474,en="Indi-Gravity",ja="インデグラビデ",de="Indi-Schwerkraft",fr="Indi-Pesanteur",recast=48},
    [475] = {id=475,en="Geo-Regen",ja="ジオリジェネ",de="Geo-Regenerieren",fr="Géo-Récup",recast=48},
    [476] = {id=476,en="Geo-Poison",ja="ジオポイズン",de="Geo-Gift",fr="Géo-Poison",recast=48},
    [477] = {id=477,en="Geo-Refresh",ja="ジオリフレシュ",de="Geo-Erfrischen",fr="Géo-Recharge",recast=48},
    [478] = {id=478,en="magic(801)",ja=".",de=".",fr=".",recast=48},
    [479] = {id=479,en="Geo-STR",ja="ジオスト",de="Geo-STR",fr="Géo-STR",recast=48},
    [480] = {id=480,en="Geo-DEX",ja="ジオデック",de="Geo-DEX",fr="Géo-DEX",recast=48},
    [481] = {id=481,en="Geo-VIT",ja="ジオバイト",de="Geo-VIT",fr="Géo-VIT",recast=48},
    [482] = {id=482,en="Geo-AGI",ja="ジオアジル",de="Geo-AGI",fr="Géo-AGI",recast=48},
    [483] = {id=483,en="Geo-INT",ja="ジオイン",de="Geo-INT",fr="Géo-INT",recast=48},
    [484] = {id=484,en="Geo-MND",ja="ジオマイン",de="Geo-MND",fr="Géo-MND",recast=48},
    [485] = {id=485,en="Geo-CHR",ja="ジオカリス",de="Geo-CHR",fr="Géo-CHR",recast=48},
    [486] = {id=486,en="Geo-Fury",ja="ジオフューリー",de="Geo-Furor",fr="Géo-Fureur",recast=48},
    [487] = {id=487,en="Geo-Barrier",ja="ジオバリア",de="Geo-Barriere",fr="Géo-Défense",recast=48},
    [488] = {id=488,en="Geo-Acumen",ja="ジオアキュメン",de="Geo-Esprit",fr="Géo-Sagacité",recast=48},
    [489] = {id=489,en="Geo-Fend",ja="ジオフェンド",de="Geo-Fürsorge",fr="Géo-Sagesse",recast=48},
    [490] = {id=490,en="Geo-Precision",ja="ジオプレサイス",de="Geo-Akribie",fr="Géo-Habileté",recast=48},
    [491] = {id=491,en="Geo-Voidance",ja="ジオヴォイダンス",de="Geo-Reflex",fr="Géo-Dérobade",recast=48},
    [492] = {id=492,en="Geo-Focus",ja="ジオフォーカス",de="Geo-Fokus",fr="Géo-Focus",recast=48},
    [493] = {id=493,en="Geo-Attunement",ja="ジオアトゥーン",de="Geo-Anpassung",fr="Géo-Harmonie",recast=48},
    [494] = {id=494,en="Geo-Wilt",ja="ジオウィルト",de="Geo-Ermüdung",fr="Géo-Faiblesse",recast=48},
    [495] = {id=495,en="Geo-Frailty",ja="ジオフレイル",de="Geo-Fragilität",fr="Géo-Fragilité",recast=48},
    [496] = {id=496,en="Geo-Fade",ja="ジオフェイド",de="Geo-Schwund",fr="Géo-Déficience",recast=48},
    [497] = {id=497,en="Geo-Malaise",ja="ジオマレーズ",de="Geo-Malaise",fr="Géo-Malaise",recast=48},
    [498] = {id=498,en="Geo-Slip",ja="ジオスリップ",de="Geo-Sturz",fr="Géo-Maladresse",recast=48},
    [499] = {id=499,en="Geo-Torpor",ja="ジオトーパー",de="Geo-Starre",fr="Géo-Torpeur",recast=48},
    [500] = {id=500,en="Geo-Vex",ja="ジオヴェックス",de="Geo-Irritation",fr="Géo-Dispersion",recast=48},
    [501] = {id=501,en="Geo-Languor",ja="ジオランゴール",de="Geo-Ermattung",fr="Géo-Langueur",recast=48},
    [502] = {id=502,en="Geo-Slow",ja="ジオスロウ",de="Geo-Gemach",fr="Géo-Lenteur",recast=48},
    [503] = {id=503,en="Geo-Paralysis",ja="ジオパライズ",de="Geo-Paralyse",fr="Géo-Paralysie",recast=48},
    [504] = {id=504,en="Geo-Gravity",ja="ジオグラビデ",de="Geo-Schwerkraft",fr="Géo-Pesanteur",recast=48},
    [512] = {id=512,en="Foot Kick",ja="フットキック",de="Fußtritt",fr="Coup de patte",recast=26},
    [513] = {id=513,en="Power Attack",ja="パワーアタック",de="Kraft-Attacke",fr="Attaque en force",recast=29},
    [514] = {id=514,en="Sprout Smack",ja="スプラウトスマック",de="Sprossenklatsche",fr="Germe gifleur",recast=29},
    [515] = {id=515,en="Wild Oats",ja="種まき",de="Wilder Hafer",fr="Germination",recast=29},
    [516] = {id=516,en="Queasyshroom",ja="マヨイタケ",de="Übelpilz",fr="Champi-nausée",recast=60},
    [517] = {id=517,en="Battle Dance",ja="バトルダンス",de="Kriegstanz",fr="Danse de combat",recast=40},
    [518] = {id=518,en="Head Butt",ja="ヘッドバット",de="Kopfnuss",fr="Coup de tête",recast=40},
    [519] = {id=519,en="Feather Storm",ja="羽根吹雪",de="Federsturm",fr="Déluge de plumes",recast=40},
    [520] = {id=520,en="Helldive",ja="ヘルダイブ",de="Höllentaucher",fr="Plongée en enfer",recast=45},
    [521] = {id=521,en="Bludgeon",ja="メッタ打ち",de="Knüppel",fr="Matraque",recast=47},
    [522] = {id=522,en="Claw Cyclone",ja="クローサイクロン",de="Klauenwirbel",fr="Cyclone griffu",recast=79},
    [523] = {id=523,en="Screwdriver",ja="S.ドライバー",de="Schraubenzieher",fr="Tournevis",recast=56},
    [524] = {id=524,en="Grand Slam",ja="グランドスラム",de="Grand Slam",fr="Grande claque",recast=57},
    [525] = {id=525,en="Smite of Rage",ja="怒りの一撃",de="Schlag des Zorns",fr="Coup de rage",recast=52},
    [526] = {id=526,en="Pinecone Bomb",ja="まつぼっくり爆弾",de="Kienappel-Bombe",fr="Bombe conifère",recast=106},
    [528] = {id=528,en="Jet Stream",ja="ジェットストリーム",de="Düsenstrahl",fr="Jet-stream",recast=92},
    [529] = {id=529,en="Uppercut",ja="アッパーカット",de="Uppercut",fr="Uppercut",recast=71},
    [530] = {id=530,en="Terror Touch",ja="テラータッチ",de="Terrorberührung",fr="Toucher de terreur",recast=84},
    [531] = {id=531,en="Mandibular Bite",ja="M.バイト",de="Mandibeln-Biss",fr="Mandibule",recast=77},
    [532] = {id=532,en="Sickle Slash",ja="シックルスラッシュ",de="Sichelhieb",fr="Entaille de faucille",recast=81},
    [533] = {id=533,en="Death Scissors",ja="デスシザース",de="Todesscheren",fr="Ciseaux mortels",recast=98},
    [534] = {id=534,en="Dimensional Death",ja="次元殺",de="Dimensionaler Fluch",fr="Distorsion fatale",recast=95},
    [535] = {id=535,en="Spiral Spin",ja="スパイラルスピン",de="Spiral-Angriff",fr="Vrille tournoyante",recast=180},
    [536] = {id=536,en="Seedspray",ja="シードスプレー",de="Sporenspray",fr="Crachat de graines",recast=144},
    [537] = {id=537,en="Body Slam",ja="ボディプレス",de="Bodyslam",fr="Charge physique",recast=111},
    [538] = {id=538,en="Spinal Cleave",ja="スパイナルクリーブ",de="Gratspalter",fr="Taillade spinale",recast=114},
    [539] = {id=539,en="Frenetic Rip",ja="F.リップ",de="Frenetischer Riss",fr="Griffes effrénées",recast=114},
    [540] = {id=540,en="Frypan",ja="フライパン",de="Bratpfanne",fr="Poêle à frire",recast=104},
    [541] = {id=541,en="Hydro Shot",ja="ハイドロショット",de="Hydro-Schuss",fr="Hydro-coup",recast=104},
    [542] = {id=542,en="Tail Slap",ja="テールスラップ",de="Schweifklapser",fr="Gifle caudale",recast=114},
    [543] = {id=543,en="Hysteric Barrage",ja="H.バラージ",de="Hysterische Sperre",fr="Assaut hystérique",recast=114},
    [544] = {id=544,en="Cannonball",ja="キャノンボール",de="Kanonenkugel",fr="Canon",recast=114},
    [545] = {id=545,en="Asuran Claws",ja="アシュラクロー",de="Asura-Klauen",fr="Griffes d'Asura",recast=240},
    [546] = {id=546,en="Disseverment",ja="ディセバーメント",de="Abtrennung",fr="Ecartèlement",recast=131},
    [547] = {id=547,en="Sub-zero Smash",ja="サブゼロスマッシュ",de="Unter-Null-Schlag",fr="Cryo-impact",recast=131},
    [548] = {id=548,en="Ram Charge",ja="ラムチャージ",de="Widderangriff",fr="Coup du bélier",recast=139},
    [549] = {id=549,en="Vertical Cleave",ja="バーチカルクリーヴ",de="Vertikale Zerteilung",fr="Fente verticale",recast=149},
    [550] = {id=550,en="Final Sting",ja="ファイナルスピア",de="Letzter Stich",fr="Dernier dard",recast=44},
    [551] = {id=551,en="Goblin Rush",ja="ゴブリンラッシュ",de="Goblin-Rausch",fr="Charge du Goblin",recast=102},
    [552] = {id=552,en="Vanity Dive",ja="バニティダイブ",de="Eitelk.-Abtauch.",fr="Plongée vanités",recast=169},
    [553] = {id=553,en="Whirl of Rage",ja="怒りの旋風",de="Wirbel d. Zorns",fr="Tourbillon fureur",recast=124},
    [554] = {id=554,en="Benthic Typhoon",ja="ベンシクタイフーン",de="Benth. Taifun",fr="Typh. benthique",recast=192},
    [555] = {id=555,en="Quad. Continuum",ja="四連突",de="Quadr. Kont.",fr="Continuum quad.",recast=127},
    [556] = {id=556,en="Empty Thrash",ja="エンプティスラッシュ",de="Leere Prügel",fr="Rossée du néant",recast=163},
    [557] = {id=557,en="Delta Thrust",ja="デルタスラスト",de="Delta-Stich",fr="Morsure triang.",recast=60},
    [558] = {id=558,en="Heavy Strike",ja="重い一撃",de="Schwerer Schlag",fr="Frappe lourde",recast=112},
    [559] = {id=559,en="Sudden Lunge",ja="サドンランジ",de="Plötzlicher Satz",fr="Piqué brutal",recast=60},
    [560] = {id=560,en="Quadrastrike",ja="クアドラストライク",de="Vierfach-Schlag",fr="Quadra-frappe",recast=170},
    [561] = {id=561,en="Amorphic Spikes",ja="槍玉",de="Amorphe Stacheln",fr="Point. amorphes",recast=233},
    [562] = {id=562,en="Barbed Crescent",ja="偃月刃",de="Stachel-Halbmond",fr="Croissant barbelé",recast=88},
    [563] = {id=563,en="Paralyzing Triad",ja="パラライズトライアド",de="Lähmende Triade",fr="Triade paralys.",recast=60},
    [564] = {id=564,en="Glutinous Dart",ja="グルーティナスダート",de="Klebriger Pfeil",fr="Dard glutineux",recast=24},
    [591] = {id=591,en="Blastbomb",ja="炸裂弾",de="Druckwellen-Bombe",fr="Obus",recast=60},
    [592] = {id=592,en="Bomb Toss",ja="爆弾投げ",de="Bombenwurf",fr="Lancer de bombe",recast=98},
    [593] = {id=593,en="Sound Blast",ja="サウンドブラスト",de="Schallstoß",fr="Rafale de son",recast=120},
    [594] = {id=594,en="Self-Destruct",ja="自爆",de="Selbstzerstörung",fr="Auto-destruction",recast=84},
    [595] = {id=595,en="Firespit",ja="ファイアースピット",de="Feuerspucke",fr="Crachat embrasé",recast=171},
    [596] = {id=596,en="Lowing",ja="ロウイン",de="Erniedrigung",fr="Beuglement",recast=224},
    [597] = {id=597,en="Heat Breath",ja="火炎の息",de="Hitzeatem",fr="Souffle chaud",recast=196},
    [598] = {id=598,en="Triumphant Roar",ja="共鳴",de="Triumphgeheul",fr="Résonance",recast=104},
    [599] = {id=599,en="Exuviation",ja="イグジュビエーション",de="Exuviation",fr="Exuviation",recast=240},
    [600] = {id=600,en="Blazing Bound",ja="ブレーズバウンド",de="Lodernder Bann",fr="Plongeon ardent",recast=180},
    [601] = {id=601,en="Fantod",ja="ファンタッド",de="Fantod",fr="Accès de rage",recast=40},
    [602] = {id=602,en="Thermal Pulse",ja="サーマルパルス",de="Thermischer Puls",fr="Pulsat. thermique",recast=32},
    [603] = {id=603,en="O. Counterstance",ja="カウンタースタンス",de="Gegenschlag",fr="Qui-vive orque",recast=44},
    [604] = {id=604,en="Nat. Meditation",ja="N.メディテイト",de="Stille der Natur",fr="Méditation nat.",recast=240},
    [606] = {id=606,en="Ice Break",ja="アイスブレイク",de="Eis-Brecher",fr="Rupture de glace",recast=135},
    [607] = {id=607,en="Cold Wave",ja="コールドウェーブ",de="Kältewelle",fr="Vague de froid",recast=240},
    [608] = {id=608,en="Memento Mori",ja="メメントモーリ",de="Memento Mori",fr="Memento Mori",recast=224},
    [609] = {id=609,en="Infrasonics",ja="超低周波",de="Infraschall",fr="Infrasonique",recast=240},
    [610] = {id=610,en="Frost Breath",ja="フロストブレス",de="Frostatem",fr="Souffle de glace",recast=171},
    [611] = {id=611,en="Reactor Cool",ja="反応炉冷却",de="Reaktorkühler",fr="Cryoréacteur",recast=240},
    [616] = {id=616,en="Healing Breeze",ja="いやしの風",de="Heilbrise",fr="Brise curative",recast=60},
    [617] = {id=617,en="Chaotic Eye",ja="カオティックアイ",de="Chaosauge",fr="Œil de chaos",recast=40},
    [618] = {id=618,en="Mysterious Light",ja="神秘の光",de="Mysteriöses Licht",fr="Eclat mystérieux",recast=98},
    [619] = {id=619,en="Stinking Gas",ja="スティンキングガス",de="Stinkgas",fr="Gaz puant",recast=240},
    [620] = {id=620,en="Refueling",ja="リフュエリング",de="Auftanken",fr="Ravitaillement",recast=120},
    [621] = {id=621,en="Frightful Roar",ja="フライトフルロア",de="Grausames Gebrüll",fr="Grogne effroyable",recast=80},
    [622] = {id=622,en="Hecatomb Wave",ja="ヘカトンウェーブ",de="Hecatomb-Welle",fr="Vague hécatombe",recast=135},
    [623] = {id=623,en="Feather Barrier",ja="フェザーバリア",de="Federbarriere",fr="Barrière de plumes",recast=224},
    [624] = {id=624,en="Flying Hip Press",ja="F.ヒッププレス",de="Sturm-Hüftpresse",fr="Prise aérienne",recast=138},
    [625] = {id=625,en="Feather Tickle",ja="フェザーティックル",de="Federkribbeln",fr="Chatouillement",recast=104},
    [626] = {id=626,en="Voracious Trunk",ja="吸印",de="Gieriger Rüssel",fr="Trompe vorace",recast=224},
    [627] = {id=627,en="Zephyr Mantle",ja="ゼファーマント",de="Zephyr-Mantel",fr="Mante de zéphyr",recast=240},
    [628] = {id=628,en="Leafstorm",ja="リーフストーム",de="Blättersturm",fr="Tempête feuilles",recast=4},
    [629] = {id=629,en="Animating Wail",ja="鯨波",de="Lebensklage",fr="Plainte encourag.",recast=180},
    [630] = {id=630,en="Auroral Drape",ja="オーロラルドレープ",de="Dämmervorh.",fr="Drapé auroral",recast=240},
    [631] = {id=631,en="Occultation",ja="オカルテーション",de="Okkultation",fr="Occultation",recast=104},
    [632] = {id=632,en="Reaving Wind",ja="リービンウィンド",de="Plünderschwinge",fr="Vent saccageur",recast=104},
    [633] = {id=633,en="White Wind",ja="ホワイトウィンド",de="Weißer Wind",fr="Vent blanc",recast=90},
    [634] = {id=634,en="Wind Breath",ja="ウィンドブレス",de="Windatem",fr="Souffle de vent",recast=118},
    [635] = {id=635,en="Tem. Upheaval",ja="T.アップヒーヴ",de="Stürm. Emporschn.",fr="Battement temp.",recast=48},
    [636] = {id=636,en="Sandspin",ja="土竜巻",de="Sandkreisel",fr="Trombe de sable",recast=39},
    [637] = {id=637,en="Metallic Body",ja="メタルボディ",de="Metallkörper",fr="Corps métallique",recast=240},
    [638] = {id=638,en="Cocoon",ja="コクーン",de="Kokon",fr="Cocon",recast=240},
    [639] = {id=639,en="Magnetite Cloud",ja="磁鉄粉",de="Magnetit-Wolke",fr="Nuage magnétique",recast=117},
    [640] = {id=640,en="Filamented Hold",ja="F.ホールド",de="Fadenhalt",fr="Prise filandreuse",recast=80},
    [641] = {id=641,en="Bad Breath",ja="臭い息",de="Schlechter Atem",fr="Mauvaise haleine",recast=224},
    [642] = {id=642,en="Diamondhide",ja="金剛身",de="Diamantenhaut",fr="Peau de diamant",recast=104},
    [643] = {id=643,en="Warm-Up",ja="ワームアップ",de="Aufwärmen",fr="Echauffement",recast=224},
    [644] = {id=644,en="Cimicine Discharge",ja="C.ディスチャージ",de="Stinkendes Sekret",fr="Transs. polluante",recast=80},
    [645] = {id=645,en="Barrier Tusk",ja="牙門",de="Stoßzahnbarriere",fr="Défenses protec.",recast=240},
    [646] = {id=646,en="Embalming Earth",ja="エンバームアース",de="Erdgrab",fr="Terre embaum.",recast=96},
    [651] = {id=651,en="Blitzstrahl",ja="B.シュトラール",de="Blitzstrahl",fr="Blitzstrahl",recast=117},
    [652] = {id=652,en="Temporal Shift",ja="テンポラルシフト",de="Zeitverschiebung",fr="Décalage temporel",recast=224},
    [653] = {id=653,en="Mind Blast",ja="マインドブラスト",de="Gedankenpresse",fr="Explosion mentale",recast=120},
    [654] = {id=654,en="Plasma Charge",ja="プラズマチャージ",de="Plasma-Entladung",fr="Charge de plasma",recast=240},
    [655] = {id=655,en="Charged Whisker",ja="チャージドホイスカー",de="Gelad. Schnurrhaar",fr="Poil survolté",recast=92},
    [656] = {id=656,en="Thunder Breath",ja="サンダーブレス",de="Donneratem",fr="Souffle foudroyant",recast=192},
    [661] = {id=661,en="Cursed Sphere",ja="カースドスフィア",de="Fluchkugel",fr="Sphère de maléfice",recast=78},
    [662] = {id=662,en="Poison Breath",ja="ポイズンブレス",de="Giftatem",fr="Haleine souillée",recast=78},
    [663] = {id=663,en="Venom Shell",ja="ベノムシェル",de="Gifthülle",fr="Conque de venin",recast=180},
    [664] = {id=664,en="Awful Eye",ja="アーフルアイ",de="Furchtbares Auge",fr="Œil damné",recast=240},
    [665] = {id=665,en="Maelstrom",ja="メイルシュトロム",de="Maelstrom",fr="Maëlstrom",recast=156},
    [666] = {id=666,en="Corrosive Ooze",ja="コローシブウーズ",de="Säureschleim",fr="Mucus corrosif",recast=120},
    [667] = {id=667,en="Regurgitation",ja="リガージテーション",de="Erbrechen",fr="Régurgitation",recast=98},
    [668] = {id=668,en="Amplification",ja="ねたみ種",de="Verstärkerfeld",fr="Amplification",recast=224},
    [669] = {id=669,en="Acrid Stream",ja="アクリッドストリーム",de="Beißender Strom",fr="Projection âcre",recast=92},
    [670] = {id=670,en="Demoralizing Roar",ja="D.ロア",de="Demoral. Gebrüll",fr="Rug. démoralisant",recast=100},
    [671] = {id=671,en="Water Bomb",ja="水風船爆弾",de="Wasserbombe",fr="Bombe à eau",recast=129},
    [672] = {id=672,en="Vapor Spray",ja="ヴェイパースプレー",de="Dampfspray",fr="Spray de vapeur",recast=76},
    [673] = {id=673,en="Rending Deluge",ja="R.デルージュ",de="Zerr. Wasserstoß",fr="Déluge déchir.",recast=140},
    [674] = {id=674,en="Foul Waters",ja="ファウルウォーター",de="Brackwasser",fr="Eaux usées",recast=240},
    [676] = {id=676,en="Pollen",ja="花粉",de="Pollen",fr="Pollen",recast=20},
    [677] = {id=677,en="Sheep Song",ja="シープソング",de="Schaflied",fr="Chant ovin",recast=240},
    [678] = {id=678,en="Wild Carrot",ja="ワイルドカロット",de="Wilde Möhre",fr="Carotte sauvage",recast=24},
    [679] = {id=679,en="Blank Gaze",ja="ブランクゲイズ",de="Leerer Blick",fr="Regard vide",recast=40},
    [680] = {id=680,en="Radiant Breath",ja="R.ブレス",de="Strahlenatem",fr="Souffle radiant",recast=135},
    [681] = {id=681,en="Magic Fruit",ja="マジックフルーツ",de="Magische Frucht",fr="Fruit magique",recast=24},
    [682] = {id=682,en="Light of Penance",ja="贖罪の光",de="Licht der Buße",fr="Lumière pénitence",recast=240},
    [683] = {id=683,en="1000 Needles",ja="針千本",de="1000 Nadeln",fr="1000 épines",recast=224},
    [684] = {id=684,en="Yawn",ja="ヤーン",de="Gähn",fr="Bâillement",recast=240},
    [685] = {id=685,en="Saline Coat",ja="セイリーンコート",de="Salzmantel",fr="Manteau salin",recast=240},
    [686] = {id=686,en="Actinic Burst",ja="A.バースト",de="Strahlungsausbruch",fr="Eclat actinique",recast=240},
    [687] = {id=687,en="Magic Hammer",ja="マジックハンマー",de="Magischer Hammer",fr="Marteau magique",recast=208},
    [688] = {id=688,en="Plenilune Embrace",ja="P.エンブレイス",de="Mondsucht",fr="Onction pleine lune",recast=48},
    [689] = {id=689,en="Regeneration",ja="リジェネレーション",de="Regenerierung",fr="Régénération",recast=240},
    [690] = {id=690,en="Battery Charge",ja="バッテリーチャージ",de="Batterieladung",fr="Rechargement",recast=44},
    [691] = {id=691,en="Winds of Promy.",ja="虚無の風",de="Promyvion-Winde",fr="Vents Promyvion",recast=70},
    [692] = {id=692,en="Retinal Glare",ja="レテナグレア",de="Auge des Zorns",fr="Regard rétinien",recast=180},
    [696] = {id=696,en="Blood Drain",ja="吸血",de="Blutsauger",fr="Suceur de sang",recast=104},
    [697] = {id=697,en="Soporific",ja="サペリフィック",de="Einschläfern",fr="Somnifère",recast=104},
    [698] = {id=698,en="Death Ray",ja="デスレイ",de="Todesstrahl",fr="Rayon de la mort",recast=117},
    [699] = {id=699,en="Digest",ja="消化",de="Extrakt",fr="Digestion",recast=104},
    [700] = {id=700,en="MP Drainkiss",ja="MP吸収キッス",de="MP-Vampirkuss",fr="Succion de MP",recast=104},
    [701] = {id=701,en="Geist Wall",ja="ガイストウォール",de="Geisterwand",fr="Mur Geist",recast=120},
    [702] = {id=702,en="Blood Saber",ja="ブラッドセイバー",de="Blutsäbel",fr="Sabre ensanglanté",recast=104},
    [703] = {id=703,en="Jettatura",ja="ジェタチュラ",de="Jettatura",fr="Jettatura",recast=224},
    [704] = {id=704,en="Eyes On Me",ja="アイズオンミー",de="Augen auf mich",fr="Eyes On Me",recast=117},
    [705] = {id=705,en="Sandspray",ja="サンドスプレー",de="Sandsprüher",fr="Aspersion de sable",recast=104},
    [706] = {id=706,en="Enervation",ja="吶喊",de="Entkräftung",fr="Amollissement",recast=240},
    [707] = {id=707,en="Magic Barrier",ja="マジックバリア",de="Mag. Barriere",fr="Barrière magique",recast=240},
    [708] = {id=708,en="Osmosis",ja="オスモーシス",de="Seelensog",fr="Osmose",recast=224},
    [709] = {id=709,en="Dream Flower",ja="夢想花",de="Traumblume",fr="Fleur de rêves",recast=180},
    [710] = {id=710,en="Evryone. Grudge",ja="みんなの怨み",de="Keine Widerrede",fr="Rancune collect.",recast=74},
    [711] = {id=711,en="Mortal Ray",ja="モータルレイ",de="Tödlicher Strahl",fr="Rayon mortel",recast=88},
    [712] = {id=712,en="Dark Orb",ja="ダークオーブ",de="Dunkle Sphäre",fr="Orbe noir",recast=32},
    [736] = {id=736,en="Tourbillion",ja="トゥールビヨン",de="Tourbillion",fr="Tourbillon",recast=120},
    [737] = {id=737,en="Bilgestorm",ja="ビルジストーム",de="Bilgensturm",fr="Déluge putride",recast=120},
    [738] = {id=738,en="Bloodrake",ja="ブラッドレイク",de="Blutharke",fr="Succion sang",recast=120},
    [742] = {id=742,en="Gates of Hades",ja="ゲーツオブハデス",de="Tor des Hades",fr="Portes d'Hadès",recast=120},
    [744] = {id=744,en="Carcharian Verve",ja="カルカリアンヴァーヴ",de="Carchar.-Schwung",fr="Verve carchar.",recast=120},
    [746] = {id=746,en="Droning Whirlwind",ja="D.ワールウィンド",de="Surrender Sturm",fr="Tourbillon bourd.",recast=120},
    [748] = {id=748,en="Harden Shell",ja="甲羅強化",de="Harte Schale",fr="Durcis. coquille",recast=120},
    [750] = {id=750,en="Thunderbolt",ja="サンダーボルト",de="Donnerkeil",fr="Traits de foudre",recast=120},
    [752] = {id=752,en="Pyric Bulwark",ja="パイリックブルワーク",de="Hitzebollwerk",fr="Remp. pyrogène",recast=120},
    [754] = {id=754,en="Absolute Terror",ja="アブソルートテラー",de="Absoluter Terror",fr="Terreur absolue",recast=120},
    [755] = {id=755,en="Blistering Roar",ja="ブリスターローア",de="Brennendes Brüllen",fr="Rugissement tor.",recast=120},
    [768] = {id=768,en="Foe Requiem",ja="魔物のレクイエム",de="Feindesrequiem",fr="Requiem ennemi",recast=96},
    [769] = {id=769,en="Foe Requiem II",ja="魔物のレクイエムII",de="Feindesrequiem II",fr="Requiem ennemi II",recast=96},
    [770] = {id=770,en="Foe Requiem III",ja="魔物のレクイエムIII",de="Feindesrequiem III",fr="Requiem ennemi III",recast=96},
    [771] = {id=771,en="Foe Requiem IV",ja="魔物のレクイエムIV",de="Feindesrequiem IV",fr="Requiem ennemi IV",recast=96},
    [772] = {id=772,en="Foe Requiem V",ja="魔物のレクイエムV",de="Feindesrequiem V",fr="Requiem ennemi V",recast=96},
    [773] = {id=773,en="Foe Requiem VI",ja="魔物のレクイエムVI",de="Feindesrequiem VI",fr="Requiem ennemi VI",recast=96},
    [774] = {id=774,en="Foe Requiem VII",ja="魔物のレクイエムVII",de="Feindesrequiem VII",fr="Requ. ennemi VII",recast=96},
    [775] = {id=775,en="Foe Requiem VIII",ja="魔物のレクイエムVIII",de="Feindesrequiem VIII",fr="Requ. ennemi VIII",recast=96},
    [776] = {id=776,en="Foe Lullaby",ja="魔物のララバイ",de="Feind.-Wiegenlied",fr="Berceuse hostile",recast=96},
    [777] = {id=777,en="Foe Lullaby II",ja="魔物のララバイII",de="Feind.-Wiegenl. II",fr="Berc. hostile II",recast=96},
    [778] = {id=778,en="Horde Lullaby",ja="魔物達のララバイ",de="Wiegenl. d. Horde",fr="Berceuse du clan",recast=96},
    [779] = {id=779,en="Horde Lullaby II",ja="魔物達のララバイII",de="Wiegenl. d. Horde II",fr="Berc. du clan II",recast=96},
    [780] = {id=780,en="Army's Paeon",ja="戦士達のピーアン",de="Armee-Paeon",fr="Péan martial",recast=96},
    [781] = {id=781,en="Army's Paeon II",ja="戦士達のピーアンII",de="Armee-Paeon II",fr="Péan martial II",recast=96},
    [782] = {id=782,en="Army's Paeon III",ja="戦士達のピーアンIII",de="Armee-Paeon III",fr="Péan martial III",recast=96},
    [783] = {id=783,en="Army's Paeon IV",ja="戦士達のピーアンIV",de="Armee-Paeon IV",fr="Péan martial IV",recast=96},
    [784] = {id=784,en="Army's Paeon V",ja="戦士達のピーアンV",de="Armee-Paeon V",fr="Péan martial V",recast=96},
    [785] = {id=785,en="Army's Paeon VI",ja="戦士達のピーアンVI",de="Armee-Paeon VI",fr="Péan martial VI",recast=96},
    [786] = {id=786,en="Army's Paeon VII",ja="戦士達のピーアンVII",de="Armee-Paeon VII",fr="Péan martial VII",recast=96},
    [787] = {id=787,en="Army's Paeon VIII",ja="戦士達のピーアンVIII",de="Armee-Paeon VIII",fr="Péan martial VIII",recast=96},
    [788] = {id=788,en="Mage's Ballad",ja="魔道士のバラード",de="Magier-Ballade",fr="Ballade du mage",recast=96},
    [789] = {id=789,en="Mage's Ballad II",ja="魔道士のバラードII",de="Magier-Ballade II",fr="Ball. du mage II",recast=96},
    [790] = {id=790,en="Mage's Ballad III",ja="魔道士のバラードIII",de="Magier-Ballade III",fr="Ball. du mage III",recast=96},
    [791] = {id=791,en="Knight's Minne",ja="重装騎兵のミンネ",de="Ritter-Minne",fr="Lied du chevalier",recast=96},
    [792] = {id=792,en="Knight's Minne II",ja="重装騎兵のミンネII",de="Ritter-Minne II",fr="Lied du chev. II",recast=96},
    [793] = {id=793,en="Knight's Minne III",ja="重装騎兵のミンネIII",de="Ritter-Minne III",fr="Lied du chev. III",recast=96},
    [794] = {id=794,en="Knight's Minne IV",ja="重装騎兵のミンネIV",de="Ritter-Minne IV",fr="Lied du chev. IV",recast=96},
    [795] = {id=795,en="Knight's Minne V",ja="重装騎兵のミンネV",de="Ritter-Minne V",fr="Lied du chev. V",recast=96},
    [796] = {id=796,en="Valor Minuet",ja="猛者のメヌエット",de="Mut-Menuett",fr="Menuet vaillant",recast=96},
    [797] = {id=797,en="Valor Minuet II",ja="猛者のメヌエットII",de="Mut-Menuett II",fr="Menuet vaillant II",recast=96},
    [798] = {id=798,en="Valor Minuet III",ja="猛者のメヌエットIII",de="Mut-Menuett III",fr="Menuet vaillant III",recast=96},
    [799] = {id=799,en="Valor Minuet IV",ja="猛者のメヌエットIV",de="Mut-Menuett IV",fr="Menuet vaillant IV",recast=96},
    [800] = {id=800,en="Valor Minuet V",ja="猛者のメヌエットV",de="Mut-Menuett V",fr="Menuet vaillant V",recast=96},
    [801] = {id=801,en="Sword Madrigal",ja="剣闘士のマドリガル",de="Schwert-Madrigal",fr="Madrigal épéiste",recast=96},
    [802] = {id=802,en="Blade Madrigal",ja="剣豪のマドリガル",de="Klingen-Madrigal",fr="Madrigal du duel",recast=96},
    [803] = {id=803,en="Hunter's Prelude",ja="狩人のプレリュード",de="Jäger-Prolog",fr="Prélude chasseur",recast=96},
    [804] = {id=804,en="Archer's Prelude",ja="弓師のプレリュード",de="Schützen-Prolog",fr="Prélude archer",recast=96},
    [805] = {id=805,en="Sheepfoe Mambo",ja="闘羊士のマンボ",de="Schaf-Mambo",fr="Mambo du berger",recast=96},
    [806] = {id=806,en="Dragonfoe Mambo",ja="闘龍士のマンボ",de="Drachen-Mambo",fr="Mambo du dragon",recast=96},
    [807] = {id=807,en="Fowl Aubade",ja="鶏のオーバード",de="Perlhuhn-Aubade",fr="Aubade des ailes",recast=96},
    [808] = {id=808,en="Herb Pastoral",ja="薬草のパストラル",de="Kräuter-Psalm",fr="Past. des simples",recast=96},
    [809] = {id=809,en="Chocobo Hum",ja="チョコボのハミング",de="Chocobo-Summen",fr="Chant chocobo",recast=96},
    [810] = {id=810,en="Shining Fantasia",ja="光明のファンタジア",de="Glanzfantasia",fr="Fantaisie brillante",recast=96},
    [811] = {id=811,en="Scop's Operetta",ja="小話のオペレッタ",de="Scop-Operette",fr="Opérette du barde",recast=96},
    [812] = {id=812,en="Puppet's Operetta",ja="腹話のオペレッタ",de="Puppen-Operette",fr="Opérette du pantin",recast=96},
    [813] = {id=813,en="Jester's Operetta",ja="道化のオペレッタ",de="Narren-Operette",fr="Opér. du bouffon",recast=96},
    [814] = {id=814,en="Gold Capriccio",ja="黄金のカプリチオ",de="Gold-Capriccio",fr="Capriccio d'or",recast=96},
    [815] = {id=815,en="Devotee Serenade",ja="献身のセレナーデ",de="Jünger-Serenade",fr="Sérén. fervente",recast=96},
    [816] = {id=816,en="Warding Round",ja="破邪のロンド",de="Antifluch-Rondo",fr="Rondo du gardien",recast=96},
    [817] = {id=817,en="Goblin Gavotte",ja="ゴブリンのガボット",de="Goblin-Gavotte",fr="Gavotte gobline",recast=96},
    [818] = {id=818,en="Cactuar Fugue",ja="サボテンダーフーガ",de="Cactuar-Fuge",fr="Fugue du cactuar",recast=96},
    [819] = {id=819,en="Moogle Rhapsody",ja="モーグリのラプソディ",de="Moogle-Rhapsodie",fr="Rhapsodie moogle",recast=96},
    [820] = {id=820,en="Protected Aria",ja="冷静と情熱のアリア",de="Arie des Schutzes",fr="Aria de protection",recast=96},
    [821] = {id=821,en="Advancing March",ja="無敵の進撃マーチ",de="Fortschritts-Marsch",fr="Marche d'entrain",recast=96},
    [822] = {id=822,en="Victory March",ja="栄光の凱旋マーチ",de="Sieges-Marsch",fr="Marche glorieuse",recast=96},
    [823] = {id=823,en="(magic 511)",ja="(予備)",de="a line help text",fr=".",recast=96},
    [824] = {id=824,en="Battlefield Elegy",ja="戦場のエレジー",de="Schlachtfeld-Elegie",fr="Elégie du combat",recast=96},
    [825] = {id=825,en="Carnage Elegy",ja="修羅のエレジー",de="Gemetzel-Elegie",fr="Elégie du carnage",recast=96},
    [826] = {id=826,en="Massacre Elegy",ja="地獄のエレジー",de="Höllen-Elegie",fr="Elég. du massacre",recast=96},
    [827] = {id=827,en="Sinewy Etude",ja="剛力のエチュード",de="Sehnige Etüde",fr="Etude inflexible",recast=96},
    [828] = {id=828,en="Dextrous Etude",ja="器用のエチュード",de="Geschickte Etüde",fr="Etude agile",recast=96},
    [829] = {id=829,en="Vivacious Etude",ja="元気のエチュード",de="Lebhafte Etüde",fr="Etude vivace",recast=96},
    [830] = {id=830,en="Quick Etude",ja="機敏のエチュード",de="Schnelle Etüde",fr="Etude prompte",recast=96},
    [831] = {id=831,en="Learned Etude",ja="知恵のエチュード",de="Lehrreiche Etüde",fr="Etude savante",recast=96},
    [832] = {id=832,en="Spirited Etude",ja="精神のエチュード",de="Feurige Etüde",fr="Etude spirituelle",recast=96},
    [833] = {id=833,en="Enchanting Etude",ja="魅了のエチュード",de="Verzaub. Etüde",fr="Etude enchantée",recast=96},
    [834] = {id=834,en="Herculean Etude",ja="怪力のエチュード",de="Herkules-Etüde",fr="Etude herculéenne",recast=96},
    [835] = {id=835,en="Uncanny Etude",ja="妙技のエチュード",de="Unheiml. Etüde",fr="Etude habile",recast=96},
    [836] = {id=836,en="Vital Etude",ja="活力のエチュード",de="Lebendige Etüde",fr="Etude vitale",recast=96},
    [837] = {id=837,en="Swift Etude",ja="俊敏のエチュード",de="Flinke Etüde",fr="Etude rapide",recast=96},
    [838] = {id=838,en="Sage Etude",ja="英知のエチュード",de="Kluge Etüde",fr="Etude sage",recast=96},
    [839] = {id=839,en="Logical Etude",ja="理力のエチュード",de="Logische Etüde",fr="Etude logique",recast=96},
    [840] = {id=840,en="Bewitching Etude",ja="魅惑のエチュード",de="Verhexende Etüde",fr="Et. ensorcelante",recast=96},
    [841] = {id=841,en="Fire Carol",ja="耐火カロル第一楽章",de="Feuer-Gesang",fr="Cantique de feu",recast=96},
    [842] = {id=842,en="Ice Carol",ja="耐寒カロル第一楽章",de="Eis-Gesang",fr="Cantique de glace",recast=96},
    [843] = {id=843,en="Wind Carol",ja="耐風カロル第一楽章",de="Wind-Gesang",fr="Cantique de vent",recast=96},
    [844] = {id=844,en="Earth Carol",ja="耐震カロル第一楽章",de="Erden-Gesang",fr="Cantique de terre",recast=96},
    [845] = {id=845,en="Lightning Carol",ja="耐電カロル第一楽章",de="Blitz-Gesang",fr="Cant. de foudre",recast=96},
    [846] = {id=846,en="Water Carol",ja="耐波カロル第一楽章",de="Wasser-Gesang",fr="Cantique d'eau",recast=96},
    [847] = {id=847,en="Light Carol",ja="耐光カロル第一楽章",de="Licht-Gesang",fr="Cantique lumière",recast=96},
    [848] = {id=848,en="Dark Carol",ja="耐闇カロル第一楽章",de="Dunkel-Gesang",fr="Cant. ténèbres",recast=96},
    [849] = {id=849,en="Fire Carol II",ja="耐火カロル第二楽章",de="Feuer-Gesang II",fr="Cantique de feu II",recast=96},
    [850] = {id=850,en="Ice Carol II",ja="耐寒カロル第二楽章",de="Eis-Gesang II",fr="Cant. de glace II",recast=96},
    [851] = {id=851,en="Wind Carol II",ja="耐風カロル第二楽章",de="Wind-Gesang II",fr="Cant. de vent II",recast=96},
    [852] = {id=852,en="Earth Carol II",ja="耐震カロル第二楽章",de="Erden-Gesang II",fr="Cant. de terre II",recast=96},
    [853] = {id=853,en="Lightning Carol II",ja="耐電カロル第二楽章",de="Blitz-Gesang II",fr="Cant. de foudre II",recast=96},
    [854] = {id=854,en="Water Carol II",ja="耐波カロル第二楽章",de="Wasser-Gesang II",fr="Cantique d'eau II",recast=96},
    [855] = {id=855,en="Light Carol II",ja="耐光カロル第二楽章",de="Licht-Gesang II",fr="Cant. lumière II",recast=96},
    [856] = {id=856,en="Dark Carol II",ja="耐闇カロル第二楽章",de="Dunkel-Gesang II",fr="Cant. ténèbres II",recast=96},
    [857] = {id=857,en="Fire Threnody",ja="炎のスレノディ",de="Feuer-Threnodie",fr="Thrène de feu",recast=96},
    [858] = {id=858,en="Ice Threnody",ja="氷のスレノディ",de="Eis-Threnodie",fr="Thrène de glace",recast=96},
    [859] = {id=859,en="Wind Threnody",ja="風のスレノディ",de="Wind-Threnodie",fr="Thrène de vent",recast=96},
    [860] = {id=860,en="Earth Threnody",ja="土のスレノディ",de="Erden-Threnodie",fr="Thrène de terre",recast=96},
    [861] = {id=861,en="Ltng. Threnody",ja="雷のスレノディ",de="Blitz-Threnodie",fr="Thrène de foudre",recast=96},
    [862] = {id=862,en="Water Threnody",ja="水のスレノディ",de="Wasser-Threnodie",fr="Thrène d'eau",recast=96},
    [863] = {id=863,en="Light Threnody",ja="光のスレノディ",de="Licht-Threnodie",fr="Thr. de lumière",recast=96},
    [864] = {id=864,en="Dark Threnody",ja="闇のスレノディ",de="Dunkel-Threnodie",fr="Thr. des ténèbres",recast=96},
    [865] = {id=865,en="Magic Finale",ja="魔法のフィナーレ",de="Magisches Finale",fr="Finale magique",recast=96},
    [866] = {id=866,en="Goddess's Hymnus",ja="女神のヒムヌス",de="Hymne der Göttin",fr="Hymne divin",recast=96},
    [867] = {id=867,en="Raptor Mazurka",ja="ラプトルのマズルカ",de="Raptor-Mazurka",fr="Mazurka raptor",recast=96},
    [868] = {id=868,en="Chocobo Mazurka",ja="チョコボのマズルカ",de="Chocobo-Mazurka",fr="Mazurka chocobo",recast=240},
    [869] = {id=869,en="Maiden's Virelai",ja="乙女のヴィルレー",de="Jungfr.-Virelai",fr="Virelai inaugural",recast=240},
    [870] = {id=870,en="Foe Sirvente",ja="魔物のシルベント",de="Feindes-Sirvente",fr="Sirvente ennemi",recast=96},
    [871] = {id=871,en="Adventurer's Dirge",ja="冒険者のダージュ",de="Abent.-Klagelied",fr="Mélopée amie",recast=96},
    [872] = {id=872,en="Sentinel's Scherzo",ja="警戒のスケルツォ",de="Wächter-Scherzo",fr="Scherzo sentinelle",recast=96},
    [873] = {id=873,en="Pining Nocturne",ja="恋情のノクターン",de="Sehnsucht-Nocturne",fr="Noct. languissant",recast=96},
    [880] = {id=880,en="Paralyga",ja="パライガ",de="Paralyga",fr="OmniParalysie",recast=80},
    [881] = {id=881,en="Slowga",ja="スロウガ",de="Gemachga",fr="OmniLenteur",recast=120},
    [882] = {id=882,en="Hastega",ja="ヘイスガ",de="Hastga",fr="OmniHâte",recast=120},
    [883] = {id=883,en="Silencega",ja="サイレガ",de="Schweiga",fr="OmniSilence",recast=80},
    [884] = {id=884,en="Dispelga",ja="ディスペガ",de="Entzauberga",fr="OmniDissipation",recast=240},
    [885] = {id=885,en="Blindga",ja="ブライガ",de="Blindga",fr="OmniCécité",recast=80},
    [886] = {id=886,en="Bindga",ja="バインガ",de="Fesselga",fr="OmniEntrave",recast=200},
    [887] = {id=887,en="Sleepga",ja="スリプガ",de="Schlafga",fr="OmniSommeil",recast=160},
    [888] = {id=888,en="Sleepga II",ja="スリプガII",de="Schlafga II",fr="OmniSommeil II",recast=200},
    [889] = {id=889,en="Graviga",ja="グラビガ",de="Schwerkraftga",fr="OmniPesanteur",recast=240},
    [890] = {id=890,en="Death",ja="デス",de="Tod",fr="Mort",recast=40},
    [891] = {id=891,en="(magic 506)",ja="(予備)",de="a line help text",fr=".",recast=20},
    [892] = {id=892,en="Meteor II",ja="メテオII",de="Meteor II",fr="Météore II",recast=208},
    [893] = {id=893,en="Virus",ja="ウィルス",de="Viren",fr="Virus",recast=40},
    [894] = {id=894,en="Curse",ja="カーズ",de="Fluch",fr="Maléfice",recast=40},
    [895] = {id=895,en="(magic 476)",ja="(予備)",de="a line help text",fr=".",recast=96},
    [896] = {id=896,en="Shantotto",ja="シャントット",de="Shantotto",fr="Shantotto",recast=192},
    [897] = {id=897,en="Naji",ja="ナジ",de="Naji",fr="Naji",recast=192},
    [898] = {id=898,en="Kupipi",ja="クピピ",de="Kupipi",fr="Kupipi",recast=192},
    [899] = {id=899,en="Excenmille",ja="エグセニミル",de="Excenmille",fr="Excenmille",recast=192},
    [900] = {id=900,en="Ayame",ja="アヤメ",de="Ayame",fr="Ayame",recast=192},
    [901] = {id=901,en="Nanaa Mihgo",ja="ナナー・ミーゴ",de="Nanaa Mihgo",fr="Nanaa Mihgo",recast=192},
    [902] = {id=902,en="Curilla",ja="クリルラ",de="Curilla",fr="Curilla",recast=192},
    [903] = {id=903,en="Volker",ja="フォルカー",de="Volker",fr="Volker",recast=192},
    [904] = {id=904,en="Ajido-Marujido",ja="アジドマルジド",de="Ajido-Marujido",fr="Ajido-Marujido",recast=192},
    [905] = {id=905,en="Trion",ja="トリオン",de="Trion",fr="Trion",recast=192},
    [906] = {id=906,en="Zeid",ja="ザイド",de="Zeid",fr="Zeid",recast=192},
    [907] = {id=907,en="Lion",ja="ライオン",de="Lion",fr="Lion",recast=192},
    [908] = {id=908,en="Tenzen",ja="テンゼン",de="Tenzen",fr="Tenzen",recast=192},
    [909] = {id=909,en="Mihli Aliapoh",ja="ミリ・アリアポー",de="Mihli Aliapoh",fr="Mihli Aliapoh",recast=192},
    [910] = {id=910,en="Valaineral",ja="ヴァレンラール",de="Valaineral",fr="Valaineral",recast=192},
    [911] = {id=911,en="Joachim",ja="ヨアヒム",de="Joachim",fr="Joachim",recast=192},
    [912] = {id=912,en="Naja Salaheem",ja="ナジャ・サラヒム",de="Naja Salaheem",fr="Naja Salaheem",recast=192},
    [913] = {id=913,en="Prishe",ja="プリッシュ",de="Prishe",fr="Prishe",recast=192},
    [914] = {id=914,en="Ulmia",ja="ウルミア",de="Ulmia",fr="Ulmia",recast=192},
    [916] = {id=916,en="Cherukiki",ja="チェルキキ",de="Cherukiki",fr="Cherukiki",recast=192},
    [917] = {id=917,en="Iron Eater",ja="アイアンイーター",de="Iron Eater",fr="Iron Eater",recast=192},
    [918] = {id=918,en="Gessho",ja="ゲッショー",de="Gessho",fr="Gessho",recast=192},
    [919] = {id=919,en="Gadalar",ja="ガダラル",de="Gadalar",fr="Gadalar",recast=192},
    [921] = {id=921,en="Ingrid",ja="イングリッド",de="Ingrid",fr="Ingrid",recast=192},
    [922] = {id=922,en="Lehko Habhoka",ja="レコ・ハボッカ",de="Lehko Habhoka",fr="Lehko Habhoka",recast=192},
    [923] = {id=923,en="Nashmeira",ja="ナシュメラ",de="Nashmeira",fr="Nashmeira",recast=192},
    [924] = {id=924,en="Zazarg",ja="ザザーグ",de="Zazarg",fr="Zazarg",recast=192},
    [925] = {id=925,en="Ovjang",ja="アヴゼン",de="Ovjang",fr="Ovjang",recast=192},
    [926] = {id=926,en="Mnejing",ja="メネジン",de="Mnejing",fr="Mnejing",recast=192},
    [927] = {id=927,en="Sakura",ja="サクラ",de="Sakura",fr="Sakura",recast=192},
    [928] = {id=928,en="Luzaf",ja="ルザフ",de="Luzaf",fr="Luzaf",recast=192},
    [929] = {id=929,en="Najelith",ja="ナジュリス",de="Najelith",fr="Najelith",recast=192},
    [930] = {id=930,en="Aldo",ja="アルド",de="Aldo",fr="Aldo",recast=192},
    [931] = {id=931,en="Moogle",ja="モーグリ",de="Moogle",fr="Moogle",recast=192},
    [932] = {id=932,en="Fablinix",ja="ファブリニクス",de="Fablinix",fr="Fablinix",recast=192},
    [933] = {id=933,en="Maat",ja="マート",de="Maat",fr="Maat",recast=192},
    [934] = {id=934,en="D. Shantotto",ja="D.シャントット",de="D. Shantotto",fr="Délic. Shantotto",recast=192},
}, {"id", "en", "ja", "de", "fr", "recast"}

--[[
Copyright © 2013-2014, Windower
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Windower nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Windower BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
