-- Automatically generated file: Titles

return {
    [0] = {id=0,en="N/A",ja="なし",de="N/A",fr="Aucun titre"},
    [1] = {id=1,en="Fodderchief Flayer",ja="フォッダーチーフ　フレーヤー",de="Fodderchief-Plünderer",fr="Rosseur de Fodderchief"},
    [2] = {id=2,en="Warchief Wrecker",ja="ウォーチーフ　レッカー",de="Warchief-Zerstörer",fr="Casseur de Warchief"},
    [3] = {id=3,en="Dread Dragon Slayer",ja="ドレッドドラゴン　スレーヤー",de="Dread Dragon-Totschläger",fr="Tueur de Dread Dragon"},
    [4] = {id=4,en="Overlord Executioner",ja="オーバーロード　エグゼキューショナー",de="Overlord-Henker",fr="Exécuteur d'Overlord"},
    [5] = {id=5,en="Dark Dragon Slayer",ja="ダークドラゴン　スレーヤー",de="Dark Dragon-Totschläger",fr="Tueur de Dark Dragon"},
    [6] = {id=6,en="Adamantking Killer",ja="アダマンキング　キラー",de="Adamantking-Killer",fr="Tueur d'Adamantking"},
    [7] = {id=7,en="Black Dragon Slayer",ja="ブラックドラゴン　スレーヤー",de="Black Dragon-Totschläger",fr="Tueur de Black Dragon"},
    [8] = {id=8,en="Manifest Mauler",ja="マニフェスト　モーラー",de="Manifest-Prügler",fr="Mutilateur de Manifest"},
    [9] = {id=9,en="Behemoth's Bane",ja="ベヒーモス　ベーン",de="Behemoths Bann",fr="Fléau de Béhémoth"},
    [10] = {id=10,en="Archmage Assassin",ja="アークメイジ　アサシン",de="Archmage-Mörder",fr="Assassin d'archimage"},
    [11] = {id=11,en="Hellsbane",ja="ヘルズベーン",de="Höllenbann",fr="Fléau de l'enfer"},
    [12] = {id=12,en="Giant Killer",ja="ジャイアントキラー",de="Riesenkiller",fr="Tueur de géant"},
    [13] = {id=13,en="Lich Banisher",ja="リッチ　バニッシャー",de="Lich-Vertreiber",fr="Bannisseur de Lich"},
    [14] = {id=14,en="Jellybane",ja="ジェリーベーン",de="Sülzenbann",fr="Fléau de Jelly"},
    [15] = {id=15,en="Bogeydowner",ja="ゴギー　ダウナー",de="Bogeydowner",fr="Tueur de Goggie"},
    [16] = {id=16,en="Beakbender",ja="ビークベンダー",de="Schnabelkrümmer",fr="Briseur de bec"},
    [17] = {id=17,en="Skullcrusher",ja="スカルクラッシャー",de="Schädelspalter",fr="Briseur de crâne"},
    [18] = {id=18,en="Morbolbane",ja="モルボル　ベーン",de="Morbolbann",fr="Fléau de Morbol"},
    [19] = {id=19,en="Goliath Killer",ja="ゴリアテ　キラー",de="Goliath-Killer",fr="Tueur de Goliath"},
    [20] = {id=20,en="Mary's Guide",ja="メリーズガイド",de="Marys Führer",fr="Guide de Mary"},
    [21] = {id=21,en="Simurgh Poacher",ja="シムルグ　スレーヤー",de="Simurgh-Wilddieb",fr="Eventreur de Simurgh"},
    [22] = {id=22,en="Roc Star",ja="ロック　スター",de="Roc-Star",fr="Star de Roc"},
    [23] = {id=23,en="Serket Breaker",ja="セルケト　ブレーカー",de="Serket-Brecher",fr="Briseur de Serket"},
    [24] = {id=24,en="Cassienova",ja="キャシノバ",de="Cassienova",fr="Cassienova"},
    [25] = {id=25,en="The Hornsplitter",ja="ホーンスプリッター",de="Der Hornspalter",fr="Fendeur de corne"},
    [26] = {id=26,en="Tortoise Torturer",ja="トータストーチャラー",de="Schildkröten-Folterer",fr="Tortionnaire de tortue"},
    [27] = {id=27,en="Mon Cherry",ja="モン　チェリー",de="Mon Cherry",fr="Mon Cherry"},
    [28] = {id=28,en="Behemoth Dethroner",ja="べヒーモス　デスローナー",de="Behemoth-Entthroner",fr="Détrôneur de Béhémoth"},
    [29] = {id=29,en="The Vivisector",ja="ビビセクター",de="Der Vivisezierer",fr="Vivisecteur"},
    [30] = {id=30,en="Dragon Asher",ja="ドラゴンアッシャー",de="Drachen-Einäscherer",fr="Brûleur de dragon"},
    [31] = {id=31,en="Expeditionary Trooper",ja="遠征軍遊撃隊員",de="Erkundungskavallerist",fr="Soldat expéditionnaire"},
    [32] = {id=32,en="Bearer of the Wisewoman's Hope",ja="賢者の希望を担いし者",de="Träger der Hoffnung der weisen Frau",fr="Porteur de l'espoir du Sage"},
    [33] = {id=33,en="Bearer of the Eight Prayers",ja="八つの祈りを帯びし者",de="Träger der acht Gebete",fr="Porteur des huit prières"},
    [34] = {id=34,en="Lightweaver",ja="光の紡ぎ手",de="Leichtweber",fr="Tisseur de lumière"},
    [35] = {id=35,en="Destroyer of Antiquity",ja="いにしえを屠る者",de="Zerstörer des Altertums",fr="Destructeur de l'Antiquité"},
    [36] = {id=36,en="Sealer of the Portal of the Gods",ja="神の扉を閉ざす者",de="Versiegler des Götterportals",fr="Scelleur du portail des dieux"},
    [37] = {id=37,en="Burier of the Illusion",ja="幻影を葬りし者",de="Begraber von Illusionen",fr="Fossoyeur de l'Illusion"},
    [39] = {id=39,en="Family Counselor",ja="小さな親切運動家",de="Familienberater",fr="Conseiller familial"},
    [41] = {id=41,en="Great Grappler Scorpio!?",ja="格闘家スコーピオン！？",de="Großgreiferskorpion!?",fr="Grand lutteur Scorpion !?"},
    [42] = {id=42,en="Bond Fixer",ja="絆の証人",de="Bandenreparierer",fr="Fixeur de lien"},
    [43] = {id=43,en="Vampire Hunter D-Minus",ja="低級ヴァンパイアハンター",de="Vampirjagd D-Minus",fr="Chasseur de vampires de bas étage"},
    [44] = {id=44,en="Sheep's Milk Deliverer",ja="羊乳配達人",de="Schafsmilchlieferant",fr="Livreur de lait de brebis"},
    [45] = {id=45,en="Bean Cuisine Salter",ja="マメ料理人手伝い",de="Bohnenküchen-Einsalzer",fr="Saleur de haricots"},
    [46] = {id=46,en="Total Loser",ja="ヘッポコくん",de="Totaler Verlierer",fr="Raté complet"},
    [47] = {id=47,en="Doctor Shantotto's Flavor of the Month",ja="シャントット博士のお気に入り",de="Doktor Shantottos Aroma des Monats",fr="Chouchou du Dr Shantotto"},
    [48] = {id=48,en="Pilgrim to Holla",ja="ホラの巡礼者",de="Pilger nach Holla",fr="Pèlerin de Holla"},
    [49] = {id=49,en="Pilgrim to Dem",ja="デムの巡礼者",de="Pilger nach Dem",fr="Pèlerin de Dem"},
    [50] = {id=50,en="Pilgrim to Mea",ja="メアの巡礼者",de="Pilger nach Mea",fr="Pèlerin de Mea"},
    [51] = {id=51,en="Daybreak Gambler",ja="暁の勝負師",de="Tagesanbruchs-Glücksspieler",fr="Joueur de l'aube"},
    [52] = {id=52,en="The Pious One",ja="信心深き者",de="Der Fromme",fr="Pieux"},
    [53] = {id=53,en="A Moss Kind Person",ja="心優しき者",de="Eine sehr nette Person",fr="Ame charitable"},
    [54] = {id=54,en="Entrance Denied",ja="門前払い",de="Zugang verwährt",fr="Entrée refusée"},
    [55] = {id=55,en="Apiarist",ja="ハチミツ博士",de="Imker",fr="Apiculteur"},
    [56] = {id=56,en="Rabbiter",ja="ワイルドハンター",de="Kaninchenzüchter",fr="Spécialiste en lapins"},
    [57] = {id=57,en="Royal Grave Keeper",ja="龍王の墓守",de="Königlicher Grabpfleger",fr="Gardien de tombe royale"},
    [58] = {id=58,en="Courier Extraordinaire",ja="凄腕の運び屋",de="Sonderbote",fr="Coursier hors du commun"},
    [59] = {id=59,en="Ronfaurian Rescuer",ja="森の救急隊員",de="Retter aus Ronfaure",fr="Sauveteur de Ronfaure"},
    [60] = {id=60,en="Pickpocket Pincher",ja="街の名探偵",de="Taschendieb-Klauer",fr="Pinceur de pickpockets"},
    [61] = {id=61,en="Fang Finder",ja="ファング",de="Zahnfinder",fr="Trouveur de crocs"},
    [62] = {id=62,en="Faith like a Candle",ja="炎の信者",de="Glauben wie eine Kerze",fr="Foi de cierge"},
    [63] = {id=63,en="The Pure One",ja="清らかなる者",de="Der Pure",fr="Ame pure"},
    [64] = {id=64,en="Lost Child Officer",ja="迷子引受人",de="Beauftragter für verirrte Kinder",fr="Agent des enfants perdus"},
    [65] = {id=65,en="Silencer of the Lambs",ja="沈黙の羊飼い",de="Schalldämpfer der Lämmer",fr="Silencieux des agneaux"},
    [66] = {id=66,en="Lost & Found Officer",ja="遺失物捜索隊員",de="Fundbürobeamter",fr="Agent des objets trouvés"},
    [67] = {id=67,en="Green Grocer",ja="ベジタブル特急",de="Gemüsehändler",fr="Epicier"},
    [68] = {id=68,en="The Benevolent One",ja="慈悲深き者",de="Der Wohltätige",fr="Bienveillant"},
    [69] = {id=69,en="Knight in Training",ja="見習い騎士",de="Ritter in Ausbildung",fr="Chevalier en formation"},
    [70] = {id=70,en="Lizard Skinner",ja="リザードキラー",de="Eidechsenhäuter",fr="Dépeceur de lézards"},
    [71] = {id=71,en="Bug Catcher",ja="虫採り名人",de="Insektenfänger",fr="Attrapeur d'insectes"},
    [72] = {id=72,en="Spelunker",ja="洞窟探検隊",de="Höhlenforscher",fr="Spéléologue"},
    [73] = {id=73,en="Arms Trader",ja="取引代理人",de="Waffenhändler",fr="Marchand d'armes"},
    [74] = {id=74,en="Traveling Medicine Man",ja="旅の調剤士",de="Reisender Medizinmann",fr="Guérisseur itinérant"},
    [75] = {id=75,en="Cat Skinner",ja="虎ハンター",de="Katzenhäuter",fr="Dépeceur de chat"},
    [76] = {id=76,en="Carp Diem",ja="フナ釣りマイスター",de="Karpfen Diem",fr="Carpe diem"},
    [77] = {id=77,en="Advertising Executive",ja="呼び込み名人",de="Werbefachmann",fr="Publicitaire"},
    [78] = {id=78,en="Third-rate Organizer",ja="下級オーガナイザー",de="Drittklassiger Organisator",fr="Organisateur de troisième plan"},
    [79] = {id=79,en="Second-rate Organizer",ja="中級オーガナイザー",de="Zweitklassiger Organisator",fr="Organisateur de second plan"},
    [80] = {id=80,en="First-rate Organizer",ja="上級オーガナイザー",de="Erstklassiger Organisator",fr="Organisateur de premier plan"},
    [81] = {id=81,en="Bastok Welcoming Committee",ja="バストゥークの案内人",de="Begrüßungskomitee von Bastok",fr="Comité d'accueil de Bastok"},
    [82] = {id=82,en="Shell Outer",ja="甲羅からの解放者",de="Muschelholer",fr="Videur de coquille"},
    [83] = {id=83,en="Bucket Fisher",ja="バケツフィッシャー",de="Eimerfischer",fr="Pêcheur de seaux"},
    [84] = {id=84,en="Pursuer of the Past",ja="過去を垣間見る者",de="Verfolger der Vergangenheit",fr="Poursuivant du passé"},
    [85] = {id=85,en="Pursuer of the Truth",ja="真実の探求者",de="Verfolger der Wahrheit",fr="Poursuivant de la vérité"},
    [86] = {id=86,en="Mommy's Helper",ja="ママのお手伝い",de="Mamas Helfer",fr="Assistant de maman"},
    [87] = {id=87,en="Hot Dog",ja="スモーキー",de="Hot Dog",fr="Hot-dog"},
    [88] = {id=88,en="Stampeder",ja="スタンピオン",de="Stampeder",fr="Ecraseur"},
    [89] = {id=89,en="Qiji's Friend",ja="クィジの友人",de="Qijis Freund",fr="Ami de Qiji"},
    [90] = {id=90,en="Qiji's Rival",ja="クィジのライバル",de="Qijis Rivale",fr="Rival de Qiji"},
    [91] = {id=91,en="Contest Rigger",ja="勝負の采配人",de="Wettbewerbs-Rigger",fr="Organisateur de concours"},
    [92] = {id=92,en="Ringbearer",ja="怪しい運び屋",de="Ringträger",fr="Porteur de bagues"},
    [93] = {id=93,en="Kulatz Bridge Companion",ja="クラウツ橋の友人",de="Kulatz-Brückenkamerad",fr="Compagnon du pont de Kulatz"},
    [94] = {id=94,en="Beadeaux Surveyor",ja="ベドー調査員",de="Vermesser von Beadeaux",fr="Vigie de Beadeaux"},
    [95] = {id=95,en="Avenger",ja="死者を弔いし者",de="Rächer",fr="Vengeur"},
    [96] = {id=96,en="Treasure Scavenger",ja="トレジャーハンター",de="Schatzsammler",fr="Chasseur de trésors"},
    [97] = {id=97,en="Airship Denouncer",ja="飛空艇伝道師",de="Luftschiff-Verkünder",fr="Dénonciateur d'aéronef"},
    [98] = {id=98,en="Zeruhn Sweeper",ja="ツェールンスイーパー",de="Zeruhn-Räumboot",fr="Balayeur de Zeruhn"},
    [99] = {id=99,en="Tearjerker",ja="水辺に立つ者",de="Schmachtfetzen",fr="Tire-larmes"},
    [100] = {id=100,en="Crab Crusher",ja="クラブクラッシャー",de="Krabbenspalter",fr="Ecraseur de crabes"},
    [101] = {id=101,en="Star of Ifrit",ja="イフリートの空に向かう者",de="Stern von Ifrit",fr="Etoile d'Ifrit"},
    [102] = {id=102,en="Sorrow Drowner",ja="ラプソディコンダクター",de="Sorgenertränker",fr="Noyeur de chagrin"},
    [103] = {id=103,en="Brygid-approved",ja="ブリジッドのお墨付き",de="Brygid-anerkannt",fr="Approuvé par Brygid"},
    [104] = {id=104,en="Drachenfall Ascetic",ja="臥竜の験者",de="Drachenfall-Asket",fr="Ascète de Drachen"},
    [105] = {id=105,en="\"Steaming Sheep\" Regular",ja="「蒸気の羊」亭の常連客",de="Stammkunde im \"Dampfenden Schaf\"",fr="Habitué du Mouton Fumé"},
    [106] = {id=106,en="Purple Belt",ja="紫帯の有段者",de="Lila Gürtel",fr="Ceinture violette"},
    [107] = {id=107,en="Gustaberg Tourist",ja="グスタベルグツーリスト",de="Gustaberg-Tourist",fr="Touriste de Gustaberg"},
    [108] = {id=108,en="Sand Blaster",ja="砂の開拓者",de="Sandsturm",fr="Sableur"},
    [109] = {id=109,en="Black Death",ja="黒の死神",de="Schwarzer Tod",fr="Mort noire"},
    [111] = {id=111,en="Fresh \"North Winds\" Recruit",ja="北風団の新米",de="Frischer Rekrut von \"Nordwind\"",fr="Nouvelle recrue des \"Vents du nord\""},
    [112] = {id=112,en="New \"Best of the West\" Recruit",ja="ウェスト・オブ・ビースト",de="Neuer Rekrut von \"Die Besten aus dem Westen\"",fr="Nouvelle recrue des \"Meilleurs de l'ouest\""},
    [113] = {id=113,en="New \"Buuma's Boomers\" Recruit",ja="ブーマガードの新米",de="Neuer Rekrut von \"Buumas Wanderratten\"",fr="Nouvelle recrue des \"Boumeurs de Buuma\""},
    [114] = {id=114,en="Heavens Tower Gatehouse Recruit",ja="天の塔前・魔戦士隊員",de="Rekrut vom Himmelsturm-Torhaus",fr="Recrue des gardes de la Tour des cieux"},
    [115] = {id=115,en="Cat Burglar Groupie",ja="泥棒ミスラのコブン",de="Katzeneinbrecher-Groupie",fr="Sous-fifre de la Chatpardeuse"},
    [116] = {id=116,en="Crawler Culler",ja="クロウラーバスター",de="Crawler-Aussonderer",fr="Casseur de Crawlers"},
    [117] = {id=117,en="Savior of Knowledge",ja="知識の守り手",de="Retter des Wissens",fr="Sauveur du savoir"},
    [118] = {id=118,en="Star-ordained Warrior",ja="星巡りの戦士",de="Mit Sternen geweihter Krieger",fr="Guerrier ordonné de l'étoile"},
    [119] = {id=119,en="Lower than the Lowest Tunnel Worm",ja="くさったバナナ",de="Der allertiefste Tunnel Worm",fr="Banane pourrie"},
    [120] = {id=120,en="Star Onion Brigade Member",ja="スターオニオンズ団員",de="Mitglied der Sternzwiebelbrigade",fr="Membre de la Brigade des oignons stellaires"},
    [121] = {id=121,en="Star Onion Brigadier",ja="オニオンヒーロー",de="Kommandeur der Sternzwiebelbrigade",fr="Brigadier des oignons stellaires"},
    [122] = {id=122,en="Quick Fixer",ja="お手軽修繕屋",de="Schnelllöser",fr="Réparateur rapide"},
    [123] = {id=123,en="Fake-moustached Investigator",ja="つけひげの名探偵",de="Ermittler mit falschem Schnurrbart",fr="Enquêteur à fausse moustache"},
    [124] = {id=124,en="Hakkuru-Rinkuru's Benefactor",ja="ハックルリンクルの恩人",de="Hakkuru-Rinkurus Wohltäter",fr="Bienfaiteur de Hakkuru-Rinkuru"},
    [125] = {id=125,en="S.O.B. Super Hero",ja="正義の味方",de="SZB-Superheld",fr="Super héros de la Brigade des oignons stellaires"},
    [126] = {id=126,en="Editor's Hatchet Man",ja="編集長の刺客",de="Zuchtmeister des Herausgebers",fr="Meurtrier du rédacteur"},
    [127] = {id=127,en="Doctor Shantotto's Guinea Pig",ja="シャントット博士の実験台",de="Doktor Shantottos Versuchskaninchen",fr="Cobaye du Dr Shantotto"},
    [128] = {id=128,en="Spoilsport",ja="マナー違反者",de="Spielverderber",fr="Mal élevé"},
    [129] = {id=129,en="Super Model",ja="ナイスモデル",de="Super Model",fr="Top modèle"},
    [130] = {id=130,en="Ghostie Buster",ja="ゴーストバスター",de="Ghostie Buster",fr="S.O.S. revenant"},
    [131] = {id=131,en="Night Sky Navigator",ja="夜空の航海士",de="Nachthimmel-Navigator",fr="Navigateur du ciel nocturne"},
    [132] = {id=132,en="Fast Food Deliverer",ja="買出し部隊員",de="Fast Food-Lieferant",fr="Livreur de restauration rapide"},
    [133] = {id=133,en="Cupid's Florist",ja="花鼻キューピッド",de="Amors Florist",fr="Fleuriste de Cupidon"},
    [134] = {id=134,en="Tarutaru Murder Suspect",ja="殺タルタル容疑者",de="Tarutaru-Mordverdächtiger",fr="Suspect d'un meurtre de Tarutaru"},
    [135] = {id=135,en="Hexer Vexer",ja="不幸な呪い師",de="Hexer-Plager",fr="Envoûteur malchanceux"},
    [136] = {id=136,en="Cardian Tutor",ja="カーディアン教育者",de="Cardianer Studienleiter",fr="Tuteur de Cardien"},
    [137] = {id=137,en="Deliverer of Tearful News",ja="銀色の涙の使者",de="Lieferant des Tränenblatts",fr="Porteur de tristes nouvelles"},
    [138] = {id=138,en="Fossilized Sea Farer",ja="太古の海人",de="Versteinerter Seefahrer",fr="Marin fossilisé"},
    [139] = {id=139,en="Down Piper Pipe-upperer",ja="栄光なる薔薇の笛吹き",de="Fallrohr-Rohrsteiger",fr="Flûtiste pipeauteur"},
    [140] = {id=140,en="Kisser Make-upper",ja="美の開拓者",de="Küsser Make-upper",fr="Grand maquilleur"},
    [141] = {id=141,en="Timekeeper",ja="時の旅人",de="Zeitmesser",fr="Chronométreur"},
    [142] = {id=142,en="Fortune-teller in Training",ja="見習い占い師",de="Wahrsager in der Ausbildung",fr="Voyant en formation"},
    [143] = {id=143,en="Torchbearer",ja="ともし火ランナー",de="Fackelträger",fr="Porteur de torche"},
    [144] = {id=144,en="Tenshodo Member",ja="天晶堂会員",de="Tenshodo-Mitglied",fr="Membre du Tenshodo"},
    [145] = {id=145,en="Chocobo Trainer",ja="チョコボ調教師",de="Chocobo-Ausbilder",fr="Dresseur de chocobo"},
    [146] = {id=146,en="Bringer of Bliss",ja="しあわせ宅配人",de="Glücksbringer",fr="Porteur de bénédiction"},
    [147] = {id=147,en="Activist for Kindness",ja="慈善活動家",de="Freundlichkeitsaktivist",fr="Activiste de la gentillesse"},
    [148] = {id=148,en="Envoy to the North",ja="北への使者",de="Abgesandter in den Norden",fr="Envoyé vers le nord"},
    [149] = {id=149,en="Exorcist in Training",ja="エクソシスト見習い",de="Exorzist in der Ausbildung",fr="Exorciste en formation"},
    [150] = {id=150,en="Professional Loafer",ja="街一番の油売り",de="Faulenzer von Beruf",fr="Fainéant professionnel"},
    [151] = {id=151,en="Clock Tower Preservationist",ja="時計塔保存嘆願者",de="Uhrturm-Denkmalschützer",fr="Conservateur de la tour de l'horloge"},
    [152] = {id=152,en="Life Saver",ja="命の恩人",de="Lebensretter",fr="Sauveur"},
    [153] = {id=153,en="Fool's Errand Runner",ja="下級ツカイッパー",de="Laufbursche",fr="Garçon de courses du fou"},
    [154] = {id=154,en="Card Collector",ja="カードコレクター",de="Kartensammler",fr="Collectionneur de cartes"},
    [155] = {id=155,en="Researcher of Classics",ja="古典研究家",de="Forscher des Klassischen Zeitalters",fr="Chercheur de classiques"},
    [156] = {id=156,en="Street Sweeper",ja="街の掃除人",de="Straßenfeger",fr="Balayeur des rues"},
    [157] = {id=157,en="Mercy Errand Runner",ja="上級ツカイッパー",de="Laufbursche aus Mitleid",fr="Coursier de la pitié"},
    [158] = {id=158,en="Two's Company",ja="第一発見者",de="Zwei-Mann-Betrieb",fr="Perdu de vue"},
    [159] = {id=159,en="Believer of Altana",ja="アルタナ教信者",de="Gläubiger von Altana",fr="Fidèle d'Altana"},
    [160] = {id=160,en="Trader of Mysteries",ja="迷トレーダー",de="Mysterienhändler",fr="Marchand de mystères"},
    [161] = {id=161,en="Trader of Antiquities",ja="お宝出品人",de="Antiquitätenhändler",fr="Marchand d'antiquités"},
    [162] = {id=162,en="Trader of Renown",ja="名トレーダー",de="Berühmter Händler",fr="Marchand de renom"},
    [163] = {id=163,en="Brown Belt",ja="茶帯の有段者",de="Brauner Gürtel",fr="Ceinture marron"},
    [164] = {id=164,en="Horizon Breaker",ja="オーバー・ザ・トップ",de="Horizontbrecher",fr="Briseur d'horizon"},
    [165] = {id=165,en="Goblin's Exclusive Fashion Mannequin",ja="ゴブリン専属モデル",de="Goblins Exklusivmoden-Modell",fr="Mannequin particulier du Goblin"},
    [166] = {id=166,en="Summit Breaker",ja="山の頂に立つ者",de="Gipfelbrecher",fr="Briseur de sommet"},
    [167] = {id=167,en="Sky Breaker",ja="風来坊",de="Himmelsbrecher",fr="Briseur de ciel"},
    [168] = {id=168,en="Cloud Breaker",ja="雲入道",de="Wolkenbrecher",fr="Briseur de nuage"},
    [169] = {id=169,en="Star Breaker",ja="ヴァナ・ディールのスター",de="Sternenbrecher",fr="Briseur d'étoile"},
    [170] = {id=170,en="Greedalox",ja="ヨバクリ",de="Greedalox",fr="Gourmandalox"},
    [171] = {id=171,en="Certified Rhinostery Venturer",ja="鼻の院認可冒険者",de="Zertifizierter Rhinosterie-Unternehmer",fr="Explorateur certifié du rhinostère"},
    [172] = {id=172,en="Cordon Bleu Fisher",ja="釣り名人",de="Cordon Bleu-Angler",fr="Pêcheur cordon bleu"},
    [173] = {id=173,en="Ace Angler",ja="釣り大名人",de="Ass-Angler",fr="Pêcheur d'élite"},
    [174] = {id=174,en="Lu Shang-like Fisher King",ja="太公望",de="Lu Shang-ähnlicher Fischerkönig",fr="Pêcheur légendaire"},
    [175] = {id=175,en="Matchmaker",ja="愛の仲人",de="Kuppler",fr="Entremetteur"},
    [176] = {id=176,en="Ecologist",ja="エコロジスト",de="Ökologe",fr="Ecologiste"},
    [177] = {id=177,en="Li'l Cupid",ja="愛のキューピッド",de="Li'l-Kupido",fr="P'tit Cupidon"},
    [178] = {id=178,en="The Love Doctor",ja="キング・オブ・ラブ",de="Der Liebesdoktor",fr="Docteur de l'amour"},
    [179] = {id=179,en="Savior of Love",ja="愛の救世主",de="Retter der Liebe",fr="Sauveur de l'amour"},
    [180] = {id=180,en="Honorary Citizen of Selbina",ja="セルビナ名誉市民",de="Ehrenbürger von Selbina",fr="Citoyen honoraire de Selbina"},
    [181] = {id=181,en="Purveyor in Training",ja="食材調達人見習い",de="Lieferant in der Ausbildung",fr="Fournisseur en formation"},
    [182] = {id=182,en="One-star Purveyor",ja="食材調達人",de="Ein-Stern-Lieferant",fr="Fournisseur 1 étoile"},
    [183] = {id=183,en="Two-star Purveyor",ja="目利きの調達人",de="Zwei-Sterne-Lieferant",fr="Fournisseur 2 étoiles"},
    [184] = {id=184,en="Three-star Purveyor",ja="調達人",de="Drei-Sterne-Lieferant",fr="Fournisseur 3 étoiles"},
    [185] = {id=185,en="Four-star Purveyor",ja="調達の達人",de="Vier-Sterne-Lieferant",fr="Fournisseur 4 étoiles"},
    [186] = {id=186,en="Five-star Purveyor",ja="孤高の調達人",de="Fünf-Sterne-Lieferant",fr="Fournisseur 5 étoiles"},
    [187] = {id=187,en="Doctor Yoran-Oran Supporter",ja="ヨランオラン博士の味方",de="Anhänger von Doktor Yoran-Oran",fr="Partisan du Dr Yoran-Oran"},
    [188] = {id=188,en="Doctor Shantotto Supporter",ja="シャントット博士の味方",de="Anhänger von Doktor Shantotto",fr="Partisan du Dr Shantotto"},
    [189] = {id=189,en="Professor Koru-Moru Supporter",ja="コルモル博士の味方",de="Anhänger von Professor Koru-Moru",fr="Partisan du Pr Koru-Moru"},
    [190] = {id=190,en="Rainbow Weaver",ja="虹を織りし者",de="Regenbogenweber",fr="Tisseur d'arc-en-ciel"},
    [191] = {id=191,en="Shadow Walker",ja="忍びの道を往く者",de="Schattenläufer",fr="Marcheur de l'ombre"},
    [192] = {id=192,en="Heir to the Holy Crest",ja="聖なる印を継ぐ者",de="Erbe des heiligen Wappens",fr="Héritier de l'écusson sacré"},
    [193] = {id=193,en="Bushido Blade",ja="ブシドー・ザ・ブレード",de="Bushido-Klinge",fr="Lame Bushido"},
    [195] = {id=195,en="Paragon of Paladin Excellence",ja="高雅なる大騎士",de="Vorbild an Paladin-Vortrefflichkeit",fr="Modèle d'excellence du paladin"},
    [196] = {id=196,en="Paragon of Beastmaster Excellence",ja="熾烈なる大獣使い",de="Vorbild an Bestienbändiger-Vortrefflichkeit",fr="Modèle d'excellence du dresseur"},
    [197] = {id=197,en="Paragon of Ranger Excellence",ja="果敢なる大狩人",de="Vorbild an Jäger-Vortrefflichkeit",fr="Modèle d'excellence du chasseur"},
    [198] = {id=198,en="Paragon of Dark Knight Excellence",ja="威風なる大暗黒騎士",de="Vorbild an Dunkelritter-Vortrefflichkeit",fr="Modèle d'excellence du chevalier noir"},
    [199] = {id=199,en="Paragon of Bard Excellence",ja="典麗なる大吟遊詩人",de="Vorbild an Barden-Vortrefflichkeit",fr="Modèle d'excellence du barde"},
    [200] = {id=200,en="Paragon of Samurai Excellence",ja="無双なる大武士",de="Vorbild an Samurai-Vortrefflichkeit",fr="Modèle d'excellence du samouraï"},
    [201] = {id=201,en="Paragon of Dragoon Excellence",ja="勇猛なる大竜騎士",de="Vorbild an Dragoon-Vortrefflichkeit",fr="Modèle d'excellence du chevalier dragon"},
    [202] = {id=202,en="Paragon of Ninja Excellence",ja="沈勇なる大忍者",de="Vorbild an Ninja-Vortrefflichkeit",fr="Modèle d'excellence du ninja"},
    [203] = {id=203,en="Paragon of Summoner Excellence",ja="博雅なる大召喚士",de="Vorbild an Beschwörer-Vortrefflichkeit",fr="Modèle d'excellence de l'invocateur"},
    [206] = {id=206,en="New Adventurer",ja="冒険者見習い",de="Neuer Abenteurer",fr="Nouvel aventurier"},
    [207] = {id=207,en="Certified Adventurer",ja="公認冒険者",de="Zertifizierter Abenteurer",fr="Aventurier certifié"},
    [208] = {id=208,en="Shadow Banisher",ja="闇を祓いし者",de="Schatten-Verbanner",fr="Bannisseur des ombres"},
    [209] = {id=209,en="Tried and Tested Knight",ja="騎士の魂宿りし者",de="Bewährter Ritter",fr="Chevalier vétéran"},
    [210] = {id=210,en="Dark Sider",ja="暗き業宿りし者",de="Dunkelseitiger",fr="Partisan des ténèbres"},
    [211] = {id=211,en="The Fanged One",ja="牙持つ者",de="Der mit den Reißzähnen",fr="Celui qui a des crocs"},
    [212] = {id=212,en="Have Wings, Will Fly",ja="翼持つ者",de="Habe Flügel, fliege gerne",fr="Celui qui a des ailes"},
    [213] = {id=213,en="Animal Trainer",ja="モンスター調教師",de="Tiertrainer",fr="Dresseur d'animaux"},
    [214] = {id=214,en="Wandering Minstrel",ja="心の歌うたい",de="Fahrender Sänger",fr="Ménestrel itinérant"},
    [215] = {id=215,en="Mog's Master",ja="モーグリのご主人さま",de="Meister des Mog",fr="Maître de moogle"},
    [216] = {id=216,en="Mog's Kind Master",ja="やさしいご主人さま",de="Guter Meister des Mog",fr="Bon maître de moogle"},
    [217] = {id=217,en="Mog's Exceptionally Kind Master",ja="すてきなご主人さま",de="Außergewöhnlich guter Meister des Mog",fr="Maître de moogle exceptionnel"},
    [218] = {id=218,en="Paragon of Warrior Excellence",ja="勇壮なる大戦士",de="Vorbild an Krieger-Vortrefflichkeit",fr="Modèle d'excellence du guerrier"},
    [219] = {id=219,en="Paragon of Monk Excellence",ja="孤高なる大格闘家",de="Vorbild an Mönch-Vortrefflichkeit",fr="Modèle d'excellence du moine"},
    [220] = {id=220,en="Paragon of Red Mage Excellence",ja="比類なき大赤魔道士",de="Vorbild an Rotmagier-Vortrefflichkeit",fr="Modèle d'excellence du mage rouge"},
    [221] = {id=221,en="Paragon of Thief Excellence",ja="華麗なる大盗賊",de="Vorbild an Diebes-Vortrefflichkeit",fr="Modèle d'excellence du voleur"},
    [222] = {id=222,en="Paragon of Black Mage Excellence",ja="偉大なる大黒魔道士",de="Vorbild an Schwarzmagier-Vortrefflichkeit",fr="Modèle d'excellence du mage noir"},
    [223] = {id=223,en="Paragon of White Mage Excellence",ja="高潔なる大白魔道士",de="Vorbild an Weißmagier-Vortrefflichkeit",fr="Modèle d'excellence du mage blanc"},
    [224] = {id=224,en="Mog's Loving Master",ja="ラブラブご主人さま",de="Liebender Meister des Mog",fr="Maître attentionné de moogle"},
    [226] = {id=226,en="Royal Archer",ja="王国弓兵",de="Königsschütze",fr="Archer royal"},
    [227] = {id=227,en="Royal Spearman",ja="王国槍兵",de="Königslanzier",fr="Lancier royal"},
    [228] = {id=228,en="Royal Squire",ja="王国従騎士",de="Königsknappe",fr="Ecuyer royal"},
    [229] = {id=229,en="Royal Swordsman",ja="王国剣士",de="Königsfechter",fr="Epéiste royal"},
    [230] = {id=230,en="Royal Cavalier",ja="王国騎士",de="Königsedelmann",fr="Cavalier royal"},
    [231] = {id=231,en="Royal Guard",ja="近衛騎士",de="Königsgarde",fr="Garde royal"},
    [232] = {id=232,en="Grand Knight of the Realm",ja="王国大騎士",de="Großritter des Königreichs",fr="Grand chevalier royal"},
    [233] = {id=233,en="Grand Temple Knight",ja="神殿大騎士",de="Groß-Tempelritter",fr="Grand templier"},
    [234] = {id=234,en="Reserve Knight Captain",ja="傭兵騎士団長",de="Reserveritter-Kommandant",fr="Capitaine chevalier de réserve"},
    [235] = {id=235,en="Elite Royal Guard",ja="上級近衛騎士",de="Elitenkönigsgarde",fr="Garde royal d'élite"},
    [236] = {id=236,en="Legionnaire",ja="共和軍団兵",de="Legionär",fr="Légionnaire républicain"},
    [237] = {id=237,en="Decurion",ja="十人隊長",de="Dekurion",fr="Décurion"},
    [238] = {id=238,en="Centurion",ja="百人隊長",de="Zenturion",fr="Centurion"},
    [239] = {id=239,en="Junior Musketeer",ja="准銃士",de="Junior-Musketier",fr="Mousquetaire cadet"},
    [240] = {id=240,en="Senior Musketeer",ja="正銃士",de="Höherer Musketier",fr="Mousquetaire titulaire"},
    [241] = {id=241,en="Musketeer Commander",ja="銃士隊長",de="Musketier-Kommandeur",fr="Capitaine mousquetaire"},
    [242] = {id=242,en="Gold Musketeer",ja="黄金銃士",de="Goldmusketier",fr="Mousquetaire d'or"},
    [243] = {id=243,en="Praefectus",ja="千人隊長",de="Präfekt",fr="Praefectus"},
    [244] = {id=244,en="Senior Gold Musketeer",ja="先任黄金銃士",de="Senioren-Goldmusketier",fr="Maître mousquetaire d'or"},
    [245] = {id=245,en="Praefectus Castrorum",ja="一番千人隊長",de="Praefectus Castrorum",fr="Praefectus Castrorum"},
    [246] = {id=246,en="Freesword",ja="義勇兵",de="Freischwert",fr="Conquérant"},
    [247] = {id=247,en="Mercenary",ja="傭兵",de="Söldner",fr="Mercenaire"},
    [248] = {id=248,en="Mercenary Captain",ja="傭兵隊長",de="Söldneroberst",fr="Capitaine mercenaire"},
    [249] = {id=249,en="Combat Caster",ja="連邦魔戦士",de="Schlachtenwerfer",fr="Mage guerrier"},
    [250] = {id=250,en="Tactician Magician",ja="連邦軍師",de="Taktischer Magier",fr="Tacticien fédéral"},
    [251] = {id=251,en="Wise Wizard",ja="連邦賢者",de="Weiser Hexer",fr="Sage de la Fédération"},
    [252] = {id=252,en="Patriarch Protector",ja="元老院警護隊士",de="Patriarchenbeschützer",fr="Garde des patriarches"},
    [253] = {id=253,en="Caster Captain",ja="連邦魔戦隊長",de="Werfer-Oberst",fr="Capitaine des mages guerriers"},
    [254] = {id=254,en="Master Caster",ja="筆頭魔戦隊長",de="Meisterwerfer",fr="Maître mage"},
    [255] = {id=255,en="Mercenary Major",ja="連邦傭兵団長",de="Söldnermajor",fr="Commandant des mercenaires"},
    [256] = {id=256,en="Fugitive Minister Bounty Hunter",ja="脱走院長追跡者",de="Kopfgeldjäger des fliehenden Ministers",fr="Chasseur de ministre en fuite"},
    [257] = {id=257,en="King of the Opo-opos",ja="オポオポ王",de="König der Opo-Opos",fr="Roi des Opo-opos"},
    [258] = {id=258,en="Excommunicate of Kazham",ja="カザム追放者",de="Exkommunizierter von Kazham ",fr="Excommunié de Kazham"},
    [259] = {id=259,en="Kazham Caller",ja="カザムの客人",de="Kazham-Rufer",fr="Visiteur de Kazham"},
    [260] = {id=260,en="Dream Dweller",ja="夢の住人",de="Bewohner der Traumwelt",fr="Habitant des rêves"},
    [261] = {id=261,en="Apprentice Sommelier",ja="ソムリエ見習い",de="Kellermeisterlehrling",fr="Apprenti sommelier"},
    [262] = {id=262,en="Desert Hunter",ja="デザートハンター",de="Wüstenjäger",fr="Chasseur du désert"},
    [263] = {id=263,en="Seeker of Truth",ja="真理を垣間見た者",de="Wahrheitssuchender",fr="Chercheur de vérité"},
    [264] = {id=264,en="Kuftal Tourist",ja="クフタルツーリスト",de="Kuftal-Tourist",fr="Touriste de Kuftal"},
    [265] = {id=265,en="The Immortal Fisher, Lu Shang",ja="不死身の太公望",de="Der unsterbliche Fischer, Lu Shang",fr="Le pêcheur immortel, Lu Shang"},
    [266] = {id=266,en="Looks Sublime in a Subligar",ja="サブリガを輝かせる者",de="Sieht in Subligar grandios aus",fr="Sublime en Subligar"},
    [267] = {id=267,en="Looks Good in Leggings",ja="レギンスを輝かせる者",de="Sieht in Leggings gut aus",fr="Superbe en jambières"},
    [268] = {id=268,en="Honorary Doctorate, Majoring in Tonberries",ja="トンベリ博士",de="Ehrendoktortitel, Hauptfach Tonberries",fr="Docteur honoris causa, spécialité Tonberry"},
    [269] = {id=269,en="Treasure-house Ransacker",ja="宝物庫あらし",de="Schatzhaus-Plünderer",fr="Pilleur de trésors"},
    [270] = {id=270,en="Cracker of the Secret Code",ja="暗号？解読者",de="Knacker des Geheimcodes",fr="Décrypteur de code secret"},
    [271] = {id=271,en="Black Marketeer",ja="闇ブローカー",de="Schwarzmarkthändler",fr="Vendeur au marché noir"},
    [272] = {id=272,en="Acquirer of Ancient Arcanum",ja="古代秘法を継ぐ者",de="Erwerber alter Wundermittel",fr="Acheteur d'arcanes antiques"},
    [273] = {id=273,en="Ya Done Good",ja="アンタヤルーニャ",de="Haste gut gemacht",fr="Bien joué"},
    [274] = {id=274,en="Heir of the Great Fire",ja="大いなる火の継承者",de="Erbe des Großen Feuers",fr="Héritier du grand feu"},
    [275] = {id=275,en="Heir of the Great Earth",ja="大いなる土の継承者",de="Erbe der Großen Erde",fr="Héritier de la grande terre"},
    [276] = {id=276,en="Heir of the Great Water",ja="大いなる水の継承者",de="Erbe des Großen Wassers",fr="Héritier de la grande eau"},
    [277] = {id=277,en="Heir of the Great Wind",ja="大いなる風の継承者",de="Erbe des Großen Winds",fr="Héritier du grand vent"},
    [278] = {id=278,en="Heir of the Great Ice",ja="大いなる氷の継承者",de="Erbe des Großen Eises",fr="Héritier de la grande glace"},
    [279] = {id=279,en="Heir of the Great Lightning",ja="大いなる雷の継承者",de="Erbe des Großen Blitzes",fr="Héritier de la grande foudre"},
    [280] = {id=280,en="Guider of Souls to the Sanctuary",ja="聖地に魂導く者",de="Führer der Seelen des Heiligtums",fr="Guide des âmes vers le sanctuaire"},
    [281] = {id=281,en="Bearer of Bonds Beyond Time",ja="時を越えた絆持つ者",de="Träger der Bündnisse jenseits der Zeit",fr="Porteur des liens au-delà du temps"},
    [282] = {id=282,en="Friend of the Opo-opos",ja="オポオポの友",de="Freund der Opo-Opos",fr="Ami des Opo-opos"},
    [283] = {id=283,en="Hero on Behalf of Windurst",ja="ウィンダス代表の勇士",de="Held im Auftrag von Windurst",fr="Héros du camp de Windurst"},
    [284] = {id=284,en="Victor of the Balga Contest",ja="バルガ武闘会の勝利者",de="Sieger des Balga-Wettbewerbs",fr="Vainqueur du concours de Balga"},
    [285] = {id=285,en="Gullible's Travels",ja="いい人カモ",de="Unglaublicher Abenteurer",fr="Peut-être pas si mauvais"},
    [286] = {id=286,en="Even More Gullible's Travels",ja="もっといい人カモ",de="Noch unglaublicherer Abenteurer",fr="Pas si mauvais du tout"},
    [287] = {id=287,en="Heir of the New Moon",ja="新しい力の継承者",de="Erbe des Neumonds",fr="Héritier de la nouvelle lune"},
    [288] = {id=288,en="Assassin Reject",ja="アサシン不採用",de="Mordzurückweisung",fr="Assassin raté"},
    [289] = {id=289,en="Black Belt",ja="黒帯の有段者",de="Schwarzer Gürtel",fr="Ceinture noire"},
    [290] = {id=290,en="Vermillion Venturer",ja="紅霞の雇われハンター",de="Zinnober-Unternehmer",fr="Chasseur à gages vermillon"},
    [291] = {id=291,en="Cerulean Soldier",ja="蒼海の雇われハンター",de="Blauer Soldat",fr="Chasseur à gages azuré"},
    [292] = {id=292,en="Emerald Exterminator",ja="翠嶺の雇われハンター",de="Smaragd-Kammerjäger",fr="Chasseur à gages émeraude"},
    [293] = {id=293,en="Guiding Star",ja="導きの星",de="Leitstern",fr="Etoile guide"},
    [294] = {id=294,en="Vestal Chamberlain",ja="魔天のしるべ",de="Vestalischer Kammerherr",fr="Hôte d'honneur de la chambre vestale"},
    [295] = {id=295,en="San d'Orian Royal Heir",ja="次期サンドリア国王候補者",de="Königlicher Erbe von San d'Oria",fr="Héritier royal de San d'Oria"},
    [296] = {id=296,en="Hero Among Heroes",ja="英雄なき時代の英雄",de="Held unter Helden",fr="Héros des temps modernes"},
    [297] = {id=297,en="Dynamis-San d'Oria Interloper",ja="デュナミス～サンドリアの踏破者",de="Eindringling nach Dynamis - San d'Oria",fr="Explorateur de Dynamis - San d'Oria"},
    [298] = {id=298,en="Dynamis-Bastok Interloper",ja="デュナミス～バストゥークの踏破者",de="Eindringling nach Dynamis - Bastok",fr="Explorateur de Dynamis - Bastok"},
    [299] = {id=299,en="Dynamis-Windurst Interloper",ja="デュナミス～ウィンダスの踏破者",de="Eindringling nach Dynamis - Windurst",fr="Explorateur de Dynamis - Windurst"},
    [300] = {id=300,en="Dynamis-Jeuno Interloper",ja="デュナミス～ジュノの踏破者",de="Eindringling nach Dynamis - Jeuno",fr="Explorateur de Dynamis - Jeuno"},
    [301] = {id=301,en="Dynamis-Beaucedine Interloper",ja="デュナミス～ボスディンの踏破者",de="Eindringling nach Dynamis - Beaucedine",fr="Explorateur de Dynamis - Beaucedine"},
    [302] = {id=302,en="Dynamis-Xarcabard Interloper",ja="デュナミス～ザルカバードの踏破者",de="Eindringling nach Dynamis - Xarcabard",fr="Explorateur de Dynamis - Xarcabard"},
    [303] = {id=303,en="Discerning Individual",ja="違いの分かるヤツ",de="Kritische Person",fr="Individu perspicace"},
    [304] = {id=304,en="Very Discerning Individual",ja="とても違いの分かるヤツ",de="Sehr kritische Person",fr="Individu très perspicace"},
    [305] = {id=305,en="Extremely Discerning Individual",ja="とてもとても違いの分かるヤツ",de="Äußerst kritische Person",fr="Individu extrêmement perspicace"},
    [306] = {id=306,en="Royal Wedding Planner",ja="月下氷人",de="Königlicher Hochzeitsplaner",fr="Organisateur de mariage royal"},
    [307] = {id=307,en="Consort Candidate",ja="サンドリア王子妃候補",de="Geleitschutzkandidat",fr="Candidat consort"},
    [308] = {id=308,en="Obsidian Storm",ja="漆黒の稲妻",de="Obsidiansturm",fr="Tempête d'obsidienne"},
    [309] = {id=309,en="Pentacide Perpetrator",ja="神威",de="Pentazid-Täter",fr="Puissance divine"},
    [310] = {id=310,en="Wood Worshiper",ja="白樫の木彫師",de="Holzanbeter",fr="Adorateur du bois"},
    [311] = {id=311,en="Lumber Lather",ja="紫檀の木彫師",de="Nutzholz-Bearbeiter",fr="Amateur de bois"},
    [312] = {id=312,en="Accomplished Carpenter",ja="黒檀の木彫師",de="Ausgebildeter Tischler",fr="Charpentier accompli"},
    [313] = {id=313,en="Anvil Advocate",ja="青銅の鍛冶師",de="Amboss-Verfechter",fr="Avocat de l'enclume"},
    [314] = {id=314,en="Forge Fanatic",ja="黒鉄の鍛冶師",de="Schmieden-Fanatiker",fr="Fanatique de la forge"},
    [315] = {id=315,en="Accomplished Blacksmith",ja="超鋼の鍛冶師",de="Ausgebildeter Schmied",fr="Forgeron accompli"},
    [316] = {id=316,en="Trinket Turner",ja="真鍮の彫金師",de="Dreher wertlosen Schmucks",fr="Tourneur de babioles"},
    [317] = {id=317,en="Silver Smelter",ja="白銀の彫金師",de="Silberschmelzer",fr="Fondeur d'argent"},
    [318] = {id=318,en="Accomplished Goldsmith",ja="黄金の彫金師",de="Ausgebildeter Goldschmied",fr="Orfèvre accompli"},
    [319] = {id=319,en="Knitting Know-It-All",ja="木綿の裁縫師",de="Strickarbeit-Alleswisser",fr="Tricoteur expérimenté"},
    [320] = {id=320,en="Loom Lunatic",ja="別珍の裁縫師",de="Webstuhl-Narr",fr="Fou du tissage"},
    [321] = {id=321,en="Accomplished Weaver",ja="錦の裁縫師",de="Ausgebildeter Weber",fr="Tisserand accompli"},
    [322] = {id=322,en="Formula Fiddler",ja="博識の錬金術師",de="Formelgauner",fr="Mélangeur de formules"},
    [323] = {id=323,en="Potion Potentate",ja="神秘の錬金術師",de="Potion-Potentat",fr="Potasseur de potions"},
    [324] = {id=324,en="Accomplished Alchemist",ja="奇蹟の錬金術師",de="Ausgebildeter Alchemist",fr="Alchimiste accompli"},
    [325] = {id=325,en="Bone Beautifier",ja="白骨の骨彫師",de="Knochenverschönerer",fr="Embellisseur d'os"},
    [326] = {id=326,en="Shell Scrimshander",ja="亀甲の骨彫師",de="Muschel-Drückeberger",fr="Polisseur de carapace"},
    [327] = {id=327,en="Accomplished Boneworker",ja="珊瑚の骨彫師",de="Ausgebildeter Knochenwerker",fr="Ciseleur d'os accompli"},
    [328] = {id=328,en="Hide Handler",ja="羊皮の革細工師",de="Fellbehandler",fr="Polisseur de peau"},
    [329] = {id=329,en="Leather Lauder",ja="虎皮の革細工師",de="Lederwäscher",fr="Caresseur de cuir"},
    [330] = {id=330,en="Accomplished Tanner",ja="竜皮の革細工師",de="Ausgebildeter Gerber",fr="Tanneur accompli"},
    [331] = {id=331,en="Fastriver Fisher",ja="川釣りの漁師",de="Schnellfluss-Fischer",fr="Pêcheur pilote"},
    [332] = {id=332,en="Coastline Caster",ja="磯釣りの漁師",de="Küstenwerfer",fr="Coureur de côtes"},
    [333] = {id=333,en="Accomplished Angler",ja="沖釣りの漁師",de="Ausgebildeter Angler",fr="Pêcheur accompli"},
    [334] = {id=334,en="Gourmand Gratifier",ja="炎の調理師",de="Feinschmecker-Erfreuer",fr="Gourmand bon vivant"},
    [335] = {id=335,en="Banquet Bestower",ja="三ツ星の調理師",de="Bankett-Geber",fr="Cuisinier trois étoiles"},
    [336] = {id=336,en="Accomplished Chef",ja="至高の調理師",de="Ausgebildeter Koch",fr="Chef accompli"},
    [337] = {id=337,en="Fine Tuner",ja="死ぬ気で冒険者",de="Perfektionist",fr="Grand accordeur"},
    [338] = {id=338,en="Friend of the Helmed",ja="仮面同盟員",de="Freund der Behelmten",fr="Ami des porteurs de casque"},
    [339] = {id=339,en="Tavnazian Squire",ja="タブナジア侯国騎士見習",de="Tavnazischer Knappe",fr="Ecuyer de Tavnazia"},
    [340] = {id=340,en="Ducal Dupe",ja="搾取される弱者",de="Herzoglicher Tölpel",fr="Dupe du duc"},
    [341] = {id=341,en="Hyper Ultra Sonic Adventurer",ja="翼の名づけ親",de="Hyper-Ultraschall-Abenteurer",fr="Aventurier hyper ultra sonique"},
    [342] = {id=342,en="Rod Retriever",ja="勝訴の支援者",de="Angelzieher",fr="Défenseur des lésés"},
    [343] = {id=343,en="Deed Verifier",ja="千骸谷の逃亡者",de="Urkundenprüfer",fr="Vérificateur d'acte de propriété"},
    [344] = {id=344,en="Chocobo Love Guru",ja="チョコボの愛を解いた者",de="Chocobo-Liebesguru",fr="Ambassadeur des amours chocobos"},
    [345] = {id=345,en="Pick-up Artist",ja="ナンパな愛を解いた者",de="Aufsammelkünstler",fr="Sycophante des amours légères"},
    [346] = {id=346,en="Trash Collector",ja="ニィジャンスカルッヘープ",de="Müllsammler",fr="Eboueur"},
    [347] = {id=347,en="Ancient Flame Follower",ja="古のほむらに触れし者",de="Alter Flammenanhänger",fr="Disciple de la Flamme antique"},
    [348] = {id=348,en="Tavnazian Traveler",ja="聖者の島を訪れし者",de="Tavnazia-Tourist",fr="Voyageur à Tavnazia"},
    [349] = {id=349,en="Transient Dreamer",ja="うたかたなる夢を見し者",de="Vergänglicher Träumer",fr="Rêveur de passage"},
    [350] = {id=350,en="The Lost One",ja="迷いに心揺れし者",de="Der Verlorene",fr="Egaré"},
    [351] = {id=351,en="Treader of an Icy Past",ja="凍てつく過去を踏みしめる者",de="Reisender einer eisigen Vergangenheit",fr="Traceur d'un passé de glace"},
    [352] = {id=352,en="Branded by Lightning",ja="いかづちの洗礼を受けし者",de="Vom Blitz gebrandmarkt",fr="Marqué par la foudre"},
    [353] = {id=353,en="Seeker of the Light",ja="眩き世界を求むる者",de="Suchender des Lichts",fr="Chercheur de la lumière"},
    [354] = {id=354,en="Dead Body",ja="どざえもん",de="Leiche",fr="Cadavre"},
    [355] = {id=355,en="Frozen Dead Body",ja="ドザえもん",de="Gefrorene Leiche",fr="Cadavre gelé"},
    [356] = {id=356,en="Dreambreaker",ja="夢を断つ者",de="Traumbrecher",fr="Briseur de rêves"},
    [357] = {id=357,en="Mist Melter",ja="龍に応える者",de="Nebelschmelzer",fr="Dissipateur de brume"},
    [358] = {id=358,en="Delta Enforcer",ja="デルタを狩る者",de="Delta-Vollstrecker",fr="Prédateur de Delta"},
    [359] = {id=359,en="Omega Ostracizer",ja="オメガになる者",de="Omega-Ächter",fr="Successeur d'Omega"},
    [360] = {id=360,en="Ultima Undertaker",ja="アルテマになる者",de="Ultima-Bestatter",fr="Successeur d'Ultima"},
    [361] = {id=361,en="Ulmia's Soulmate",ja="ウルミアの理解者",de="Ulmias Seelenfreund",fr="Ame sœur d'Ulmia"},
    [362] = {id=362,en="Tenzen's Ally",ja="テンゼンの盟友",de="Tenzens Verbündeter",fr="Allié de Tenzen"},
    [363] = {id=363,en="Companion of Louverance",ja="ルーヴランスの友人",de="Kamerad von Louverance",fr="Compagnon de Louverance"},
    [364] = {id=364,en="True Companion of Louverance",ja="真のルーヴランスの友人",de="Wahrer Kamerad von Louverance",fr="Vrai compagnon de Louverance"},
    [365] = {id=365,en="Prishe's Buddy",ja="プリッシュの同志",de="Prishes Kumpel",fr="Copain de Prishe"},
    [366] = {id=366,en="Nag'molada's Underling",ja="ナグモラーダのなじみ",de="Nag'moladas Untergebener",fr="Sous-fifre de Nag'molada"},
    [367] = {id=367,en="Esha'ntarl's Comrade in Arms",ja="エシャンタールの戦友",de="Esha'ntarls Gefährte",fr="Compagnon d'armes d'Esha'ntarl"},
    [368] = {id=368,en="The Chebukkis' Worst Nightmare",ja="タルタル3人組の天敵",de="Der schlimmste Albtraum der Chebukkis",fr="Pire cauchemar des Chebukkis"},
    [369] = {id=369,en="Brown Mage Guinea Pig",ja="はらへにゃー",de="Braunmagier-Versuchskaninchen",fr="Cobaye du mage brun"},
    [370] = {id=370,en="Brown Magic By-Product",ja="はらピーゴロ",de="Braunmagier-Nebenprodukt",fr="Sous-produit du mage brun"},
    [371] = {id=371,en="Bastok's Second Best Dressed",ja="ベスト・オブ・サブリスト",de="Bastoks Zweitbest-Bekleideter",fr="Deuxième élégant de Bastok"},
    [372] = {id=372,en="Rookie Hero Instructor",ja="冒険初心者の師匠",de="Anfängerheld-Lehrer",fr="Instructeur de héros débutant"},
    [373] = {id=373,en="Goblin in Disguise",ja="ゴブリン人間",de="Verkleideter Goblin",fr="Goblin déguisé"},
    [374] = {id=374,en="Apostate for Hire",ja="雇われ背信者",de="Abtrünniger zu vermieten",fr="Apostat à louer"},
    [375] = {id=375,en="Talks with Tonberries",ja="残党の標的",de="Gespräche mit Tonberries",fr="Parle aux Tonberrys"},
    [376] = {id=376,en="Rook Buster",ja="ルーク・バスター",de="Gaunermeister",fr="Briseur de tours"},
    [377] = {id=377,en="Banneret",ja="バナレット",de="Bannerherr",fr="Banneret"},
    [378] = {id=378,en="Gold Balli☆☆☆☆star",ja="ゴールド・バリ☆☆☆☆スター",de="Goldener Balli☆☆☆☆star",fr="Balli☆☆☆☆star d'or"},
    [379] = {id=379,en="Mythril Balli☆☆☆star",ja="ミスリル・バリ☆☆☆スター",de="Mithril-Balli☆☆☆star",fr="Balli☆☆☆star de mithril"},
    [380] = {id=380,en="Silver Balli☆☆star",ja="シルバー・バリ☆☆スター",de="Silberner Balli☆☆star",fr="Balli☆☆star d'argent"},
    [381] = {id=381,en="Bronze Balli☆star",ja="ブロンズ・バリ☆スター",de="Bronze-Balli☆star",fr="Balli☆star de bronze"},
    [382] = {id=382,en="Searing★Star",ja="灼熱の★軍星",de="Sengender★Stern",fr="Etoile★incandescente"},
    [383] = {id=383,en="Striking★Star",ja="剛勇の★行星",de="Auffälliger★Stern",fr="Etoile★frappante"},
    [384] = {id=384,en="Soothing★Star",ja="白銀の★明星",de="Beruhigender★Stern",fr="Etoile★apaisante"},
    [385] = {id=385,en="Sable★Star",ja="黒衣の★巨星",de="Finsterer★Stern",fr="Etoile★obscure"},
    [386] = {id=386,en="Scarlet★Star",ja="赤心の★暁星",de="Scharlachroter★Stern",fr="Etoile★écarlate"},
    [387] = {id=387,en="Sonic★Star",ja="疾風の★流星",de="Schall-★Stern",fr="Etoile★sonique"},
    [388] = {id=388,en="Saintly★Star",ja="名誉の★瑞星",de="Heiliger★Stern",fr="Etoile★sacrée"},
    [389] = {id=389,en="Shadowy★Star",ja="無情の★将星",de="Schattiger★Stern",fr="Etoile★d'ombre"},
    [390] = {id=390,en="Savage★Star",ja="百獣の★群星",de="Wilder★Stern",fr="Etoile★sauvage"},
    [391] = {id=391,en="Singing★Star",ja="博愛の★極星",de="Singender★Stern",fr="Etoile★chantante"},
    [392] = {id=392,en="Sniping★Star",ja="神速の★彗星",de="Hinterhältiger★Stern",fr="Etoile★chasseresse"},
    [393] = {id=393,en="Slicing★Star",ja="万夫の★魁星",de="Schneidender★Stern",fr="Etoile★tranchante"},
    [394] = {id=394,en="Sneaking★Star",ja="雲影の★妖星",de="Gemeiner★Stern",fr="Etoile★furtive"},
    [395] = {id=395,en="Spearing★Star",ja="竜座の★双星",de="Durchbohrender★Stern",fr="Etoile★perforante"},
    [396] = {id=396,en="Summoning★Star",ja="夢幻の★遊星",de="Beschwörender★Stern",fr="Etoile★invocatrice"},
    [397] = {id=397,en="Putrid Purveyor of Pungent Petals",ja="ちょっと臭う人",de="Fauliger Lieferant stark riechender Blüten",fr="Fournisseur putride de pétales virulents"},
    [398] = {id=398,en="Unquenchable Light",ja="花散る嵐起こす者",de="Unlöschbares Licht",fr="Lumière inextinguible"},
    [399] = {id=399,en="Ballistager",ja="バリステイジャー",de="Ballista-Erfahrener",fr="Organisateur de Ballista"},
    [400] = {id=400,en="Ultimate Champion of the World",ja="天下無双魔阿斗戦覇者",de="Ultimativer Weltmeister",fr="Champion du monde suprême"},
    [401] = {id=401,en="Warrior of the Crystal",ja="クリスタルの戦士",de="Krieger des Kristalls",fr="Guerrier du Cristal"},
    [402] = {id=402,en="Indomitable Fisher",ja="釣神流免許皆伝",de="Unbeugsamer Fischer",fr="Pêcheur indomptable"},
    [403] = {id=403,en="Averter of the Apocalypse",ja="世界の終わりを繰る者",de="Abwender der Apokalypse",fr="Détourneur de l'Apocalypse"},
    [404] = {id=404,en="Banisher of Emptiness",ja="虚ろなる闇に涙する者",de="Verbanner des Nichts",fr="Bannisseur du néant"},
    [405] = {id=405,en="Random Adventurer",ja="適当な冒険者",de="Willkürlicher Abenteurer",fr="Aventurier négligent"},
    [406] = {id=406,en="Irresponsible Adventurer",ja="いい加減な冒険者",de="Verantwortungsloser Abenteurer",fr="Aventurier irresponsable"},
    [407] = {id=407,en="Odorous Adventurer",ja="生臭冒険者",de="Wohlriechender Abenteurer",fr="Aventurier odorant"},
    [408] = {id=408,en="Insignificant Adventurer",ja="歌う価値もない冒険者",de="Unbedeutender Abenteurer",fr="Aventurier insignifiant"},
    [409] = {id=409,en="Final Balli☆☆☆☆star",ja="ファイナバリ☆☆☆☆スター",de="Letzter Balli☆☆☆☆star",fr="Balli☆☆☆☆star final"},
    [410] = {id=410,en="Balli☆☆☆☆star Royale",ja="バリ☆☆☆☆スター・ロワイヤル",de="Balli☆☆☆☆star Royale",fr="Balli☆☆☆☆star royal"},
    [411] = {id=411,en="Destined Fellow",ja="導となる者",de="Auserwählter Begleiter",fr="Personne destinée"},
    [412] = {id=412,en="Orcish Serjeant",ja="オーキシュサージェント",de="Orcish-Sergeant",fr="Orcish Serjeant"},
    [413] = {id=413,en="Bronze Quadav",ja="ブロンズクゥダフ",de="Bronze-Quadav",fr="Bronze Quadav"},
    [414] = {id=414,en="Yagudo Initiate",ja="ヤグードイニシエート",de="Yagudo-Initiate",fr="Yagudo Initiate"},
    [415] = {id=415,en="Moblin Kinsman",ja="モブリンキンズマン",de="Moblin-Kinsman",fr="Compagnon moblin"},
    [416] = {id=416,en="Sin Hunter Hunter",ja="決闘の勝利者",de="Jäger des Sündenjägers",fr="Chasseur de chasseuses du péché"},
    [417] = {id=417,en="Disciple of Justice",ja="正義の勝利者",de="Jünger des Rechts",fr="Disciple de la justice"},
    [418] = {id=418,en="Monarch Linn Patrol Guard",ja="帝龍の飛泉調査員",de="Königsfall-Forscher",fr="Patrouilleur du précipice du monarque"},
    [419] = {id=419,en="Team Player",ja="志を共にせし者",de="Hüter des Teamgeists",fr="As du travail d'équipe"},
    [420] = {id=420,en="Worthy of Trust",ja="心の糧となりし者",de="Vertrauter der Seele",fr="Digne de confiance"},
    [421] = {id=421,en="Conqueror of Fate",ja="人の系譜を開く者",de="Eroberer des Schicksals",fr="Conquérant du destin"},
    [422] = {id=422,en="Breaker of the Chains",ja="呪縛を葬りし者",de="Kettenbrecher",fr="Briseur de chaînes"},
    [423] = {id=423,en="A Friend Indeed",ja="助け合う者",de="Rettende Hand",fr="Un véritable ami"},
    [424] = {id=424,en="Heir to the Realm of Dreams",ja="夢渡る力の継承者",de="Erbe des Königreichs der Träume",fr="Héritier du royaume des rêves"},
    [425] = {id=425,en="Gold Hook",ja="ゴールドフック",de="Goldhaken",fr="Crochet d'or"},
    [426] = {id=426,en="Mythril Hook",ja="ミスリルフック",de="Mithrilhaken",fr="Crochet de mithril"},
    [427] = {id=427,en="Silver Hook",ja="シルバーフック",de="Silberhaken",fr="Crochet d'argent"},
    [428] = {id=428,en="Copper Hook",ja="カッパーフック",de="Kupferhaken",fr="Crochet de cuivre"},
    [430] = {id=430,en="Dynamis-Valkurm Interloper",ja="デュナミス～バルクルムの踏破者",de="Eindringling nach Dynamis - Valkurm",fr="Explorateur de Dynamis - Valkurm"},
    [431] = {id=431,en="Dynamis-Buburimu Interloper",ja="デュナミス～ブブリムの踏破者",de="Eindringling nach Dynamis - Buburimu",fr="Explorateur de Dynamis - Buburimu"},
    [432] = {id=432,en="Dynamis-Qufim Interloper",ja="デュナミス～クフィムの踏破者",de="Eindringling nach Dynamis - Qufim",fr="Explorateur de Dynamis - Qufim"},
    [433] = {id=433,en="Dynamis-Tavnazia Interloper",ja="デュナミス～タブナジアの踏破者",de="Eindringling nach Dynamis - Tavnazia",fr="Explorateur de Dynamis - Tavnazia"},
    [434] = {id=434,en="Confronter of Nightmares",ja="悪夢ヲ喰らい合ウ者",de="Albtraum-Konfrontierer",fr="Braveur de cauchemars"},
    [435] = {id=435,en="Disturber of Slumber",ja="目覚めしかんなぎ",de="Schlafstörer",fr="Troubleur du sommeil"},
    [436] = {id=436,en="Interrupter of Dreams",ja="眠り浅きまれびと",de="Traumunterbrecher",fr="Interrupteur de rêves"},
    [437] = {id=437,en="Sapphire★Star",ja="青雲の★客星",de="Saphir★star",fr="Etoile★saphir"},
    [438] = {id=438,en="Surging★Star",ja="四海の★奔星",de="Fluten★star",fr="Etoile★déferlante"},
    [439] = {id=439,en="Swaying★Star",ja="志操の★連星",de="Macht★star",fr="Etoile★automatique"},
    [440] = {id=440,en="Dark Resistant",ja="冥闇への抵抗者",de="Widersacher der Finsternis",fr="Opposant aux ténèbres"},
    [441] = {id=441,en="Bearer of the Mark of Zahak",ja="双頭蛇の印背負いしモノ",de="Träger des Zeichens des Zahak",fr="Porteur de la marque de Zahak"},
    [442] = {id=442,en="Seagull Phratrie Crew Member",ja="海猫党クルー",de="Mitglied der Seemöwen-Bande",fr="Membre d'équipage de la Phratrie du Goéland"},
    [443] = {id=443,en="Proud Automaton Owner",ja="からくりオーナー",de="Stolzer Automaten-Besitzer",fr="Propriétaire d'un automate"},
    [444] = {id=444,en="Private Second Class",ja="山猫二等傭兵",de="Gefreiter Zweiter Klasse",fr="Soldat seconde classe"},
    [445] = {id=445,en="Private First Class",ja="山猫一等傭兵",de="Gefreiter Erster Klasse",fr="Soldat première classe"},
    [446] = {id=446,en="Superior Private",ja="山猫上等傭兵",de="Untergefreiter",fr="Soldat supérieur"},
    [447] = {id=447,en="Wildcat Publicist",ja="山猫宣伝員",de="Wildkatzen-Werbeträger",fr="Publicitaire du Chat sauvage"},
    [448] = {id=448,en="Adamantking Usurper",ja="アダマントキング　ユザーパー",de="Adamantking-Usurpator",fr="Usurpateur d'Adamantking"},
    [449] = {id=449,en="Overlord Overthrower",ja="オーバーロード　オーバースロワー",de="Overlord-Bezwinger",fr="Renverseur d'Overlord"},
    [450] = {id=450,en="Deity Debunker",ja="デイティーデバンカー",de="Gottheiten-Entlarver",fr="Démystificateur"},
    [451] = {id=451,en="Fafnir Slayer",ja="ファヴニル　スレーヤー",de="Fafnir-Totschläger",fr="Tueur de Fafnir"},
    [452] = {id=452,en="Aspidochelone Sinker",ja="アスピドケロン　シンカー",de="Aspidochelone-Versenker",fr="Couleur d'Aspidochelone"},
    [453] = {id=453,en="Nidhogg Slayer",ja="ニーズヘッグ　スレーヤー",de="Nidhogg-Totschläger",fr="Tueur de Nidhogg"},
    [454] = {id=454,en="Maat Masher",ja="マート　マッシャー",de="Maat-Stampfer",fr="Ecraseur de Maat"},
    [455] = {id=455,en="Kirin Captivator",ja="キリン　キャプティヴェイター",de="Kirin-Fessler",fr="Captureur de Kirin"},
    [456] = {id=456,en="Cactrot Desacelerador",ja="カクトロット　デサセレラドール",de="Cactrot Desacelerador",fr="Ralentisseur de Cactrot"},
    [457] = {id=457,en="Lifter of Shadows",ja="リフター　オブ　シャドーズ",de="Enthüller der Schatten",fr="Leveur d'ombres"},
    [458] = {id=458,en="Tiamat Trouncer",ja="ティアマット　トラウンサー",de="Tiamat-Prügler",fr="Cogneur de Tiamat"},
    [459] = {id=459,en="Vrtra Vanquisher",ja="ヴリトラ　ヴァンクィシャー",de="Vrtra-Überwältiger",fr="Vainqueur de Vrtra"},
    [460] = {id=460,en="World Serpent Slayer",ja="ワールドサーペントスレーヤー",de="Weltschlangen-Totschläger",fr="Tueur du serpent du monde"},
    [461] = {id=461,en="Xolotl Xtrapolator",ja="ショロトル　エクストラポレーター",de="Xolotl-Xtrapolator",fr="Extrapolateur de Xolotl"},
    [462] = {id=462,en="Boroka Beleaguerer",ja="ボロカ　ベリーガラー",de="Boroka-Belagerer",fr="Triomphateur de Boroka"},
    [463] = {id=463,en="Ouryu Overwhelmer",ja="應龍調伏猛士",de="Ouryu-Überwältiger",fr="Tueur d'Ouryu"},
    [464] = {id=464,en="Vinegar Evaporator",ja="ビネガーエヴァポレーター",de="Essigverdunster",fr="Evaporateur de vinaigre"},
    [465] = {id=465,en="Virtuous Saint",ja="ヴァーチャスセイント",de="Virtuoser Heiliger",fr="Saint vertueux"},
    [466] = {id=466,en="Bye-bye, Taisai",ja="さよなら太歳",de="Lebe wohl, Taisai",fr="Au revoir, Taisai"},
    [467] = {id=467,en="Temenos Liberator",ja="テメナスリバレーター",de="Temenos-Befreier",fr="Libérateur de Temenos"},
    [468] = {id=468,en="Apollyon Ravager",ja="アポリオンラベジャー",de="Verwüster Apollyons",fr="Ravageur d'Apollyon"},
    [469] = {id=469,en="Wyrm Astonisher",ja="ウィルムアストニシャー",de="Wyrm-Schreck",fr="Stupéfieur de wyrm"},
    [470] = {id=470,en="Nightmare Awakener",ja="ナイトメア　アウェイクナー",de="Der Albtraum-Erwecker",fr="Eveilleur de cauchemar"},
    [471] = {id=471,en="Cerberus Muzzler",ja="ケルベロスマズラー",de="Cerberus-Bändiger",fr="Museleur de Cerberus"},
    [472] = {id=472,en="Hydra Headhunter",ja="ハイドラヘッドハンター",de="Hydra-Kopfgeldjäger",fr="Chasseur de tête d'Hydra"},
    [473] = {id=473,en="Shining Scale Rifler",ja="スケールライフラー",de="Schuppenplünderer",fr="Agitateur des Ecailles brillantes"},
    [474] = {id=474,en="Troll Subjugator",ja="トロールサブジュゲーター",de="Troll-Unterjocher",fr="Dominateur de trolls"},
    [475] = {id=475,en="Gorgonstone Sunderer",ja="ゴーゴンストーンサンダラー",de="Gorgonstone-Spalter",fr="Ecarteleur de gorgone"},
    [476] = {id=476,en="Khimaira Carver",ja="キマイラカーバー",de="Khimaira-Killer",fr="Equarrisseur de khimaira"},
    [477] = {id=477,en="Elite Einherjar",ja="エインヘリヤルエリート",de="Einheriar-Elite",fr="Elite Einherjar"},
    [478] = {id=478,en="Star Charioteer",ja="スターチャリオッティア",de="Stern-Streitwagenlenker",fr="Aurige des étoiles"},
    [479] = {id=479,en="Sun Charioteer",ja="サンチャリオッティア",de="Sonnen-Streitwagenlenker",fr="Aurige du soleil"},
    [480] = {id=480,en="Subduer of the Mamool Ja",ja="マムークサブドゥア",de="Mamool Ja-Bezwinger",fr="Conquérant des Mamool Ja"},
    [481] = {id=481,en="Subduer of the Trolls",ja="ハルブーンサブドゥア",de="Troll-Bezwinger",fr="Conquérant des Trolls"},
    [482] = {id=482,en="Subduer of the Undead Swarm",ja="アンデッドサブドゥア",de="Untoten-Bezwinger",fr="Conquérant de la Légion des Morts-Vivants"},
    [483] = {id=483,en="Agent of the Allied Forces",ja="アルタナ同盟エージェント",de="Agent der verbündeten Streitkräfte",fr="Agent de la coalition d'Altana"},
    [484] = {id=484,en="Scenic Snapshotter",ja="風景記録の達人",de="Landschaftsbildaufnehmer",fr="Preneur de paysages"},
    [485] = {id=485,en="Branded by the Five Serpents",ja="五蛇の烙印押されしモノ",de="Gezeichnet von den Fünf Schlangen",fr="Marqué des cinq Serpents"},
    [486] = {id=486,en="Immortal Lion",ja="蒼き獅子",de="Unsterblicher Löwe",fr="Lion bleu"},
    [487] = {id=487,en="Paragon of Blue Mage Excellence",ja="冷厳なる大青魔道士",de="Vorbild an Blaumagier-Vortrefflichkeit",fr="Modèle d'excellence du mage bleu"},
    [488] = {id=488,en="Paragon of Corsair Excellence",ja="剛胆なる大海賊",de="Vorbild an Freibeuter-Vortrefflichkeit",fr="Modèle d'excellence du corsaire"},
    [489] = {id=489,en="Paragon of Puppetmaster Excellence",ja="痛快なる大からくり士",de="Vorbild an Puppenmeister-Vortrefflichkeit",fr="Modèle d'excellence du marionnettiste"},
    [490] = {id=490,en="Lance Corporal",ja="山猫傭兵長",de="Obergefreiter",fr="Sous-caporal"},
    [491] = {id=491,en="Corporal",ja="山猫伍長",de="Hauptgefreiter",fr="Caporal"},
    [492] = {id=492,en="Master of Ambition",ja="慧眼を断つモノ",de="Meister der Ambitionen",fr="Maître de l'ambition"},
    [493] = {id=493,en="Master of Chance",ja="碧海の勝負師",de="Meister des Glücks",fr="Maître de la chance"},
    [494] = {id=494,en="Master of Manipulation",ja="奔放不羈の業人",de="Meister der Manipulation",fr="Expert en manipulation"},
    [495] = {id=495,en="Ovjang's Errand Runner",ja="アヴゼンの小間使い",de="Ovjangs Laufbursche",fr="Larbin d'Ovjang"},
    [496] = {id=496,en="Sergeant",ja="山猫軍曹",de="Sergeant",fr="Sergent"},
    [497] = {id=497,en="Sergeant Major",ja="山猫曹長",de="Obersergeant",fr="Sergent-chef"},
    [498] = {id=498,en="Karababa's Tour Guide",ja="カラババの現地ガイド",de="Karababas Stadtführer",fr="Guide de Karababa"},
    [499] = {id=499,en="Karababa's Bodyguard",ja="カラババのボディガード",de="Karababas Leibwächter",fr="Garde du corps de Karababa"},
    [500] = {id=500,en="Karababa's Secret Agent",ja="カラババの特命エージェント",de="Karababas Spion",fr="Agent secret de Karababa"},
    [501] = {id=501,en="Skyserpent Aggrandizer",ja="天蛇将の遊撃隊",de="Himmelsschlangen-Held",fr="Soldat du Serpent Céleste"},
    [502] = {id=502,en="Chief Sergeant",ja="山猫特務曹長",de="Feldwebel",fr="Sergent-major"},
    [503] = {id=503,en="Aphmau's Mercenary",ja="アフマウの傭兵",de="Aphmaus Söldner",fr="Mercenaire d'Aphmau"},
    [504] = {id=504,en="Nashmeira's Mercenary",ja="ナシュメラの傭兵",de="Nashmeiras Söldner",fr="Mercenaire de Nashmeira"},
    [505] = {id=505,en="Chocorookie",ja="チョコボレースのルーキー",de="Chocobo-Rennen-Amateur",fr="Novice des courses de chocobo"},
    [506] = {id=506,en="Second Lieutenant",ja="山猫少尉",de="Oberfeldwebel",fr="Sous-lieutenant"},
    [507] = {id=507,en="Galeserpent Guardian",ja="風蛇将の教導隊",de="Sturmschlangen-Kamerad",fr="Conseiller du Général du Serpent du Vent"},
    [508] = {id=508,en="Stoneserpent Shocktrooper",ja="土蛇将の突撃隊",de="Steinschlangen-SEK-Beamter",fr="Soldat du Général du Serpent de Terre"},
    [509] = {id=509,en="Photopticator Operator",ja="バラカフ発明品の使い手",de="Balakafs Kamera-Assi",fr="Utilisateur des inventions de Balakaf"},
    [510] = {id=510,en="Salaheem's Risk Assessor",ja="サラヒムの斥候",de="Salaheems Späher",fr="Eclaireur des Sentinelles"},
    [511] = {id=511,en="Treasure Trove Tender",ja="財宝の番兵",de="Schatzwächter",fr="Trésorier"},
    [512] = {id=512,en="Gessho's Mercy",ja="月照の介錯人",de="Gesshos Sekundant",fr="Juge de Gessho"},
    [513] = {id=513,en="Emissary of the Empress",ja="聖皇の密使",de="Kaiserlicher Geheimbote",fr="Emissaire de l'Impératrice"},
    [514] = {id=514,en="Endymion Paratrooper",ja="エンディミオン空艇隊員",de="Crewmitglied der Endymion",fr="Parachutiste de l'Endymion"},
    [515] = {id=515,en="Naja's Comrade-In-Arms",ja="ナジャの戦友",de="Najas Waffenbruder",fr="Compagnon d'armes de Naja"},
    [516] = {id=516,en="Nashmeira's Loyalist",ja="ナシュメラの腹心",de="Nashmeiras Busenfreund",fr="Fidèle de Nashmeira"},
    [517] = {id=517,en="Preventer of Ragnarok",ja="ラグナロクの調停者",de="Abwender der Ragnarök",fr="Juge du Ragnarok"},
    [518] = {id=518,en="Champion of Aht Urhgan",ja="アトルガンの守護者",de="Aht Urhgans Schutzpatron",fr="Protecteur d'Aht Urhgan"},
    [519] = {id=519,en="First Lieutenant",ja="山猫中尉",de="Leutnant",fr="Lieutenant"},
    [520] = {id=520,en="Captain",ja="山猫大尉",de="Oberleutnant",fr="Capitaine"},
    [521] = {id=521,en="Crystal Stakes Cupholder",ja="クリスタルステークス覇者",de="Meister des Kristallrennens",fr="Champion du Prix du Cristal"},
    [522] = {id=522,en="Winning Owner",ja="勝鳥オーナー",de="Stolzer Besitzer eines Siegerhuhns",fr="Eleveur de gagnants"},
    [523] = {id=523,en="Victorious Owner",ja="猛鳥オーナー",de="Stolzer Besitzer eines Raubvogels",fr="Eleveur de vainqueurs"},
    [524] = {id=524,en="Triumphant Owner",ja="覇鳥オーナー",de="Stolzer Besitzer eines blaublütigen Huhns",fr="Eleveur de champions"},
    [525] = {id=525,en="High Roller",ja="幸運の勝負師",de="Glückskind",fr="Turfiste chanceux"},
    [526] = {id=526,en="Fortune's Favorite",ja="強運の勝負師",de="Glückspilz",fr="Turfiste d'une chance insolente"},
    [527] = {id=527,en="Superhero",ja="スーパーヒーロー",de="Superheld",fr="Super héros"},
    [528] = {id=528,en="Superheroine",ja="スーパーヒロイン",de="Superheldin",fr="Super héroïne"},
    [529] = {id=529,en="Bloody Berserker",ja="ブラッディバーサーカー",de="Blutrünstiger Berserker",fr="Berserk sanguinaire"},
    [530] = {id=530,en="The Sixth Serpent",ja="准蛇将",de="Schlangengeneral ehrenhalber",fr="Le sixième Serpent"},
    [531] = {id=531,en="Eternal Mercenary",ja="エターナルマーシナリー",de="Söldner lebenslänglich",fr="Eternel mercenaire"},
    [532] = {id=532,en="Springserpent Sentry",ja="水蛇将の親衛隊",de="Wasserschlangen-Leibwächter",fr="Garde du Général du Serpent de l'Eau"},
    [533] = {id=533,en="Sprightly★Star",ja="魅惑の★眩星",de="Verführerischer★Stern",fr="Etoile★ensorcelante"},
    [534] = {id=534,en="Sagacious★Star",ja="明哲の★識星",de="Weiser★Stern",fr="Etoile★philosophique"},
    [535] = {id=535,en="Schultz Scholar",ja="見習い軍学者",de="Student",fr="Apprenti stratège"},
    [536] = {id=536,en="Knight of the Iron Ram",ja="鉄羊騎士",de="Ritter des Eisernen Ram",fr="Bélier d'acier"},
    [537] = {id=537,en="Fourth Division Soldier",ja="第四共和軍団兵",de="Soldat der 4. Armee der Republik",fr="Soldat de la quatrième division républicaine"},
    [538] = {id=538,en="Cobra Unit Mercenary",ja="コブラ傭兵",de="Kobra-Söldner",fr="Mercenaire Cobra"},
    [539] = {id=539,en="Windtalker",ja="舞台裏の目撃者",de="Deus ex machina",fr="Révélateur de supercherie"},
    [540] = {id=540,en="Lady Killer",ja="レディキラー",de="Lady(bug)killer",fr="Dépouilleur de bêtes à bon dieu"},
    [541] = {id=541,en="Troupe Brilioth Dancer",ja="ブリリオート舞踏団ダンサー",de="Brilioths Primaballerina",fr="Petit rat de la troupe Brilioth"},
    [542] = {id=542,en="Cait Sith's Assistant",ja="ケット・シーの助手",de="Cait Sith' Helfer",fr="Aide de Cait Sith"},
    [543] = {id=543,en="Ajido-Marujido's Minder",ja="アジドマルジドの救世主",de="Ajido-Marujidos Erziehungsberechtigter",fr="Messie d'Ajido-Marujido"},
    [544] = {id=544,en="Comet Charioteer",ja="コメットチャリオッティア",de="Kometen-Streitwagenlenker",fr="Aurige des comètes"},
    [545] = {id=545,en="Moon Charioteer",ja="ムーンチャリオッティア",de="Mond-Streitwagenlenker",fr="Aurige de la lune"},
    [546] = {id=546,en="Sandworm Wrangler",ja="サンドウォームキャッチャー",de="Sandworm-Fänger",fr="Chevaucheur de ver des sables"},
    [547] = {id=547,en="Ixion Hornbreaker",ja="イクシオンホーンブレイカー",de="Ixion-Flüsterer",fr="Arracheur de la corne d'Ixion"},
    [548] = {id=548,en="Lambton Worm Desegmenter",ja="ラムトンウォームデセグメンター",de="Lambton-Entwurmer",fr="Dessegmenteur de ver"},
    [549] = {id=549,en="Pandemonium Queller",ja="パンデモニウムクウェラー",de="Pandemonium-Entwirrer",fr="Apaiseur du Pandémonium"},
    [550] = {id=550,en="Debaser of Dynasties",ja="ダイナスティディベーサー",de="Dynastien-Stürzer",fr="Annihilateur de dynastie"},
    [551] = {id=551,en="Disperser of Darkness",ja="ダークネスディスパーサー",de="Dämmerlichtbringer",fr="Disperseur des ténèbres"},
    [552] = {id=552,en="Ender of Idolatry",ja="アイドラトリーエンダー",de="Götzenbild-Zerkauer",fr="Iconoclaste"},
    [553] = {id=553,en="Lugh Exorcist",ja="ルー　エクソシスト",de="Lugh-Exorzist",fr="Conjurateur de Lugh"},
    [554] = {id=554,en="Elatha Exorcist",ja="エラサ　エクソシスト",de="Elatha-Exorzist",fr="Conjurateur d'Elatha"},
    [555] = {id=555,en="Ethniu Exorcist",ja="エスニウ　エクソシスト",de="Ethniu-Exorzist",fr="Conjurateur d'Ethniu"},
    [556] = {id=556,en="Tethra Exorcist",ja="テスラ　エクソシスト",de="Tethra-Exorzist",fr="Conjurateur de Tethra"},
    [557] = {id=557,en="Buarainech Exorcist",ja="ブーリンナク　エクソシスト",de="Buarainech-Exorzist",fr="Conjurateur de Buarainech"},
    [558] = {id=558,en="Oupire Impaler",ja="ウピール　インペーラー",de="Oupire-Pfähler",fr="Empaleur d'Oupire"},
    [559] = {id=559,en="Scylla Skinner",ja="スキュラ　スキンナー",de="Scylla-Häuter",fr="Dépeceur de Scylla"},
    [560] = {id=560,en="Zirnitra Wingclipper",ja="ジルニトラ　ウィングクリッパー",de="Zirnitra-Flügelstutzer",fr="Trancheur d'ailes de Zirnitra"},
    [561] = {id=561,en="Dawon Trapper",ja="ドゥントラッパー",de="Dawon-Wilderer",fr="Piégeur de Dawon"},
    [562] = {id=562,en="Krabkatoa Steamer",ja="クラブカタウ　スチーマー",de="Krabkatoa-Dünster",fr="Erupteur du Krabkatoa"},
    [563] = {id=563,en="Orcus Trophy Hunter",ja="オルクス　トロフィーハンター",de="Orcus-Trophäenjäger",fr="Chasseur de trophée d'Orcus"},
    [564] = {id=564,en="Blobdingnag Burster",ja="ブロブディンナグ　バースター",de="Blobdingnag-Sprenger",fr="Perceur de Blobdingnag"},
    [565] = {id=565,en="Verthandi Ensnarer",ja="ヴェルザンディ　エンスネアラー",de="Verthandi-Verführer",fr="Attrapeur de Verthandi"},
    [566] = {id=566,en="Ruthven Entomber",ja="ルスベン　エントゥーマー",de="Ruthven-Bestatter",fr="Fossoyeur de Ruthven"},
    [567] = {id=567,en="Yilbegan Hideflayer",ja="イルベガン　ハイドフレーヤー",de="Yilbegan-Häuter",fr="Mégisseur de Yilbegan"},
    [568] = {id=568,en="Torchbearer of the 1st Walk",ja="第1ウォークのトーチベアラー",de="Fackelträger des ersten Ganges",fr="Porteur de la torche du premier promenoir"},
    [569] = {id=569,en="Torchbearer of the 2nd Walk",ja="第2ウォークのトーチベアラー",de="Fackelträger des zweiten Ganges",fr="Porteur de la torche du second promenoir"},
    [570] = {id=570,en="Torchbearer of the 3rd Walk",ja="第3ウォークのトーチベアラー",de="Fackelträger des dritten Ganges",fr="Porteur de la torche du troisième promenoir"},
    [571] = {id=571,en="Torchbearer of the 4th Walk",ja="第4ウォークのトーチベアラー",de="Fackelträger des vierten Ganges",fr="Porteur de la torche du quatrième promenoir"},
    [572] = {id=572,en="Torchbearer of the 5th Walk",ja="第5ウォークのトーチベアラー",de="Fackelträger des fünften Ganges",fr="Porteur de la torche du cinquième promenoir"},
    [573] = {id=573,en="Torchbearer of the 6th Walk",ja="第6ウォークのトーチベアラー",de="Fackelträger des sechsten Ganges",fr="Porteur de la torche du sixième promenoir"},
    [574] = {id=574,en="Torchbearer of the 7th Walk",ja="第7ウォークのトーチベアラー",de="Fackelträger des siebten Ganges",fr="Porteur de la torche du septième promenoir"},
    [575] = {id=575,en="Torchbearer of the 8th Walk",ja="第8ウォークのトーチベアラー",de="Fackelträger des achten Ganges",fr="Porteur de la torche du huitième promenoir"},
    [576] = {id=576,en="Furniture Store Owner",ja="ファーニチャーストアオーナー",de="Möbelhändler",fr="Ebéniste"},
    [577] = {id=577,en="Armory Owner",ja="アーモリーオーナー",de="Waffenschieber",fr="Armurier"},
    [578] = {id=578,en="Jewelry Store Owner",ja="ジュエリーストアオーナー",de="Juwelier",fr="Joaillier"},
    [579] = {id=579,en="Boutique Owner",ja="ブティックオーナー",de="Boutique-Besitzer",fr="Tailleur"},
    [580] = {id=580,en="Apothecary Owner",ja="アポケサリオーナー",de="Apotheker",fr="Apothicaire"},
    [581] = {id=581,en="Curiosity Shop Owner",ja="キュリオシティショップオーナー",de="Krämer",fr="Bimbelotier"},
    [582] = {id=582,en="Shoeshop Owner",ja="シューショップオーナー",de="Schuster",fr="Cordonnier"},
    [583] = {id=583,en="Fishmonger Owner",ja="フィッシュモンガーオーナー",de="Fischhändler",fr="Poissonnier"},
    [584] = {id=584,en="Restaurant Owner",ja="レストランオーナー",de="Restaurantbesitzer",fr="Traiteur"},
    [585] = {id=585,en="Assistant Detective",ja="ミスリル銃士隊探偵助手",de="Mithril-Spürnase",fr="Détective assistant des mousquetaires de mithril"},
    [586] = {id=586,en="Promising Dancer",ja="才気あるダンサー",de="Tanztalent",fr="Coryphée"},
    [587] = {id=587,en="Stardust Dancer",ja="星くずのダンサー",de="Musikliebhaber",fr="Sujet"},
    [588] = {id=588,en="Elegant Dancer",ja="流麗なる大舞踏家",de="Prima-Ballerina",fr="Premier danseur"},
    [589] = {id=589,en="Dazzling Dance Diva",ja="輝く星の踊り子",de="Tänzer des Leuchtenden Sterns",fr="Danseur étoile"},
    [590] = {id=590,en="Friend of Lehko Habhoka",ja="レコ・ハボッカの友人",de="Katzenliebhaber",fr="Ami de Lehko Habhoka"},
    [591] = {id=591,en="Summa Cum Laude",ja="聡明なる大学者",de="Musterschüler",fr="Sage des sages"},
    [592] = {id=592,en="Grimoire Bearer",ja="グリモアを継ぐもの",de="Diplom-Kriegswissenschaftler",fr="Héritier du Grimoire"},
    [593] = {id=593,en="Seasoning Connoisseur",ja="塩ソムリエ",de="Feinschmecker",fr="Expert en cassoulet"},
    [594] = {id=594,en="Fine Young Griffon",ja="少年騎士団のエース",de="Königsgreif",fr="As des jeunes griffons"},
    [595] = {id=595,en="Babban's Traveling Companion",ja="ウェイレアの旅の仲間",de="Mheilleas Reisegefährte",fr="Compagnon de route de Mheillea"},
    [596] = {id=596,en="Fellow Fortifier",ja="高め合う者",de="Duellant",fr="Camarade de duel"},
    [597] = {id=597,en="Chocochampion",ja="チョコボレースのホープ",de="Hoffnung des Chocobo-Rennens",fr="Espoir des courses de chocobos"},
    [598] = {id=598,en="Traverser of Time",ja="往代を巡りし者",de="Per Anhalter durch die Generationen",fr="Argonaute des temps jadis"},
    [599] = {id=599,en="Mythril Musketeer No. 6",ja="ミスリル銃士隊No.6",de="Mithril-Musketier Nr.6",fr="Sixième mousquetaire de mithril"},
    [600] = {id=600,en="Jewel of the Cobra Unit",ja="コブラ傭兵団の秘蔵っ子",de="Königskobra",fr="Atout secret des Mercenaires Cobra"},
    [601] = {id=601,en="Knight of the Swiftwing Griffin",ja="鷲獅子騎士",de="Ritter der Geflügelten Löwen",fr="Chevalier de l'Ordre du griffon"},
    [602] = {id=602,en="Wyrmsworn Protector",ja="気高き龍の盟友",de="Verbündeter des hochehrwürdigen Drachen",fr="Allié du fier dragon"},
    [603] = {id=603,en="Flameserpent Facilitator",ja="炎蛇将の特攻隊",de="Einer, der durchs Feuer geht",fr="Espion du Général du Serpent de Feu"},
    [604] = {id=604,en="Maze Wanderer",ja="迷宮を彷徨う者",de="Sich-im-Irrgarten-Verläufer",fr="Vagabond des labyrinthes"},
    [605] = {id=605,en="Maze Navigator",ja="迷宮を行交う者",de="Irrgarten-Auf-und-Abwanderer",fr="Itinérant des labyrinthes"},
    [606] = {id=606,en="Maze Scholar",ja="迷宮を知る者",de="Sich-im-Irrgarten-Auskenner",fr="Dilettante des labyrinthes"},
    [607] = {id=607,en="Maze Artisan",ja="迷宮を創る者",de="Schöpfer der Irrgärten",fr="Architecte de labyrinthes"},
    [608] = {id=608,en="Maze Overlord",ja="迷宮を統べる者",de="Irrgarten-Monarch",fr="Connétable des labyrinthes"},
    [609] = {id=609,en="Swarminator",ja="スウォーミネーター",de="Schwarminator",fr="Déverminateur"},
    [610] = {id=610,en="Battle of Jeuno Veteran",ja="ジュノ攻防戦の功労者",de="Held von Jeuno",fr="Héros de la bataille de Jeuno"},
    [611] = {id=611,en="Grand Greedalox",ja="ゴウツバクリ",de="Nimmersatt",fr="Ultime gloutox"},
    [612] = {id=612,en="Karaha-Baruha's Research Assistant",ja="隠者の協力者",de="Verbündeter des Eremiten",fr="Collaborateur de l'ermite"},
    [613] = {id=613,en="Honorary Knight of the Cardinal Stag",ja="赤鹿の名誉騎士",de="Geflügelter Löwe",fr="Chevalier honoraire des Cerfs écarlates"},
    [614] = {id=614,en="Detector of Deception",ja="仮面を砕きし者",de="Kommissar",fr="Briseur de masque"},
    [615] = {id=615,en="Silencer of the Echo",ja="神の頌歌に返せる者",de="Auslöscher des kataklystischen Lieds",fr="Eradicateur d'ode divine"},
    [616] = {id=616,en="Bestrider of Futures",ja="境界に生きる者",de="Spiegelweltenwandler",fr="Errant à la frontière des temps"},
    [617] = {id=617,en="Mog House Handyperson",ja="モグハウス・キーパー",de="Mog-Hauswart",fr="Maître Mog"},
    [618] = {id=618,en="Presidential Protector",ja="真実を追う者",de="Sonderermittler",fr="Découvreur de la vérité"},
    [619] = {id=619,en="The Moon's Companion",ja="星月に寄り添う者",de="Eingeweihter der Sterne und des Mondes",fr="Plus près des étoiles et de la lune"},
    [620] = {id=620,en="Arrester of the Ascension",ja="シャントット帝国反乱分子",de="Agent im Auftrag Ihrer Majestät Shantotto",fr="Renégat de l'Empire shantottois"},
    [621] = {id=621,en="House Aurchiat Retainer",ja="伯爵家の客分",de="Rechter Arm des Racheengels",fr="Compagnon d'armes du jeune comte"},
    [622] = {id=622,en="Wanderer of Time",ja="失はれた者",de="Verlorener der Zeit",fr="Perdu dans les abîmes du temps"},
    [623] = {id=623,en="Smiter of the Shadow",ja="シャドウスマイター",de="Schattenzerschmetterer",fr="Jugulateur des ombres"},
    [624] = {id=624,en="Heir of the Blessed Radiance",ja="大いなる天光の継承者",de="Erbe des Großen Lichts",fr="Héritier de la grande lumière"},
    [625] = {id=625,en="Heir of the Blighted Gloom",ja="大いなる冥闇の継承者",de="Erbe der Großen Finsternis",fr="Héritier de la grande ombre"},
    [626] = {id=626,en="Sworn to the Dark Divinity",ja="冥路の騎士",de="Spielkamerad des Dunklen Reiters",fr="Chevalier des Ombres"},
    [627] = {id=627,en="Temperer of Mythril",ja="ミスリル銃士隊No.0",de="Die fantastische Null",fr="Mousquetaire de mithril n°0"},
    [628] = {id=628,en="Star in the Azure Sky",ja="蒼天のしるべ",de="Meister des Azurbogens",fr="Azur du firmament"},
    [629] = {id=629,en="Fangmonger Forestaller",ja="コロッサスデストロイヤー",de="Zogbogs Nemesis",fr="Destructeur de colosse"},
    [630] = {id=630,en="Visitor to Abyssea",ja="異界の訪問者",de="Wallfahrer",fr="Visiteur d'Abyssée"},
    [631] = {id=631,en="Friend of Abyssea",ja="異界の協力者",de="Abysseanischer Aktivist",fr="Coopérateur d'Abyssée"},
    [632] = {id=632,en="Warrior of Abyssea",ja="異界の戦士",de="Abysseanischer Krieger",fr="Combattant d'Abyssée"},
    [633] = {id=633,en="Stormer of Abyssea",ja="異界の強襲者",de="Jäger der Erwachten",fr="Attaquant d'Abyssée"},
    [634] = {id=634,en="Devastator of Abyssea",ja="異界の破壊者",de="Vernichter der Erwachten",fr="Démolisseur d'Abyssée"},
    [635] = {id=635,en="Hero of Abyssea",ja="異界の勇者",de="Hoffnungsträger Abysseas",fr="Brave d'Abyssée"},
    [636] = {id=636,en="Champion of Abyssea",ja="異界の英雄",de="Held Abysseas",fr="Héros d'Abyssée"},
    [637] = {id=637,en="Conqueror of Abyssea",ja="異界の覇者",de="Retter Abysseas",fr="Conquérant d'Abyssée"},
    [638] = {id=638,en="Savior of Abyssea",ja="異界の救世主",de="Legendärer Held Abysseas",fr="Sauveur d'Abyssée"},
    [639] = {id=639,en="Vanquisher of Spite",ja="盤上の覇者",de="Entwirrer Abysseas",fr="Maître de l'échiquier"},
    [640] = {id=640,en="Hadhayosh Halterer",ja="ハダヨッシュホルタラー",de="Hadhayosh-Herr",fr="Dompteur de Hadhayosh"},
    [641] = {id=641,en="Briareus Feller",ja="ブリアレオスフェラー",de="Briareus-Fäller",fr="Abatteur de Briareus"},
    [642] = {id=642,en="Karkinos Clawcrusher",ja="カルキノスクロークラッシャー",de="Karkinos-Scherenschredderer",fr="Briseur des pinces de Karkinos"},
    [643] = {id=643,en="Carabosse Quasher",ja="カラボスクワッシャー",de="Carabosse-Zerklatscher",fr="Ecraseur de Carabosse"},
    [644] = {id=644,en="Ovni Obliterator",ja="オヴニオブリテレイター",de="Ovni-Forscher",fr="Anéantisseur d'Ovni"},
    [645] = {id=645,en="Ruminator Confounder",ja="ルミネイターコンファウンダー",de="Ruminator-Verwirrer",fr="Vainqueur de Ruminator"},
    [646] = {id=646,en="Eccentricity Expunger",ja="エクセントリセティエクスパンジャー",de="Exzentriker",fr="Eradicateur d'excentricité"},
    [647] = {id=647,en="Fistule Drainer",ja="フィスチュルドレイナー",de="Fistule-Ausdrücker",fr="Ponctionneur de Fistule"},
    [648] = {id=648,en="Kukulkan Defanger",ja="ククルカンデファンガー",de="Kukulkan-Zahnzieher",fr="Arracheur de croc de Kukulkan"},
    [649] = {id=649,en="Turul Grounder",ja="トゥルルグラウンダー",de="Turul-Fänger",fr="Terrasseur de Turul"},
    [650] = {id=650,en="Bloodeye Banisher",ja="ブラッドアイバニッシャー",de="Vileberry-Verbanner",fr="Bannisseur de Bloodeye"},
    [651] = {id=651,en="Satiator Depriver",ja="セイシエーターデプライバー",de="Satiator-Enthalter",fr="Dépouilleur de Satiator"},
    [652] = {id=652,en="Iratham Capturer",ja="イラタムキャプチャラー",de="Iratham-Mattsetzer",fr="Preneur d'Iratham"},
    [653] = {id=653,en="Lacovie Capsizer",ja="ラコビキャプサイザー",de="Lacovie-Kenterer",fr="Basculeur de Lacovie"},
    [654] = {id=654,en="Chloris Uprooter",ja="クロリスアップルーター",de="Chloris-Entwurzeler",fr="Déracineur de Chloris"},
    [655] = {id=655,en="Myrmecoleon Tamer",ja="メルメコレオンテイマー",de="Myrmecoleon-Bändiger",fr="Apprivoiseur de Myrmecoleon"},
    [656] = {id=656,en="Glavoid Stampeder",ja="グラヴォイドスタンピーダー",de="Glavoid-Gladiator",fr="Assaillant de Glavoid"},
    [657] = {id=657,en="Usurper Deposer",ja="ユーサーパーデポーザー",de="Usurper-Umstürzer",fr="Déposeur d'Usurper"},
    [658] = {id=658,en="Yaanei Crasher",ja="ヤーネイ　クラッシャー",de="Yaanei-Zermalmer",fr="Briseur de Yaanei"},
    [659] = {id=659,en="Kutharei Unhorser",ja="クタレイ　アンホーサー",de="Kutharei-Bändiger",fr="Désarçonneur de Kutharei"},
    [660] = {id=660,en="Sippoy Capturer",ja="シポイ　キャプチャラー",de="Sippoy-Fänger",fr="Preneur de Sippoy"},
    [661] = {id=661,en="Titlacauan Dismemberer",ja="ティトラカワン　ディスメンベラー",de="Titlacauan-Zerleger",fr="Démembreur de Titlacauan"},
    [662] = {id=662,en="Smok Defogger",ja="ズモク　ディフォッガー",de="Smok-Entnebler",fr="Désenfumeur de Smok"},
    [663] = {id=663,en="Amhuluk Inundater",ja="アムルック　イナンデーター",de="Amhuluk-Ertränker",fr="Noyeur d'Amhuluk"},
    [664] = {id=664,en="Pulverizer Dismantler",ja="パルバライザー　ディスマンテラー",de="Pulverizer-Deaktivierer",fr="Désarmeur de Pulverizer"},
    [665] = {id=665,en="Durinn Deceiver",ja="ドゥリン　ディシーバー",de="Durinn-Täuscher",fr="Dupeur de Durinn"},
    [666] = {id=666,en="Karkadann Exoculator",ja="カーカダン　エクスオキュレーター",de="Karkadann-Blender",fr="Aveugleur de Karkadann"},
    [667] = {id=667,en="Ulhuadshi Desiccator",ja="ウルハドシ　デシケーター",de="Ulhuadshi-Trockner",fr="Dessiccateur d'Ulhuadshi"},
    [668] = {id=668,en="Itzpapalotl Declawer",ja="イツパパロツル　ディクローアー",de="Itzpapalotl-Krallenzieher",fr="Arracheur de griffe d'Itzpapalotl"},
    [669] = {id=669,en="Sobek Mummifier",ja="ソベク　マミファイアー",de="Sobek-Mumifizierer",fr="Momifieur de Sobek"},
    [670] = {id=670,en="Cirein-croin Harpooner",ja="キレイン・キロイン　ハープーナー",de="Cirein-croin-Harpuner",fr="Harponneur de Cirein-croin"},
    [671] = {id=671,en="Bukhis Tetherer",ja="ブッキス　テザラー",de="Bukhis-Anleiner",fr="Atteleur de Bukhis"},
    [672] = {id=672,en="Sedna Tuskbreaker",ja="セドナ　タスクブレーカー",de="Sedna-Zahnbrecher",fr="Briseur de défense de Sedna"},
    [673] = {id=673,en="Cleaver Dismantler",ja="クリーバー　ディスマンテラー",de="Cleaver-Deaktivierer",fr="Désarmeur de Cleaver"},
    [674] = {id=674,en="Executioner Dismantler",ja="エクセキュショナー　ディスマンテラー",de="Executioner-Deaktivierer",fr="Désarmeur d'Executioner"},
    [675] = {id=675,en="Severer Dismantler",ja="セバラー　ディスマンテラー",de="Severer-Deaktivierer",fr="Désarmeur de Severer"},
    [676] = {id=676,en="Lusca Debunker",ja="ルスカ　ディバンカー",de="Lusca-Entlarver",fr="Discréditeur de Lusca"},
    [677] = {id=677,en="Tristitia Deliverer",ja="トリスティシア　デリバラー",de="Tristitia-Befreier",fr="Apaiseur de Tristitia"},
    [678] = {id=678,en="Ketea Beacher",ja="ケテア　ビーチャー",de="Ketea-Strander",fr="Ensableur de Ketea"},
    [679] = {id=679,en="Rani Decrowner",ja="ラーニー　デクラウナー",de="Rani-Entkroner",fr="Découronneur de Rani"},
    [680] = {id=680,en="Orthrus Decapitator",ja="オルトロス　デカピテーター",de="Orthrus-Enthaupter",fr="Décapiteur d'Orthrus"},
    [681] = {id=681,en="Dragua Slayer",ja="ドラグア　スレイヤー",de="Dragua-Schlächter",fr="Pourfendeur de Dragua"},
    [682] = {id=682,en="Bennu Deplumer",ja="ベンヌ　デプルーマー",de="Bennu-Rupfer",fr="Plumeur de Bennu"},
    [683] = {id=683,en="Hedjedjet Destinger",ja="ヘデデット　デスティンガー",de="Hedjedjet-Entstachler",fr="Arracheur de dard de Hedjedjet"},
    [684] = {id=684,en="Cuijatender Desiccator",ja="クイジャテンダー　デシケイター",de="Cuijatender-Austrockner",fr="Dessiccateur de Cuijatender"},
    [685] = {id=685,en="Brulo Extinguisher",ja="ブルーロ　エクスティングイシャー",de="Brulo-Auslöscher",fr="Extincteur de Brulo"},
    [686] = {id=686,en="Pantokrator Disprover",ja="パントクラトル　ディスプルーバー",de="Pantokrator-Widerleger",fr="Réfutateur de Pantokrator"},
    [687] = {id=687,en="Apademak Annihilator",ja="アペデマク　アナイアレーター",de="Apademak-Annihilator",fr="Annihilateur d'Apademak"},
    [688] = {id=688,en="Isgebind Defroster",ja="イスゲビンド　デフロスター",de="Isgebind-Entfroster",fr="Décongeleur d'Isgebind"},
    [689] = {id=689,en="Resheph Eradicator",ja="レシェフ　エラディケイター",de="Resheph-Ausmerzer",fr="Eradicateur de Resheph"},
    [690] = {id=690,en="Empousa Expurgator",ja="エンプーサ　エクスパーゲイター",de="Empousa-Schrubber",fr="Expurgeur d'Empousa"},
    [691] = {id=691,en="Indrik Immolator",ja="インドリック　イモレイター",de="Indrik-Schlächter",fr="Immolateur d'Indrik"},
    [692] = {id=692,en="Ogopogo Overturner",ja="オゴポゴ　オウバーターナー",de="Ogopogo-Trockenleger",fr="Renverseur d'Ogopogo"},
    [693] = {id=693,en="Raja Regicide",ja="ラージャー　レジサイド",de="Raja-Königsmörder",fr="Régicide de Raja"},
    [694] = {id=694,en="Alfard Detoxifier",ja="アルファルド　デトックシファイアー",de="Alfard-Entgifter",fr="Désintoxicateur d'Alfard"},
    [695] = {id=695,en="Azdaja Abolisher",ja="アジュダヤ　アボリシャー",de="Azdaja-Stürzer",fr="Abolisseur d'Azdaja"},
    [696] = {id=696,en="Amphitrite Shucker",ja="アムピトリーテー　シャッカー",de="Amphitrite-Enthülser",fr="Décoquilleur d'Amphitrite"},
    [697] = {id=697,en="Fuath Purifier",ja="フーア　ピュリファイアー",de="Fuath-Läuterer",fr="Purificateur de Fuath"},
    [698] = {id=698,en="Killakriq Excoriator",ja="キラクリック　エクスコリエイター",de="Killakriq-Wundschürfer",fr="Condamnateur de Killakriq"},
    [699] = {id=699,en="Maere Bestirrer",ja="メーア　ベスターラー",de="Maere-Schieber",fr="Adjurateur de Maere"},
    [700] = {id=700,en="Wyrm God Defier",ja="神竜を葬りし者",de="Befreier des Abyssus",fr="Triomphateur de Shinryu"},
    [701] = {id=701,en="Hahava Condemner",ja="ハハヴァ　コンデンマー",de="Hahava-Verdammer",fr="Condamnateur de Hahava"},
    [702] = {id=702,en="Celaeno Silencer",ja="セラエノ　サイレンサー",de="Celaeno-Verstummer",fr="Cloueur de bec de Celaeno"},
    [703] = {id=703,en="Voidwrought Deconstructor",ja="ヴォイドロート　デコンストラクター",de="Voidwrought-Zerleger",fr="Démolisseur de Voidwrought"},
    [704] = {id=704,en="Devourer of Shadows",ja="デバウアー　オブ　シャドーズ",de="Vertilger der Schatten",fr="Dévoreur d'ombres"},
    [705] = {id=705,en="Kaggen Clobberer",ja="カッゲン　クロッバラー",de="Kaggen-Knüppler",fr="Tabasseur de Kaggen"},
    [706] = {id=706,en="Akvan Absterger",ja="アクヴァン　アブスタージャー",de="Akvan-Entschlacker",fr="Abstergeur d'Akvan"},
    [707] = {id=707,en="Pil Unfrocker",ja="フィル　アンフロッカー",de="Pil-Entfracker",fr="Défroqueur de Pil"},
    [708] = {id=708,en="Qilin Contravener",ja="チーリン　コントラビーナー",de="Qilin-Verstoßer",fr="Renieur de Qilin"},
    [709] = {id=709,en="Uptala Reprobator",ja="ウプタラ　レプロベーター",de="Uptala-Verdammer",fr="Réprouveur d'Uptala"},
    [710] = {id=710,en="Aello Abator",ja="アイエロ　アベイター",de="Aello-Dämpfer",fr="Abatteur d'Aello"},
    [711] = {id=711,en="Torchbearer of the 9th Walk",ja="第9ウォークのトーチベアラー",de="Fackelträger des neunten Ganges",fr="Porteur de la torche du neuvième promenoir"},
    [712] = {id=712,en="Torchbearer of the 10th Walk",ja="第10ウォークのトーチベアラー",de="Fackelträger des zehnten Ganges",fr="Porteur de la torche du dixième promenoir"},
    [713] = {id=713,en="Torchbearer of the 11th Walk",ja="第11ウォークのトーチベアラー",de="Fackelträger des elften Ganges",fr="Porteur de la torche du onzième promenoir"},
    [714] = {id=714,en="Nightmare Illuminator",ja="ナイトメア　イルミネーター",de="Nachtmahr-Illuminierer",fr="Illuminateur des cauchemars"},
    [715] = {id=715,en="Gaunab Gutter",ja="ガウナブ　ガッター",de="Gaunab-Röster",fr="Etripeur de Gaunab"},
    [716] = {id=716,en="Kalasutrax Cremator",ja="カラストラクス　クリーメーター",de="Kalasutrax-Kremator",fr="Crémateur de Kalasutrax"},
    [717] = {id=717,en="Ocythoe Overrider",ja="オシトエ　オバーライダー",de="Ocythoe-Überwinder",fr="Neutralisateur d'Ocythoe"},
    [718] = {id=718,en="Ig-Alima Inhumer",ja="イッグ・アリマ　インヒューマー",de="Ig-Alima-Beisetzer",fr="Inhumateur d'Ig-Alima"},
    [719] = {id=719,en="Botulus Rex Engorger",ja="ボチュルス・レックス　エンゴージャー",de="Botulus Rex-Verschlinger",fr="Avaleur de Botulus Rex"},
    [720] = {id=720,en="Torchbearer of the 12th Walk",ja="第12ウォークのトーチベアラー",de="Fackelträger des zwölften Ganges",fr="Porteur de la torche du douzième promenoir"},
    [721] = {id=721,en="Torchbearer of the 13th Walk",ja="第13ウォークのトーチベアラー",de="Fackelträger des dreizehnten Ganges",fr="Porteur de la torche du treizième promenoir"},
    [722] = {id=722,en="Torchbearer of the 14th Walk",ja="第14ウォークのトーチベアラー",de="Fackelträger des vierzehnten Ganges",fr="Porteur de la torche du quatorzième promenoir"},
    [723] = {id=723,en="Torchbearer of the 15th Walk",ja="第15ウォークのトーチベアラー",de="Fackelträger des fünfzehnten Ganges",fr="Porteur de la torche du quinzième promenoir"},
    [724] = {id=724,en="Delver of the Depths",ja="未踏領域を踏破せし者",de="Durchquerer unerforschter Lande",fr="Grand explorateur impérial"},
    [725] = {id=725,en="Subjugator of the Lofty",ja="ロフティレギオン　サブジュゲーター",de="Himmelsstürmer",fr="Dominateur de la chambre du ciel"},
    [726] = {id=726,en="Subjugator of the Mired",ja="マイアーレギオン　サブジュゲーター",de="Erdenstürmer",fr="Dominateur de la chambre de la terre"},
    [727] = {id=727,en="Subjugator of the Soaring",ja="ソアリングレギオン　サブジュゲーター",de="Luftstürmer",fr="Dominateur de la chambre du vent"},
    [728] = {id=728,en="Subjugator of the Veiled",ja="ベールレギオン　サブジュゲーター",de="Wolkenstürmer",fr="Dominateur de la chambre des nuages"},
    [729] = {id=729,en="Legendary Legionnaire",ja="パラマウントレギオン　サブジュゲーター",de="Kosmosstürmer",fr="Dominateur de la chambre du firmament"},
    [730] = {id=730,en="Witness to Provenance",ja="原初の輝きに触れし者",de="Vom ersten Licht Berührter",fr="Contemplateur de la Provenance"},
    [731] = {id=731,en="Bismarck Flenser",ja="ビスマルク　フレンサー",de="Bismarck-Flenser",fr="Dépeceur de Bismarck"},
    [732] = {id=732,en="Morta Extirpator",ja="モルタ　エクスターペイター",de="Morta-Jäter",fr="Extirpateur de Morta"},
    [733] = {id=733,en="Unsung Heroine",ja="アンサングヒロイン",de="Unbesungener Held",fr="Héroïne oubliée"},
    [734] = {id=734,en="Epic Heroine",ja="エピックヒロイン",de="Gefeierter Held",fr="Héroïne célébrée"},
    [735] = {id=735,en="Epic Einherjar",ja="エインヘリヤルエピック",de="Epischer Einheriar",fr="Einherjar épique"},
    [736] = {id=736,en="Mender of Wings",ja="翼を抱きし者",de="Reminiszenzen-Wächter",fr="Porteur d'aile de la Déesse"},
    [737] = {id=737,en="Champion of the Dawn",ja="アルタナの神兵",de="Flügel der Göttin",fr="Guerrier de la Déesse"},
    [738] = {id=738,en="Bushin Aspirant",ja="武神の門出に立つ者",de="Mit 99 Leveln, da fängt das Leben an",fr="Aspirant au Bushin"},
    [739] = {id=739,en="Bushin-Ryu Inheritor",ja="武神流免許皆伝",de="Wanderer auf dem Weg des Bushin",fr="Combattant indomptable"},
    [740] = {id=740,en="Temenos Emancipator",ja="テメナスエマンシペーター",de="Temenos-Erlöser",fr="Emancipateur de Temenos"},
    [741] = {id=741,en="Apollyon Razer",ja="アポリオンレイザー",de="Apollyon-Auslöscher",fr="Dévastateur d'Apollyon"},
    [742] = {id=742,en="Goldwing Squasher",ja="ゴールドウィング　スクァッシャー",de="Goldwing-Zerquetscher",fr="Ecraseur de Goldwing"},
    [743] = {id=743,en="Silagilith Detonator",ja="サイレジャリス　デトネーター",de="Silagilith-Sprenger",fr="Dynamiteur de Silagilith"},
    [744] = {id=744,en="Surtr Smotherer",ja="スルト　スマザラー",de="Surtr-Besänftiger",fr="Etouffeur de Surtr"},
    [745] = {id=745,en="Dreyruk Predominator",ja="ドレールック　プレドミネーター",de="Dreyruk-Dompteur",fr="Prédominateur de Dreyruk"},
    [746] = {id=746,en="Samursk Vitiator",ja="サムルスク　ビティエター",de="Samursk-Vernichter",fr="Viciateur de Samursk"},
    [747] = {id=747,en="Umagrhk Manemangler",ja="ウマゲルク　メーンマングラー",de="Umagrhk-Torero",fr="Piétineur de crinière d'Umagrhk"},
    [748] = {id=748,en="Supernal Savant",ja="スパーナルサバント",de="Astronom",fr="Savant supernel"},
    [749] = {id=749,en="Solar Sage",ja="ソーラーセージ",de="Sonnenweiser",fr="Sage solaire"},
    [750] = {id=750,en="Bolide Baron",ja="ボライドバロン",de="Bolidbaron",fr="Baron des bolides"},
    [751] = {id=751,en="Moon Maven",ja="ムーンメ―ヴェン",de="Mondgelehrter",fr="Expert lunaire"},
    [752] = {id=752,en="Izyx Vexer",ja="イジックス　ヴェックサー",de="Izyx-Irritator",fr="Perturbateur d'Izyx"},
    [753] = {id=753,en="Grannus Garroter",ja="グランナス　ガロッター",de="Grannus-Garotteur",fr="Garrotteur de Grannus"},
    [754] = {id=754,en="Svaha Striker",ja="スヴァッハ　ストライカー",de="Svaha-Isolator",fr="Cogneur de Svaha"},
    [755] = {id=755,en="Melisseus Domesticator",ja="メリシアス　ドメステケイター",de="Melisseus-Domestizierer",fr="Apprivoiseur de Melisseus"},
    [756] = {id=756,en="Waterway Exemplar",ja="ウォーターウェー　エグゼンプラー",de="Aquädukt-Aushängeschild",fr="Marmouset des voies d'eau"},
    [757] = {id=757,en="Cavern Exemplar",ja="カーヴァン　エグゼンプラー",de="Höhlen-Heroe",fr="Marmouset des cavernes"},
    [758] = {id=758,en="Muyingwa Wingcrusher",ja="ムイングワ　ウイングクラッシャー",de="Muyingwa-Flügelstutzer",fr="Pesticide de Muyingwa"},
    [759] = {id=759,en="Dakuwaqa Trawler",ja="ダクワカ　トローラー",de="Dakuwaqa-Drescher",fr="Chalutier de Dakuwaqa"},
    [760] = {id=760,en="Tojil Douser",ja="トヒル　ダウザー",de="Tojil-Ausknipser",fr="Arroseur de Tojil"},
    [761] = {id=761,en="Colkhab Dethroner",ja="コルカブ　デスローナー",de="Colkhab-Entthroner",fr="Ecrabouilleur de Colkhab"},
    [762] = {id=762,en="Achuka Glaciator",ja="アチュカ　グレイシエイター",de="Achuka-Brandmeister",fr="Extincteur d'Achuka"},
    [763] = {id=763,en="Tchakka Desiccator",ja="チャッカ　デシケイター",de="Tchakka-Fliegenfischer",fr="Pourfendeur de Tchakka"},
    [764] = {id=764,en="Weald Exemplar",ja="ウィールド　エグゼンプラー",de="Naturforscher",fr="Marmouset des forêts"},
    [765] = {id=765,en="Hurkan Birdlimeist",ja="フルカン　バードライミスト",de="Hurkan-Flügelstutzer",fr="Bagueur de Hurkan"},
    [766] = {id=766,en="Yumcax Logger",ja="ユムカクス　ローガー",de="Yumcax-Fäller",fr="Bûcheron de Yumcax"},
    [767] = {id=767,en="Colkhab Hivecrusher",ja="コルカブ　ハイヴクラッシャー",de="Colkhab-Schwarmzerstörer",fr="Ecraseur de ruche de Colkhab"},
    [768] = {id=768,en="Achuka Coagulator",ja="アチュカ　コアギュレイター",de="Achuka-Koagulans",fr="Coagulateur d'Achuka"},
    [769] = {id=769,en="Tchakka Filleter",ja="チャッカ　フィレーヤー",de="Tchakka-Filetierer",fr="Déchiqueteur de Tchakka"},
    [770] = {id=770,en="Rabbit Tussler",ja="ラビット　タッスラー",de="Rabbit-Raufbold",fr="Ennemi des lapins"},
    [771] = {id=771,en="Helminth Mincer",ja="ヘルミンス　ミンサー",de="Darmwurm-Häcksler",fr="Eminceur de vers"},
    [772] = {id=772,en="Mandragardener",ja="マンドラ　ガーデナー",de="Mandra-Gärtner",fr="Jardinier des mandragoras"},
    [773] = {id=773,en="Moppet Massacrer",ja="モペット　マサカーラー",de="Moppet-Massakrierer",fr="Massacreur de poupées"},
    [774] = {id=774,en="Rip-roaring Limbrender",ja="ローリング　リムレンダー",de="Knochenberster",fr="Démembreur rugissant"},
    [775] = {id=775,en="Shell Shocker",ja="シェル　ショッカー",de="Shell-Spalter",fr="Dynamiteur de carapace"},
    [776] = {id=776,en="Yagudo Coopkeeper",ja="ヤグード　クップキーパー",de="Yagudo-Nesttrampler",fr="Gardien de poulailler"},
    [777] = {id=777,en="Gigasplosion Expert",ja="ギガスプロード　エキスパート",de="Giga-Sprengexperte",fr="Expert en gigasplosion"},
    [778] = {id=778,en="Brother-in-arms",ja="ブラザーインアームズ",de="Kampfgefährte",fr="Frère d'armes"},
    [779] = {id=779,en="Antica Hunter",ja="アンティカ　ハンター",de="Antica-Jäger",fr="Chasseur d'Anticas"},
    [780] = {id=780,en="Amphibian Adulterator",ja="アンフィ　アダルタレイター",de="Amphibien-Adulterator",fr="Décimeur d'amphibiens"},
    [781] = {id=781,en="Tonberry Toppler",ja="トンベリ　トップラー",de="Tonberry-Tackler",fr="Tombeur de Tonberry"},
    [782] = {id=782,en="Bloodline Corrupter",ja="ブラッドライン　コラプター",de="Blutlinien-Korrumpierer",fr="Corrupteur de lignée"},
    [783] = {id=783,en="Kumhau Roaster",ja="クムハウ　ロースター",de="Kumhau-Röster",fr="Rôtisseur de Kumhau"},
    [785] = {id=785,en="Quieter of Ancient Thoughts",ja="エンシェントソート　クワイエター",de="Verstummer antiker Gedanken",fr="Effaceur d'anciennes pensées"},
    [786] = {id=786,en="Ark Hume Humiliator",ja="アークヒューム　ヒューミリアター",de="Ark Angel Hume-Vernichter",fr="Insulteur d'Ark Hume"},
    [787] = {id=787,en="Ark Elvaan Eviscerator",ja="アークエルヴァーン　エビサレイター",de="Ark Angel Elvaan-Erniedriger",fr="Eviscérateur d'Ark Elvaan"},
    [788] = {id=788,en="Ark Mithra Maligner",ja="アークミスラ　マライナー",de="Ark Angel Mithra-Bezwinger",fr="Calomniateur d'Ark Mithra"},
    [789] = {id=789,en="Ark Tarutaru Trouncer",ja="アークタルタル　トラウンサー",de="Ark Angel Tarutaru-Drangsalierer",fr="Etrilleur d'Ark Tarutaru"},
    [790] = {id=790,en="Ark Galka Gouger",ja="アークガルカ　ガウジャー",de="Ark Angel Galka-Triumphator",fr="Escroqueur d'Ark Galka"},
    [791] = {id=791,en="Pentarch Pacifier",ja="ペンターク　パシファイアー",de="Pentark-Peiniger",fr="Pacificateur de pentarchie"},
    [792] = {id=792,en="Dream Distiller",ja="ドリーム　デスティラー",de="Traum-Destillateur",fr="Distilleur de rêves"},
    [793] = {id=793,en="Ra'Kaznar Exemplar",ja="ラ・カザナル　エグゼンプラー",de="Ra’Kaznar-Recke",fr="Exemplaire de Ra'Kaznar"},
    [794] = {id=794,en="Utkux Peltburner",ja="アットクックス　ペルトバーナー",de="Utkux-Pelzverbrenner",fr="Brûleur de pelage d'Utkux"},
    [795] = {id=795,en="Cailimh Plumageplucker",ja="カイルイム　プルメッジプラッカー",de="Cailimh-Rupfer",fr="Déplumeur de Cailimh"},
    [796] = {id=796,en="Wopket Trunksplitter",ja="ウォップケット　トランクスプリッター",de="Wopket-Stammspalter",fr="Fendeur de tronc de Wopket"},
    [797] = {id=797,en="Ouryu Obfuscator",ja="オウリュウ　オブフスケイター",de="Ouryu-Obsieger",fr="Dérouteur d'Ouryu"},
    [798] = {id=798,en="Unwavering Blaze",ja="アンウェーヴ　ブレイズ",de="Standhafte Flamme",fr="Flamme éternelle"},
    [799] = {id=799,en="Lancelord Divester",ja="ランスロード　ディベスター",de="Lancelord-Entblößer",fr="Dépouilleur de Gaheel Ja"},
    [800] = {id=800,en="Gessho Pinioner",ja="ゲッショー　ピニオナー",de="Gessho-Flügelstutzer",fr="Déplumeur de Gessho"},
    [836] = {id=836,en="Geodancer",ja="見習い風水士",de="Stolzer Luopan-Besitzer",fr="Timide géomancien"},
    [837] = {id=837,en="Runic Engraver",ja="ルーンを刻みし者",de="Runenfechter-Novize",fr="Tatoué runique"},
    [838] = {id=838,en="Apprentice Tarutaru Sauce Manager",ja="タルタル★ソース・マネージャー見習い",de="Manager wider Willen",fr="Apprenti impresario des Sauce★tarutaru"},
    [839] = {id=839,en="Vegetable Revolutionary",ja="ベジタブルレボリューションヘルパー",de="Rübenrevoluzzer",fr="Contributeur de la révolution légumière"},
    [840] = {id=840,en="Friend to Gluttons",ja="食いしん坊の友",de="Geduldiger Proviantmeister",fr="Ami des gourmands"},
    [841] = {id=841,en="Waypoint Warrior",ja="シャルルのお気に入り",de="Sharurus bester Freund",fr="Favori de Sharuru"},
    [842] = {id=842,en="Ulbukan Stalwart",ja="混沌への抵抗者",de="Familientherapeut",fr="Rassureur de famille paranoïaque"},
    [843] = {id=843,en="Toxin Tussler",ja="どくどくざえもん",de="Freischwimmer",fr="Maître-nageur de la Zoldeff"},
    [844] = {id=844,en="Spiritual★Star",ja="万象の★地星",de="Ganzheitlicher★Stern",fr="Etoile★universelle"},
    [845] = {id=845,en="Stippling★Star",ja="刻印の★剣星",de="Gezeichneter★Stern",fr="Etoile★gravée"},
    [846] = {id=846,en="Geomancipator",ja="自然の理解者",de="Naturversteher",fr="Amoureux de la nature"},
    [847] = {id=847,en="Trialed-and-True Runeist",ja="理の執行者",de="Vernunft-Vollstrecker",fr="Clairvoyant avisé"},
    [848] = {id=848,en="Queen's Confidante",ja="女王の信頼を得し者",de="Vertrauter der Königin",fr="Bras droit de la reine"},
    [849] = {id=849,en="Princess's Partisan",ja="若姫さまの守り手",de="Beschützer der Prinzessin",fr="Protecteur de la princesse"},
    [850] = {id=850,en="Potation Pathfinder",ja="ドリンクエクスプローラー",de="Flaschenkind",fr="Spécialiste des boissons"},
    [851] = {id=851,en="Storied Geomancer",ja="深淵なる大風水士",de="Grandioser Geomant",fr="Grand géomancien des abysses"},
    [852] = {id=852,en="Ultimate Runeist",ja="灼然なる大魔導剣士",de="Wundervoller Runenfechter",fr="Grand épéiste flamboyant"},
    [853] = {id=853,en="Mog Garden Seedling",ja="モグガーデンのタマゴ",de="Ein Ei im Mog-Garten",fr="Petite graine des Jardins Mog"},
    [854] = {id=854,en="Kit Empathizer",ja="にぅにぅオーナー",de="Ein Herz für Kätzchen",fr="Pro de l'empathie"},
    [855] = {id=855,en="Jingly Dangler",ja="ちゃりちゃりオーナー",de="Ein Herz für Langnasen",fr="Pro de la corde"},
    [856] = {id=856,en="Mole Manipulator",ja="アニキのオーナー",de="Ein Herz für Maulwürfe",fr="Maître des taupes"},
    [857] = {id=857,en="Agrarian Novice",ja="農耕初心者",de="Unkundiger Bauer",fr="Agriculteur débutant"},
    [858] = {id=858,en="Agrarian Initiate",ja="農耕中級者",de="Beschlagener Bauer",fr="Agriculteur confirmé"},
    [859] = {id=859,en="Agrarian Professional",ja="農耕上級者",de="Hingebungsvoller Landwirt",fr="Agriculteur professionnel"},
    [860] = {id=860,en="Agrarian Virtuoso",ja="農耕の達人",de="Sachkundiger Landwirt",fr="Agriculteur expert"},
    [861] = {id=861,en="Agrarian Tutelar",ja="農耕の超人",de="Agronom",fr="Maître agriculteur"},
    [862] = {id=862,en="Weed Praetor",ja="草木の守り手",de="Wächter der Gräser",fr="Sauveur de la verdure"},
    [863] = {id=863,en="Tree Praetor",ja="樹木の守り手",de="Wächter der Bäume",fr="Sauveur des arbres"},
    [864] = {id=864,en="Thicket Praetor",ja="林の守り手",de="Wächter des Forsts",fr="Sauveur des bois"},
    [865] = {id=865,en="Forest Praetor",ja="森の守り手",de="Wächter des Waldes",fr="Sauveur de la forêt"},
    [866] = {id=866,en="Jungle Praetor",ja="ジャングルの守り手",de="Wächter des Dschungels",fr="Sauveur de la jungle"},
    [867] = {id=867,en="Copper Mattock",ja="カッパーマトック",de="Kupfernes Haueisen",fr="Pioche de cuivre"},
    [868] = {id=868,en="Silver Mattock",ja="シルバーマトック",de="Silbernes Haueisen",fr="Pioche d'argent"},
    [869] = {id=869,en="Mythril Mattock",ja="ミスリルマトック",de="Mithril-Haueisen",fr="Pioche de mithril"},
    [870] = {id=870,en="Gold Mattock",ja="ゴールドマトック",de="Goldenes Haueisen",fr="Pioche d'or"},
    [871] = {id=871,en="Adamanttock",ja="アダマンマトック",de="Adamantium-Haueisen",fr="Pioche d'adamantium"},
    [872] = {id=872,en="Puddle Patron",ja="水溜まり師匠",de="Pfützenmeister",fr="Expert en points d'eau"},
    [873] = {id=873,en="Swamp Savant",ja="沼師匠",de="Tümpelmeister",fr="Expert en marais"},
    [874] = {id=874,en="Pond Preceptor",ja="池師匠",de="Teichmeister",fr="Précepteur pour étangs"},
    [875] = {id=875,en="River Regent",ja="渓流師匠",de="Seemeister",fr="Régent des rivières"},
    [876] = {id=876,en="Monke-Onke Master",ja="モンケオンケ師匠",de="Monke-Onke-Meister",fr="Maître des monke-onkes"},
    [877] = {id=877,en="Sardineophyte",ja="サーディンちゃん",de="Sardinchen",fr="Sardinéophyte"},
    [878] = {id=878,en="Calamareeler",ja="カラマリちゃん",de="Mini-Kalmar",fr="Pêcheur de calmars"},
    [879] = {id=879,en="Octopotentate",ja="オクトパちゃん",de="Mini-Oktopus",fr="Maître des pieuvres"},
    [880] = {id=880,en="Giant Squimperator",ja="スキッドちゃん",de="Tintenfischlein",fr="Empereur des calmars"},
    [881] = {id=881,en="Leviauthority",ja="リヴァイアちゃん",de="Leviathanchen",fr="Autorité des colosses"},
    [882] = {id=882,en="Novice Nurseryman",ja="園丁",de="Hobbygärtner",fr="Pépiniériste amateur"},
    [883] = {id=883,en="Lesser Landscaper",ja="主任庭師",de="Erfahrener Gärtner",fr="Paysagiste inférieur"},
    [884] = {id=884,en="Greater Gardener",ja="上級庭師",de="Gartenprofi",fr="Jardinier de renom"},
    [885] = {id=885,en="Honored Horticulturist",ja="宮廷庭師",de="Königlicher Gärtner",fr="Horticulteur célèbre"},
    [886] = {id=886,en="Mog Gardener",ja="モグガーデナー",de="Mog-Gärtner",fr="Jardinier Mog"},
    [887] = {id=887,en="Brygidesque Manager",ja="ブリジッド系マネージャー見習い",de="Manager in Ausbildung",fr="Apprenti manager chez Brygid"},
    [888] = {id=888,en="Vegetable Evolutionary",ja="ベジタブルエボリューションヘルパー",de="Rübenevoluzzer",fr="Visionnaire ès légumes"},
    [889] = {id=889,en="Blade Enthusiast",ja="魔導マニア",de="Runenfetischist",fr="Epéiste fanatique"},
    [890] = {id=890,en="Runic Emissary",ja="ルーン宅配人",de="Runenlieferant",fr="Livreur de runes"},
    [891] = {id=891,en="Maester of Maddening",ja="焦らしマイスター",de="Brennender Meister",fr="Maître provocateur"},
    [892] = {id=892,en="Sunshine Cadet",ja="雲飛ばす東風",de="Wolkenvertreiber",fr="Porteur d'espoir venu de l'Est"},
    [893] = {id=893,en="Quartet Captivator",ja="クワッどコア",de="Mog-Garten-Animateur",fr="Animateur de Jardin Mog"},
    [894] = {id=894,en="The Trustworthy",ja="信頼・親愛・友情を抱く者",de="Vertrauensschöpfer",fr="Meilleur ami"},
    [895] = {id=895,en="The Lovelorn",ja="ラブラブウォッチャー",de="Amors Gehilfe",fr="Voyeur de tourtereaux"},
    [896] = {id=896,en="Inventor Extraordinaire",ja="INV.ワークスツカイッパー",de="Erfinderzunft-Briefträger",fr="Coursier des Ingénieurs"},
    [897] = {id=897,en="Boomy and Busty",ja="お遊戯王",de="Zocker-König",fr="Joueur dans l'âme"},
    [898] = {id=898,en="Weatherer of Brumal Climes",ja="絶零の開拓者",de="Blitzfrostiger Pionier",fr="Diplomate des glaces"},
    [899] = {id=899,en="White Knight",ja="姫を救いし勇者",de="Prinzessinnen-Retter",fr="Héros de Sa Majesté"},
    [900] = {id=900,en="Light of Dawn",ja="大いなる暁の継承者",de="Erbe der Morgendämmerung",fr="Héritier de la grande aube"},
    [901] = {id=901,en="Observer of Fateful Cubes",ja="一天地六の観測者",de="Würfelexperte",fr="Jeteur de dés"},
    [902] = {id=902,en="Knower of Untruths",ja="無知なる知者",de="Unwissender Weise",fr="Renvoyé à ses études"},
    [903] = {id=903,en="Ulbukan Understudy",ja="ウルブカの守護者見習い",de="Angehender Ulbuka-Beschützer",fr="Apprenti gardien d'Ulbuka"},
    [904] = {id=904,en="Keeper of Ulbuka",ja="ウルブカの守護者",de="Ulbuka-Beschützer",fr="Gardien d'Ulbuka"},
    [905] = {id=905,en="Radiance of Daybreak",ja="暁の光",de="Licht der Morgendämmerung",fr="Lumière de l'aube"},
    [906] = {id=906,en="Wibbly Wobbly Woozy Warrior",ja="あばばばヒーラー",de="Moogle-Ruhestifter",fr="Guérisseur de tous les états"},
}, {"id", "en", "ja", "de", "fr"}

--[[
Copyright © 2013-2014, Windower
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Windower nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Windower BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
